### ISSUE TITLE
server-side initial require

### ISSUE THREAD

**Issue by mmahalwy** [shakacode/bootstrap-loader#10]
While using isomorphic tools (https://www.npmjs.com/package/webpack-isomorphic-tools), it would be nice to avoid the initial white flash by requiring the bootstrap file. What file should be required?

In previous library, we'd just require the `bootstrap.config.js` file. Is there a counterpart here?

**Comment by justin808** [comment]
@mmahalwy I really don't know as I don't use that library. I think you can require the new loader and pass in any dummy file. The file param won't be used. The .bootstraprc file will be used.

**Comment by justin808** [comment]
@mmahalwy Please reopen this issue if you think this requires a code fix on our part.

**Comment by mmahalwy** [comment]
Maybe @halt-hammerzeit can chime in?

**Comment by halt-hammerzeit** [comment]
@mmahalwy well, I never used this loader in my projects and I'm not sure how it works, but judging from the `examples` folder it has a webpack `entry` with a `pitch` function
https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.loader.js#L24
I don't know how this whole thing works but it outputs something in the form of `resultOutput` variable and then it somehow appears on the webpage I guess
https://github.com/shakacode/bootstrap-loader/blob/master/examples/css-modules/app/markup/bootstrap-dev.html#L6

So, to reduce (or totally remove if you got all the styles) the flashing you can insert inside your `<style/>` tag something like `resultOutput + '\n' + [your css styles]`.

The first thing: `resultOutput` contains `CSS + js` so you'll have to take only the `CSS` part from it (the project author might know how to do it).
The second thing: to get ahold of that `resultOutput` variable i guess you can just substitute it with `require('bootstrap-loader')` as per the readme. In this case there is a possibility to tell it to contain only `CSS` without `js` using loader parameters, something like `require('bootstrap-loader?extract_only_css=true')`. Again, the project author should know how to do it.
https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.loader.js#L118
https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.config.js

And, that's it - you should have your issue resolved.

**Comment by justin808** [comment]
@halt-hammerzeit @mmahalwy Thanks! If you've got a PR, we'd definitely take it so long as it does not break others.

**Comment by mmahalwy** [comment]
@halt-hammerzeit thanks! I will implement it and report back

**Comment by mihirsoni** [comment]
@mmahalwy Did you find any workaround to do this ?

**Comment by justin808** [comment]
PR that might be close: https://github.com/shakacode/bootstrap-loader/pull/123

and 

repro case: https://github.com/shakacode/react-starter-kit-with-bootstrap-loader/pull/1

**Comment by justin808** [comment]
I've commented on issue: https://github.com/kriasoft/react-starter-kit/pull/782

and I've created https://github.com/shakacode/react-starter-kit-with-bootstrap-loader/pull/1

CC: @zeyton

**Comment by Judahmeek** [comment]
Since #123 is now closed, should this issue be closed as well?

**Comment by idangozlan** [comment]
Is there any example of how to implement server side rendering for bootstrap css on development?

**Comment by justin808** [comment]
I'm going to close this for now.
