### ISSUE TITLE
extract-text-webpack-plugin error after updated

### ISSUE THREAD

**Issue by colinshen** [shakacode/bootstrap-loader#102]
```
"webpack": "^2.1.0-beta.8",
 "extract-text-webpack-plugin": "^2.0.0-beta.1",
 "bootstrap-loader": "^1.0.10",
```

```
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js
Module build failed: Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).
Example: if your old code looked like this:
    ExtractTextPlugin.extract('style-loader', 'css-loader')

You would change it to:
    ExtractTextPlugin.extract({ notExtractLoader: 'style-loader', loader: 'css-loader' })

The available options are:
    loader: string | object | loader[]
    notExtractLoader: string | object | loader[]
    publicPath: string

    at Function.ExtractTextPlugin.extract (/Users/shensi/codes/uhccjProject/uhccjMain/node_modules/extract-text-webpack-plugin/index.js:171:9)
    at exports.default (/Users/shensi/codes/uhccjProject/uhccjMain/node_modules/bootstrap-loader/lib/utils/buildExtractStylesLoader.js:21:28)
    at Object.module.exports.pitch (/Users/shensi/codes/uhccjProject/uhccjMain/node_modules/bootstrap-loader/lib/bootstrap.loader.js:128:86)
 @ ./~/bootstrap-loader/extractStyles.js 1:0-58
 @ multi app

ERROR in chunk vendor [entry]
app.0b1ea0230a51c0a8c213.js
Chunk.entry was removed. Use hasRuntime()
```

**Comment by justin808** [comment]
@alexfedoseev We might need an update for this. However. Let's wait until 2.0.0 is released.

@colinshen Any chance that you can create a PR for what we need?

**Comment by colinshen** [comment]
@justin808 I'm sorry. I'm new to github..so, I dont know how to do it..

**Comment by vpanjganj** [comment]
@justin808 is it possible that `bootsrap-loader` uses its own 'webpack` and `extract-text-webpack-plugin` as a dependency with locked version?

**Comment by justin808** [comment]
https://github.com/shakacode/bootstrap-loader/blob/master/package.json#L36

The dependencies are listed there. "extract-text-webpack-plugin" is not listed.

**Comment by vpanjganj** [comment]
True, I meant adding it as a dependency with a specified version.

**Comment by vpanjganj** [comment]
@justin808 I spent a whole day on it and couldn't make it work with nested dependencies. Removed it from peerDependencies and added dependencies.
keep getting this:
```
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/Vahid/projects/bootstrap-loader/examples/basic/node_modules/bootstrap-loader/node_modules/extract-text-webpack-plugin/loader.js:21:9)
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js 1:0-273
``
I guess using `'bootstrap-loader/extractStyles’` in the webpack entry  makes `buildExtractStylesLoader` to require `'extract-text-webpack-plugin’` from the tope level dependency rather than its own dedicated version.

**Comment by justin808** [comment]
@vpanjganj On your project, you need the extract-text-plugin listed as a "dependency" and not a peer.

**Comment by vpanjganj** [comment]
Just to clearify. Ideally, `bootstrap-loader` and the project that uses `bootstrap-loader` both should be able to have different versions of `extract-text-webpack-plugin` as dependecies. So far `bootstrap-loader` relies on the host project's using peerDependency. In 'bootstrap-loader' I changed it from peerDependency to dependency locked on ` "extract-text-webpack-plugin": "0.9.1"`. And in the project that consumes 'bootstrap-loader' I use `extract-text-webpack-plugin` as usual on version `1.0.1` or `2.0.0-beta.3`. But still 'bootstrap-loader' ignores its own version of extract text.

**Comment by vpanjganj** [comment]
It would be good having `extract-text-webpack-plugin` as peerDependency locked on version 0.9.1. And a new beta release of `bootstrap-loader` that only supports newer versions of `extract-text-webpack-plugin`.

**Comment by justin808** [comment]
@vpanjganj @alexfedoseev We probably need to specify a range for the peer dependency. @vpanjganj Any chance that you'd like to do a PR on this?

**Comment by vpanjganj** [comment]
I will, is it possible to have a beta release that works with `extract-text-webpack-plugin` 2 beta?

**Comment by justin808** [comment]
@vpanjganj Sure on the beta release. Let me know when you're ready.

**Comment by vpanjganj** [comment]
@justin808 Cool, I just made a PR for the peerDependency bit. Also, I'm working on a different branch to support extract text plugin 2. Since this will be a beta release does it have to be a normal pull request to master as well?

**Comment by vpanjganj** [comment]
@justin808 I think I'm done with the beta version. You can have a look at it here and let me know when you want the pull request (it will need some bits to change) [https://github.com/vpanjganj/bootstrap-loader/tree/support-extract-text-plugin-2](https://github.com/vpanjganj/bootstrap-loader/tree/support-extract-text-plugin-2)

Just FYI: 

1. I used Node 6.2.0 and npm 3.10.6. 
2. I had to change font-awsome-loader in order to make it work; it's already a pull request for it and needs revising. 
3. In the sample projects, 'bootstrap-loader' dependecies still point to my local machine which needs to be changed to beta release version after push. 
4. In sample projects' webpack settings, I changed `webpack.ProvidePlugin` parameters from doublequote to singlequote for linting. I'm not sure whether it was left like that intentionally however my change didn't break anything.
```
    new webpack.ProvidePlugin({
      'window.Tether': 'tether',
    }),
```

**Comment by justin808** [comment]
Please create the PR.

In terms of a beta version, we can release anytime off of the branch.

We need to get the customizable bootstrap-loader location PR #90 in first.

**Comment by vinhlh** [comment]
Waiting the release of this PR 💃

**Comment by vpanjganj** [comment]
@vinhlh @colinshen It's good to go now. Just install `bootstrap-loader@2.0.0-beta`

**Comment by kingluddite** [comment]
bootstrap-loader@2.0.0-beta.7 as of 8/31/2016

**Comment by justin808** [comment]
Thanks to all for your patience. If any of you want to get involved in helping me maintain this project, let me know!
