### ISSUE TITLE
Upgrade from bootstrap-sass-loader produces error

### ISSUE THREAD

**Issue by davidfurlong** [shakacode/bootstrap-loader#104]
ERROR in ./~/bootstrap-loader/lib/bootstrap.scripts.loader.js!./~/bootstrap-loader/no-op.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../bootstrap-sass/assets/javascripts/bootstrap/util in /node_modules/bootstrap-loader

 
[0] ERROR in ./~/css-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js
[0] Module build failed: 
[0] undefined
[0] ^
[0]       File to import not found or unreadable: ../bootstrap-sass/assets/stylesheets/bootstrap/_reboot
[0] Parent style sheet: stdin

Thanks for any help.

**Comment by justin808** [comment]
@davidfurlong is bootstrap-sass listed in your package.json like this:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/package.json#L57

Can we close this issue?

**Comment by davidfurlong** [comment]
@justin808 I decided to stick with bootstrap-sass-loader as trying to debug this was taking too much time. Thus you can close this issue (although the issue may reappear with someone else). Thanks for the fast reply.

I had bootstrap-sass installed as a saved dependency and I verified that the folder  node_modules/bootstrap-sass/asset/javascripts/bootstrap existed, however it was missing util node_modules/bootstrap-sass/assets/javascripts/bootstrap/util. But this file isn't at /bootstrap/js/util either, so perhaps I'm thinking about this wrong

**Comment by justin808** [comment]
@davidfurlong Ah, I see your title. There's a lot to change! Please read the README.md. It won't take you more than 30 min (or else message me!).

**Comment by davidfurlong** [comment]
I did go through the upgrade instructions. I wouldn't waste your time by not having utilized the resources available.

**Comment by justin808** [comment]
Thanks @davidfurlong. You might have a typo, or we might have something missing in our docs. 

the main error is:

> Module not found: Error: Cannot resolve 'file' or 'directory' ../bootstrap-sass/assets/javascripts/bootstrap/util in /node_modules/bootstrap-loader

**Comment by gazorg** [comment]
I have exactly the same problem. Is there a way to solve this? Or to troubleshoot it. As I understand it webpack looks for a file (or directory) called util that simply does not exist in the javascripts/bootstrap directory. This is either an error in the bootstrap-sass package or some quite subtle error in the webpack config.

**Comment by justin808** [comment]
We're looking in the node_modules folder. Please take a look there.
