### ISSUE TITLE
`.idea` not being excluded.

### ISSUE THREAD

**Issue by vpanjganj** [shakacode/bootstrap-loader#106]
It will be good to add `.idea` folders (example projects have their own `.idea` folders as well) in `.gitignore`. I also noticed that this project setting folder get bundled in the actual build within `node_modules` :

![screen shot 2016-07-22 at 12 10 05](https://cloud.githubusercontent.com/assets/8151667/17055637/fc3fe5be-5005-11e6-8832-bb7c8e07942a.png)

**Comment by justin808** [comment]
Please see this: 

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

Consider creating a global one.
