### ISSUE TITLE
Undefined variable: "$brand-primary".

### ISSUE THREAD

**Issue by zh-wowtv** [shakacode/bootstrap-loader#113]
Here is my user.scss:

```
.login-page {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	overflow: auto;
    background: $brand-primary;
	text-align: center;
	color: #fff;
	padding: 3em;
}
```

In my Javascript:

```
import 'bootstrap-loader';
import './user.scss';

```

I got this error message.  But isn't **$brand-primary** a bootstrap variable? What could be the reason? Can anybody help?

**Comment by Phyks** [comment]
Same problem here.

From [this](https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic/.bootstraprc#L54-L57) I guess this way does not work. But then, I am not sure how to access Bootstrap variables from a CSS module… =(

**Comment by bennettrogers** [comment]
Here you go: #9

**Comment by Phyks** [comment]
Thanks a lot! Maybe this is something worth mentionning in the README?

**Comment by justin808** [comment]
@Phyks We'd really appreciate a PR on the README.md for this!
