### ISSUE TITLE
.bootstraprc-4-default does not work with new file and folder structure of Bootstrap@4.0.0-alpha.3

### ISSUE THREAD

**Issue by dani0010** [shakacode/bootstrap-loader#117]
Even after issue #112  is remedied, bootstrap-loader will not load Bootstrap properly because of changes to the file and folder structure in two areas:

1. CSS Components pager and labels are no longer present. If set to true in the config, loader will complain about those files not being found. These don't create a problem with the exported css because the files aren't found, and they're not needed.

2. Utilities are now handled similarly to mixins. The bootstrap/scss/_utilities.scss file simply contains several import statements for utilities files which are now in bootstrap/scss/utilities folder with separate files for the following utilities:

- background
- clearfix
- display
- flex
- pulls
- screenreaders
- spacing
- text
- visibility

To get bootstrap-loader to export CSS with all these items, set #Utility class > utilities to true and all the others to false. Or turn them all off by setting utilities to false as well to turn them all off. Either way, we lose the granular control over the utilities classes. I don't know enough to say whether they can still function independently.

Given that flex is now in the utilities area and not in bootstrap-flex, I am wondering if the useFlexbox config option is still working at all. There are probably other issues related to the file and folder changes that I missed.

**Comment by justin808** [comment]
@dani0010, Thank you!

If you can help us get this solved, many of us will be very happy and grateful. We have a slack room that you might want to join.

**Comment by dani0010** [comment]
After more digging I can see the use flex box option will be fine. Although the rules have been refactored, the switch is still in the same place and will properly import or ignore them.

**Comment by justin808** [comment]
@dani0010 close this one?

**Comment by dani0010** [comment]
It's not resolved. Bootstrap is shipping a patch for Alpha 4.3 as you see here: https://github.com/twbs/bootstrap/issues/20373That will break bootstrap-loader for the reasons in this issue.

**Comment by dani0010** [comment]
https://github.com/twbs/bootstrap/issues/20373

**Comment by kwelch** [comment]
I came across this issue also today. Migrating back to alpha.2 fixed the issue. 

I was getting an error asking is bootstrap was installed, when using alpha.3. not sure if that is the same error but sounded similar.

**Comment by justin808** [comment]
Alpha 4! https://github.com/twbs/bootstrap/issues/20631

**Comment by justin808** [comment]
Does anybody want to submit a PR with the following changes? Please verify the examples work, per https://github.com/shakacode/bootstrap-loader/blob/master/CONTRIBUTING.md

* https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic/package.json#L44
* https://github.com/shakacode/bootstrap-loader/blob/a4ad66f67815a3bd186f9556e99529407a7bccc8/examples/css-modules/package.json#L46

And in the v1 branch:

* https://github.com/shakacode/bootstrap-loader/blob/v1/examples/css-modules/package.json#L46
* https://github.com/shakacode/bootstrap-loader/blob/v1/examples/basic/package.json#L44

We should update the regular bootstrap-sass to 3.3.7 as well.


![2016-09-07_12-29-22](https://cloud.githubusercontent.com/assets/1118459/18330908/167e44fa-74f7-11e6-9167-1f72bfab4542.png)
