### ISSUE TITLE
Webpack Peer Dependency fails for `webpack@2.1.0-beta.20`

### ISSUE THREAD

**Issue by robwise** [shakacode/bootstrap-loader#118]
Relates to this peer dependency: https://github.com/shakacode/bootstrap-loader/blob/master/package.json#L44

```shell
npm WARN bootstrap-loader@2.0.0-beta.2 requires a peer of webpack@>=2.0.0-beta but none was installed.
```

This is with `webpack@2.1.0-beta.20` installed (notice the minor version is **1** not **0**. I believe this is the cause of the problem because of the special way NPM semver handles pre-release/beta tags.

> If a version has a prerelease tag (for example, 1.2.3-alpha.3) then it will only be allowed to satisfy comparator sets if at least one comparator with the same [major, minor, patch] tuple also has a prerelease tag.

[source](https://docs.npmjs.com/misc/semver#prerelease-tags)

We should therefore change the dependency to be like `webpack@>=2.1.0-beta` (notice the **1**).

**Comment by justin808** [comment]
@alexfedoseev We should get this PR merged...
