### ISSUE TITLE
Logging level of bootstraprc messages

### ISSUE THREAD

**Issue by iynaix** [shakacode/bootstrap-loader#120]
I run my production build with the following command:

`NODE_ENV=production webpack --config=webpack.config.prod.js --profile --json > build.json`

With the most recent update to version 2, the build.json begins with the following line: 

`[bootstrap-loader]:  bootstrap-loader is using config file at ...`

which breaks the file as being valid json.

Changing the log level should fix the issue I think.

**Comment by justin808** [comment]
Hi @iynaix,

If you could make a PR, and we'll create a new release.

Thanks.

**Comment by justin808** [comment]
We've made a suggestion on this PR #121. We'd like to get this merged soon!
