### ISSUE TITLE
[question] Are the 2.* bootstrap-loader version incompatible with webpack 1.*

### ISSUE THREAD

**Issue by janusch** [shakacode/bootstrap-loader#122]
Maybe this should be made more clear in the readme?

Will the 1.* branch still be maintained? I am not sure how bumpy the upgrade path from webpack 1 to webpack 2 will be. Hopefully there will be support for newer bootstrap 4 version in the 1.* releses as well!

Thank you!

**Comment by justin808** [comment]
I updated the README.md. Thanks!

No idea on Webpack 2 or Bootstrap 4 upgrades.

Please let me know if my update to the README is clear.

**Comment by janusch** [comment]
It is perfectly clear now, thank you! 

I'll be sticking to v1 for some time.

Have a nice weekend!
