### ISSUE TITLE
useCustomIconFontPath assumes that I have a woff2 file

### ISSUE THREAD

**Issue by denizdogan** [shakacode/bootstrap-loader#128]
I just downloaded a few icons from [IcoMoon](https://icomoon.io/) but when I try to use them, the build fails entirely because there is no .woff2 file. There *is* a .woff file. Any way to make this fail gracefully?

**Comment by justin808** [comment]
1. What is the connection of IcoMoon to this project?
2. Be sure to configure your webpack file to handle both woff2 and woff files.
3. You probably need some adjustments on your image path.

**Comment by justin808** [comment]
@denizdogan Any update?
