### ISSUE TITLE
Unwanted debug logs because process.env.DEBUG is set by npm module "debug"

### ISSUE THREAD

**Issue by damienleroux** [shakacode/bootstrap-loader#129]
Hello

I'm experiencing an issue with [global.__DEBUG__ = loglevel === 'debug' || process.env.DEBUG;](https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.loader.js#L70).

Indeed, I'm using [debug](https://github.com/visionmedia/debug) to log information during my gulp/webpack process. With this framework, I can do:

    import Debug from 'debug';
    const debug = Debug('evenium:js-build-toolsbuild-web');
    ....
    debug('Hello');
    ....

In command line, I can do `set DEBUG=evenium:*` before calling my gulp process. As a result, got at screen all logs called with a debug function instanciated using the string "evenium:":

![image](https://cloud.githubusercontent.com/assets/12717418/17774509/4ef68a20-6554-11e6-8f2a-83df0997388e.png)

My probleme is that I got a lot of logs from bootstrap loader even if I have set in bootstraprc `loglevel: disabled`.

I understand that  [global.__DEBUG__ = loglevel === 'debug' || process.env.DEBUG;](https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.loader.js#L70). activates the bootstrap debug logs because `process.env.DEBUG` is set.

I should be able to defined `DEBUG` for my own need (aka using [debug](https://github.com/visionmedia/debug)) without having bootstrap logs on screen.

**Comment by damienleroux** [comment]
Something like `global.DEBUG = loglevel === 'debug' || process.env.DEBUG && loglevel !== 'disabled';` could be an good solution.

I'll thank you for any advice on this topic :)

**Comment by justin808** [comment]
@damienleroux We could also check if the value of DEBUG is truthy, like YES, yes, TRUE, true, 1, etc.

**Comment by justin808** [comment]
@damienleroux Any chance of a PR from you?

**Comment by damienleroux** [comment]
Yes sure I'm doing that :)

**Comment by damienleroux** [comment]
done: https://github.com/shakacode/bootstrap-loader/pull/130
