### ISSUE TITLE
Babel polyfills missing

### ISSUE THREAD

**Issue by christemple** [shakacode/bootstrap-loader#13]
Hi guys,

I just tried cloning and trying out the examples and run into an issue.

It seems that areas of your code are using ES6 features that require babels polyfills which are not included, for example the `Array.prototype.find` method, examples of which are used here:

https://github.com/shakacode/bootstrap-loader/blob/master/src/utils/processStyleLoaders.js#L28-L31

If I add the babel polyfills as a precursor to using bootstrap-loader in my webpack config file it works.

Is this something you guys have seen before?

Thanks,
Chris Temple

**Comment by justin808** [comment]
@alexfedoseev We might have missed the babel runtime?

**Comment by alexfedoseev** [comment]
@justin808 Yep, we should do it. I guess it's an issue for Node `<=0.12` users.
@christemple What's your node version?

**Comment by christemple** [comment]
@alexfedoseev yep you guessed it, my node version is `v0.12.0`

**Comment by alexfedoseev** [comment]
@christemple @justin808 I investigated this issue and I added `babel-polyfill` instead of `babel-runtime` b/c of [this](https://github.com/babel/babel-loader/issues/73#issuecomment-112094117).

`1.0.3` is published. @christemple Can you try it out and close the issue if it works?

**Comment by christemple** [comment]
Updated to 1.0.3 and removed my own babel-polyfill dependency and can confirm it's working :+1: 

Thanks guys

**Comment by bopeng87** [comment]
the problem comes back on 1.0.6 and 1.0.9 :(

**Comment by bopeng87** [comment]
I have to go back to 1.0.3
