### ISSUE TITLE
can I choose folder for generated svg and font files?

### ISSUE THREAD

**Issue by zchrissirhcz** [shakacode/bootstrap-loader#134]
Hi, I'm new to webpack and bootstrap-loader. I have configured my npm packages and webpack config file, which everythings in my webpage runs OK. But one small thing I wonder if I can configure, whether if I can put the generated svg and font files into a temperory folder, instead of dont't know how to controll that, and my project folder structure is like this now:
![image](https://cloud.githubusercontent.com/assets/3831847/17928149/e9a35004-6a2b-11e6-9f97-a59d40ca5138.png)

The files in the red bounding box above， can I change their' position? And my webpack config file is:
```
module.exports = {
	entry: "./src/entry.js",
	output: {
		path: __dirname,
		publicPath:'dist/',
		filename: "dist/bundle.js"
	},
	module: {
		loaders: [

			{ test: /\.css$/, loader: 'style-loader!css-loader' },
			{ test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file" },
			{ test: /\.(woff|woff2)$/, loader:"url?prefix=font/&limit=5000" },
			{ test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/octet-stream" },
			{ test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=image/svg+xml" }
		]
	}
};
```

**Comment by justin808** [comment]
This is more of a webpack question. 

Nevertheless, take a look at the options for the 

https://github.com/webpack/file-loader

```
[path] the path of the resource relative to the context query parameter or option.
```

**Comment by justin808** [comment]
@zchrissirhcz: try changing the output.path in your exports to include the `dist` and remove the dist from the publicPath and filename.

**Comment by zchrissirhcz** [comment]
Thanks, it's really a webpack configuration issue. By doing as what you suggest, it works now.
