### ISSUE TITLE
Basic example with bootstrap 4 error

### ISSUE THREAD

**Issue by Ks89** [shakacode/bootstrap-loader#141]
I followed the instruction in the example/basic folder but I received an error:

webpack built b5804fae135cd571c63f in 1327ms
Time: 1327ms
                                 Asset     Size  Chunks       Chunk Names
  25a32416abee198dd821b0b17a198a8f.eot  76.5 kB
  d7c639084f684d66a1bc66855d193ed8.svg   392 kB
  1dc35d25e61d819a9c357074014867ab.ttf   153 kB
e6cf7c6ec7c2d6f670ae9d762604cb0b.woff2  71.9 kB
 c8ddf1e5e5bf3682bc7bebf30f394148.woff  90.4 kB
                                app.js  1.25 MB       0       main

ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: Error:
Could not find bootstrap version: '4'. Did you install it?
The package is 'bootstrap' for bootstrap v4 and 'bootstrap-sass' for v3.

    at Object.module.exports.pitch (/Users/Ks89/git/bootstrap-loader/examples/basic/node_modules/bootstrap-loader/lib/bootstrap.loader.js:114:11)
 @ ./~/bootstrap-loader/loader.js 1:0-44
 @ multi main
webpack: bundle is now VALID.

I'm using exactly your code without any modifications.

**Comment by 7sharp9** [comment]
Same for me too.

**Comment by wilburrr90** [comment]
I found a two step workaround to this:

1) Make this one-line change in npm_modules/bootstrap/package.json https://github.com/twbs/bootstrap/commit/75715d9d3cc8d033cc1e1fe5de805e81cfa06b1f

2) Modify .bootstraprc as described here: https://github.com/shakacode/bootstrap-loader/issues/117

Although it's not good practice to modify a module's package.json, this get's things working--for me at least.

**Comment by AlexKVal** [comment]
Examples don't work with the `bootstrap@4.0.0-alpha.3`, only with `bootstrap@4.0.0-alpha.2` version
https://github.com/shakacode/bootstrap-loader/pull/147/commits/1c29eb6725355185e9488b43625c335705ebf18b

**Comment by justin808** [comment]
Can any of you please confirm https://github.com/shakacode/bootstrap-loader/pull/170 works per the `/examples`.
