### ISSUE TITLE
Upgrading to 1.1.1 makes bootstrap-loader not finding the bootstrap 4 package

### ISSUE THREAD

**Issue by Magellol** [shakacode/bootstrap-loader#145]
After upgrading I had this following error

```
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js
Module build failed: Error:
Could not find bootstrap version: '3'. Did you install it?
The package is 'bootstrap' for bootstrap v4 and 'bootstrap-sass' for v3.

    at Object.module.exports.pitch (/Volumes/Whiskeytango/htdocs/pro/crew/labs-publication/node_modules/bootstrap-loader/lib/bootstrap.loader.js:134:11)
 @ ./~/bootstrap-loader/extractStyles.js 1:0-58
```
Downgrading back to `1.1.0` fixes the issue.

**Comment by AlexKVal** [comment]
Related https://github.com/shakacode/bootstrap-loader/issues/141#issuecomment-243191923

--
`bootstrap-loader` doesn't work with `bootstrap@4.0.0-alpha.3`, only with `bootstrap@4.0.0-alpha.2`

**Comment by Magellol** [comment]
I'm using `bootstrap@4.0.0-alpha.2`.
Here's a sample of my `package.json`.

```
    "bootstrap": "4.0.0-alpha.2",
    "bootstrap-loader": "1.1.0",
```

**Comment by justin808** [comment]
@Magellol Please verify fixed in 1.1.2.

**Comment by Magellol** [comment]
Will do :)

**Comment by justin808** [comment]
@Magellol Can you please confirm https://github.com/shakacode/bootstrap-loader/pull/170 solves your issue? Please check the examples.
