### ISSUE TITLE
How to use sass glob loader along with bootstrap-loader

### ISSUE THREAD

**Issue by aseem2625** [shakacode/bootstrap-loader#15]
**First of all my project is webpack-bootstrap-reactBootstrap. Also, I am having lot of custom scss files.**
Before bootstrap-loader in my project, **my own scss works(inside src folder)** fine as loader used are style, css, postcss and sass. With this, I am having all the bootstrap scss and js files in my src folder, so they also works fine with my own scss.

*(Now, I removed these bootstrap scss and js files)*
And after installing bootstrap-loader and dependencies as in Doc, the bootstrap-sass(from node modules) works but not my own scss files.
>So, Doc says, to use  `appStyles: ./path/to/your/app/styles/endpoint.scss` **which works fine if I put all my scss imports individually inside endpoints.scss which is not possible if I've 50 files**.

Basically, I needed something, that could work as 
` @import styles/**/*` inside endpoints.scss but it doesn't work.

So I want to use sass glob loader as on https://github.com/Aintaer/import-glob-loader.
which doesn't work with bootstrap-loader if I used the following:
` @import styles/**/*` inside endpoints.scss instead of individual imports but it doesn't work.
>It says, it doesn't identify the file *

So, in in my .bootstraprc itself, I tried using, 

`  "appStyles": "./src/styles/**/*",`
 ` "styleLoaders": ["style", "css", "sass", "import-glob"],`

And VOILA!! It works... because of import-glob. This way isn't given in bootstrap-loader Doc!

**But still I wanted to make it work in endpoints.scss because it is supposed to work**
Need help.. :innocent: 

(**Btw, for import-glob to make work, using "require(..)" or "preLoader" is not necessary as given in Doc in the link I gave.**)

**Comment by justin808** [comment]
@aseem2625 I don't like glob loading as you can't control the order. It's best to have manifest files.

Have a top level manifest file of imports and reference that one file from the .bootstraprc file, like this:

https://github.com/shakacode/bootstrap-loader/blob/master/.bootstraprc-3-default#L44

```
appStyles: ./path/to/your/app/styles/endpoint.scss
```

**Comment by aseem2625** [comment]
>Have a top level manifest file of imports...

@justin808 That is why I asked the question!!
Plz read my last 2 blocks of bold lines.

I wanted a top level manifest file like endpoints.scss but I wanted a functionality where a developer like me, if doesn't need control on order, can directly use recursive import all the scss files in a folder, something like `@import "styles/**/*"` but inside endpoints.scss and not inside .bootstraprc which although worked.

I refer to the same endpoints.scss which is in link 
https://github.com/shakacode/bootstrap-loader/blob/master/.bootstraprc-3-default#L44

**Comment by justin808** [comment]
@aseem2625 Did you get this worked out? If you wanted to add a PR to support globs, we'd consider it. However, I don't consider a "best practice" to use globs with scss.

**Comment by aseem2625** [comment]
Hi @justin808 
Right now, I am using it the way I explained in my last to last comment.
Since I've so many scss files in project and multiple programmers are working on it, it's not possible for everyone to add scss file in endpoints.scss manually each time they create a new scss file. So, since alphabetical wise loading scss is not my priority, I need to have some recursive inclusion like ```@import "styles/**/*"``` which can be written once in endpoints.scss and everything will be imported automatically whenever new scss file is created.

>However, I don't consider a "best practice" to use globs with scss.

Not sure why you feel so. But why it won't be a good practice when I have already given the path to folder where all my scss resides. Since I am using glob, meaning, just once line in endpoints.scss as ```@import "styles/**/*"``` it doesn't makes sense to create separate endpoints.scss files for this.

I would really like to hear your advice on this **as per my needs**
Thanks

**Comment by justin808** [comment]
@aseem2625 Please send us a PR that can make the changes you need. If you get stuck, let us know. If you're interested, check out http://www.shakacode.com, and I've got developers that that could help us get this done. Thanks for your support.

**Comment by justin808** [comment]
BTW, we're heavily using CSS modules now. So using globs is not a priority for the ShakaCode team.
