### ISSUE TITLE
appStyles, etc. missing for default config path

### ISSUE THREAD

**Issue by bmancini42** [shakacode/bootstrap-loader#151]
If you provide config in the default file path (i.e. `./.boostraprc`), values for 

- `appStyles`
- `preBootstrapCustomizations`
- `bootstrapCustomizations`

are ignored. This problem was introduced here: https://github.com/shakacode/bootstrap-loader/commit/9ef2e35c3d00cf8680415a0f4eecfe473bafebc6#diff-0b69986665a247a8a8e5e872e1df7022L98

It could be fixed by adding these lines:

```
      preBootstrapCustomizations: _defaultConfig.preBootstrapCustomizations,
      bootstrapCustomizations: _defaultConfig.bootstrapCustomizations,
      appStyles: _defaultConfig.appStyles,
```

starting at https://github.com/shakacode/bootstrap-loader/blob/v1/src/bootstrap.config.js#L92

**Comment by bmancini42** [comment]
I'd be happy to create a PR, given privileges to this repo.

**Comment by justin808** [comment]
@bmancini42 Please create a fork to create a PR. If you can show this error in the /examples directories, even better!

BIG Thanks!

**Comment by justin808** [comment]
@bmancini42 Please submit a PR today. Otherwise, @AlexKVal or I will fix later today.

**Comment by AlexKVal** [comment]
#153

**Comment by bmancini42** [comment]
That was fast! Thanks guys.

**Comment by justin808** [comment]
Please try out 1.1.3!

**Comment by bmancini42** [comment]
Yep, works for me
