### ISSUE TITLE
Problems with customized variables.scss in 1.1.2

### ISSUE THREAD

**Issue by ifranke** [shakacode/bootstrap-loader#156]
I used the loader in release 1.1.0 with a customized variables.scss addressed in .bootstraprc with preBootstrapCustomizations. 

In Version 1.1.2 my $font-family-sans-serif definitions and other bootstrap configurations like body bg color are not used and fall back to bootstrap base definitions. 

I am still working with bs4 alpha.2

I did not figure out, why this is not working any longer, solved it temporarily by using fixed 1.1.0 

Is there any change in using variables.scss to customize the bs variables since 1.1.2?

**Comment by justin808** [comment]
Please confirm this is fixed in 1.1.4.

**Comment by justin808** [comment]
@ifranke Any update? Please try the latest.

**Comment by justin808** [comment]
Please re-open if you still see this issue.
