### ISSUE TITLE
Bootstrap styles, loads after user scripts

### ISSUE THREAD

**Issue by MikeJSX** [shakacode/bootstrap-loader#161]
What i did wrong? 
My Webpack entry points:
```
`const APP_ENTRY_PATHS = [
    'bootstrap-loader',
    paths.client('main.js'),
]

webpackConfig.entry = {
    app: __DEV__
        ? APP_ENTRY_PATHS.concat(`webpack-hot-middleware/client?path=${config.compiler_public_path}__webpack_hmr`)
        : APP_ENTRY_PATHS,
    vendor: config.compiler_vendor
}`
```

**Comment by justin808** [comment]
@MikeJSX Please see the examples for inspiration

* https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic/README.md
* https://github.com/shakacode/bootstrap-loader/blob/master/examples/css-modules/README.md

**Comment by jsdevel** [comment]
Is there an answer for this?  I'm having a hard time getting bootstrap styles to load after user styles.

**Comment by justin808** [comment]
@jsdevel You are supposed to load the bootstrap styles first so that you can override them in your styles. Let me know if you need further help. http://www.shakacode.com/work.
