### ISSUE TITLE
How can I use this to add bootstrap 4 to the official angular-seed project?

### ISSUE THREAD

**Issue by robhobbes** [shakacode/bootstrap-loader#168]
I'm new to angular 2 and webpack. I git cloned the angular 2 seed project and I installed this project and bootstrap 4 via npm, and then in the vendor file I did `import 'bootstrap-loader'` but the styles on the page don't change. Should I be using the loader in the webpack config? Any help would be appreciated.

**Comment by justin808** [comment]
Yes. Try the Webpack configuration.

**Comment by robhobbes** [comment]
It would be nice if there was a sample project. I'm not sure how I need to change my webpack config. I tried just adding bootstrap loader to the list of loaders for css but it caused all sorts of console errors.

**Comment by justin808** [comment]
@robhobbes We'd love a PR for the /examples directory.

**Comment by Judahmeek** [comment]
@robhobbes Do you have your code in a public repository? I'd be happy to work with you on this issue.

**Comment by robhobbes** [comment]
@Judahmeek, I don't yet, but I ended up just using a sass loader and pointing webpack at the main bootstrap sass file. That did the trick for me.
