### ISSUE TITLE
Instructions for file loader when loading file in css with appStyles?

### ISSUE THREAD

**Issue by reywright** [shakacode/bootstrap-loader#173]
So inside .bootstraprc, you allow people to load in whatever css they want for their app. As you know, a lot of css uses images or assets... can you help me (and / or) add something to the webpack configurations that address using files in the css? I was able to figure it out with my dev config but I wasn't able to figure it out with the extract text plugin.

**Comment by reywright** [comment]
this is basically what needs to be in the webpack files for it to load.

{
        test: /\.(jpe?g$|gif|png)$/,
        loader: 'file-loader'
        // or 
        // loader: 'file-loader?name=[name].[ext]'
}

**Comment by reywright** [comment]
The bigger issue though is that with this setup, the images are extracted. How do we get around this?

**Comment by Judahmeek** [comment]
I'm not sure how this is a bootstrap-loader issue, but I'd be happy to discuss it with you in order to gain more experience with Webpack myself. I think that you would have better luck finding a solution to your issue through in Webpack's Gitter rooms: https://gitter.im/webpack/webpack

**Comment by Judahmeek** [comment]
@reywright Did you find a solution to your issue? Can we close this issue?
