### ISSUE TITLE
Bootstrap4 alpha.4 fixed navigation is scrolled over when background color is omited from <nav>

### ISSUE THREAD

**Issue by KerryRuddock** [shakacode/bootstrap-loader#178]
[]http://codepen.io/KerryRuddock/pen/pEvYXb

Created a codepen to demonstrate the issue of fixed navigation is scrolled under when class of "bg-*" is missing from mark up.  I'm not sure if this is an issue or not.  Maybe add documentation only?

ie. <nav id="navbar1" class="navbar navbar-default navbar-fixed-top">

adding "bg-inverse" or "bg-faded" fixes the problem.

**Comment by justin808** [comment]
@KerryRuddock is this a bootstrap issue? or a bootstrap-loader issue? Maybe try this without the bootstrap loader? Seems to be unrelated to the loader. Please confirm.

![2016-09-22_12-47-13](https://cloud.githubusercontent.com/assets/1118459/18768696/bc5a5c70-80c2-11e6-92d0-24721d452748.png)

**Comment by KerryRuddock** [comment]
Apologies Justin,

This is not a bootstrap loader issue. I deposited this to the wrong repository.
