### ISSUE TITLE
Neither basic nor css-modules examples have a working build version

### ISSUE THREAD

**Issue by okendoken** [shakacode/bootstrap-loader#18]
Hi! Thanks for great lib!

When trying to execute `npm run build` to compile a production version you get a public folder with js and css files, but html file is missing, so it's impossible to host a production version anywhere (e.g. put files to static web host).

The solution for this would probably be to include [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin).

Moreover, it would be cool to extract examples into a separate seed project, something like (webpack-bootstrap-seed)

**Comment by alexfedoseev** [comment]
Hi @okendoken, thanks for feedback!

TBH I don't remember the case when I was generating `html` with webpack for production, b/c most of the time it's generated by backend & web server (Ruby-on-Rails, Node's Express etc), and we need to prepare only js/css/images/fonts/.../ files as pluggable assets. In the example I used Express web server to serve html to the browser.

Previously examples was in separate repos, but it was hard to maintain and they were not such noticible as they are now, so we moved them to sub-folders. Actually it's quite general practice in npm libs world. Also they're not meant to be starter kits or smth, it's just an examples of implementation of this lib.

**Comment by okendoken** [comment]
OK, so in my case I expected html files to be inside of public folder because I am going to use your example as a starter kit for a single page application based on webpack, bootstrap 4 and angular 2.0. In this case server is going to serve static html files, which will load angular and do all other requests.

So I still think that it would make sense to put html files inside a public folder.

**Comment by alexfedoseev** [comment]
@okendoken Sure, PRs are welcome!

We can add comment to html part of webpack config, smth like "In case you prepare static html's for production...".
