### ISSUE TITLE
Loss of significant digits or rounding error (line-height, etc.)

### ISSUE THREAD

**Issue by AnonymousCoward476** [shakacode/bootstrap-loader#181]
Hi,

I just tried using bootstrap-loader for the first time and I ran into a strange problem. The default `line-height` value (and others? untested) in Bootstrap 3 is being imported with reduced accuracy due to a difference in the number of significant digits in the value. When using Bootstrap's CSS without bootstrap-loader, the default value for `line-height` on the `body` tag is `1.42857143`, but comes in as `1.42857` when using bootstrap-loader. Similarly, the default value for `line-height` on `.btn-lg` is `1.3333333` but comes in as `1.33333` when using boostrap-loader. As minor as this sounds, it does affect the output and I am unable to provide an exact replica of existing non-bootstrap-loader output without overriding those values (setting them back to the full, original BS3 values).

This is reproducible in the basic example provided in the v1 branch.

(I searched and couldn't find anything related, apologies in advance if this is a known issue.)

Thanks.

**Comment by Judahmeek** [comment]
@AnonymousCoward476 Bootstrap-Loader doesn't mutate any of Bootstrap's SCSS or CSS code. It only creates the necessary import and require statements for them.

@justin808 Any idea which loader (or webpack itself) would be responsible for this?

**Comment by AnonymousCoward476** [comment]
@Judahmeek Yeah, I wouldn't have thought that it would. The result was quite surprising. As you said, it must be one of the other loaders or webpack itself. I just tried it on the master branch and it still exists in 2.x, FWIW.

**Comment by Judahmeek** [comment]
Yeah, Bootstrap-Loader v1 & v2 do pretty much the exact same thing. I honestly think your time might be better spent modifying your layout so such exact precision isn't such a large issue.

**Comment by justin808** [comment]
@AnonymousCoward476 I don't think this issue is related to bootstrap-loader. I think it's related to the sass-loader.

**Comment by AnonymousCoward476** [comment]
@justin808 Thanks for looking.

**Comment by AnonymousCoward476** [comment]
In case anyone stumbles upon this in the future, I solved it by adding `precision=8` option to the `sass` loader in `.bootstraprc`:

```yaml
styleLoaders:
  - style
  - css
  - sass?precision=8
```
