### ISSUE TITLE
 bootstrap style file not include in index.html

### ISSUE THREAD

**Issue by nasreddineskandrani** [shakacode/bootstrap-loader#186]
i am upgrading my app from angular2 Rc4 to release version. I have a repo with the rc4 version, when i deploy i find out that bootstrap was include first in the index.html.

with the new project for upgrade its not included at all. Can't figure out why :S. I did all the steps in the documentation

notice that the boostraploader.js is include at the end of index.html ( in the script part )

do i need to import manually bootstrap.css file? but why in my old project i didn't have to do that?

**Comment by justin808** [comment]
@nasreddineskandrani Please study the examples in the /examples directory. I think you just need to do some debugging.
