### ISSUE TITLE
Add your customizations to sass resourcers file

### ISSUE THREAD

**Issue by mkontula** [shakacode/bootstrap-loader#190]
When customizing Bootstrap's variables ($brand-primary etc..) to roll out a special look and feel, one might want to use these customized variables in component's styles. This might be totally trivial to more experienced designers, but **it might be worth to mention in the readme.md**. Add your pre-customizations to sass resources file and your pink $brand-primary is pink everywhere you need it.

@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_mixins";
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables";
@import "app/styles/bootstrap-pre-customizations.scss";

Thanks for the great lib!

**Comment by justin808** [comment]
@mkontula Please make a PR to the readme if you feel this is missing.

**Comment by blowsie** [comment]
@mkontula  does modifying $brand-primary in your customisations file work?

**Comment by justin808** [comment]
@mkontula @blowsie The reason we have pre-customizations is that bootstrap's mixins create derived Sass variables. If you want to override these, you have to do it in the "customizations", not the "pre-customizations".
