### ISSUE TITLE
"Error: Path must be a string. Received undefined" updating to webpack 2.1.0-beta.25

### ISSUE THREAD

**Issue by borysn** [shakacode/bootstrap-loader#191]
Thought my issue was related to another thread, but it seems they are separate, so I'm opening up this ticket. Still actively trying to figure out what exactly is happening here. There were some breaking changes between webpack 2.1.0-beta.23-25, and upgrading is producing an error from bootstrap-loader...

```
69% building modules 1174/1175 modules 1 active ...ode_modules/bootstrap-loader/no-op.jsTypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.relative (path.js:495:3)
    at Object.onRender (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/index.js:282:42)
    at Object.<anonymous> (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/node_modules/async/dist/async.js:2414:31)
    at apply (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/node_modules/async/dist/async.js:40:25)
    at Object.<anonymous> (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/node_modules/async/dist/async.js:76:12)
    at Object.callback (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/sass-loader/node_modules/async/dist/async.js:988:16)
    at options.success (/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/node-sass/lib/index.js:309:32)

```

I am not completely sure that the issue is bootstrap-loader, I feel as though it may just be a configuration problem, or even possibly an issue with sass-loader (given the error trace)

I pulled the [basic example](https://github.com/shakacode/bootstrap-loader/tree/master/examples/basic) and tried to reproduce the issue, but could not, even updating the webpack version to 2.1.0-beta.25 did not break the build. Scratching my head here on this one a bit.

I'm still debugging, and searching around for a solution. I will definitely submit a PR if I find the fix is related to bootstrap-loader.

For reference...
**webpack.common.js**

``` javascript
const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const helpers = require('./helpers');
const autoprefixer = require('autoprefixer');

module.exports = {
    entry: {
        'polyfills': './src/polyfills.ts',
        'vendor': './src/vendor.ts',
        'app': './src/main.ts'
    },

    context: helpers.root(),

    resolve: {
        modules: [helpers.root('src'), "node_modules"],
        descriptionFiles: ['package.json'],
        extensions: ['.js', '.ts', '.css', '.scss', '.json', '.html']
    },

    module: {
      rules: [
          {
            enforce: 'pre',
            test: /\.js$/,
            loader: 'source-map-loader',
            exclude: [helpers.root('node_modules')]
          },

          {
            test: /\.ts$/,
            loaders: ['awesome-typescript-loader', 'angular2-template-loader'],
            exclude: [/\.(spec|e2e)\.ts$/]
          },

          {
            test: /\.html$/,
            loader: 'raw-loader',
            exclude: [helpers.root('src/index.html')]
          },

          {
            test: /\.css$/,
            loader: 'raw-loader!style-loader!css-loader!postcss-loader'
          },

          {
            test: /initial\.scss$/,
            loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader!sass-loader'})
          },

          {
            test: /\.scss$/,
            loaders: ['raw-loader', 'sass-loader'],
            exclude: [helpers.root('node_modules')]
          },

          {
            test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: "url-loader?limit=10000&mimetype=application/font-woff"
          },

          {
              test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
              loader: "file-loader"
          },

          {
            test: /\.json$/,
            loader: 'json-loader'
          },

          {
            test: /bootstrap\/dist\/js\/umd\//,
            loader: 'imports?jQuery=jquery'
          }
      ]
    },

    plugins: [
        new webpack.ContextReplacementPlugin(
            /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
            __dirname
        ),
        new ExtractTextPlugin({
            filename: 'css/[name].css',
            disable: false, allChunks: true
        }),

        new webpack.optimize.CommonsChunkPlugin({
            name: ['app', 'vendor', 'polyfills']
        }),

        new CopyWebpackPlugin([{
          from: 'src/assets',
          to: 'assets'
        }]),

        new HtmlWebpackPlugin({
            template: 'src/index.html',
            chunksSortMode: 'dependency'
        }),

        new webpack.ProvidePlugin({
            jQuery: 'jquery',
            $: 'jquery',
            jquery: 'jquery',
            "window.moment": "moment",
            'Tether': 'tether',
            'window.Tether': 'tether',
            Tooltip: "exports?Tooltip!bootstrap/js/dist/tooltip",
            Alert: "exports?Alert!bootstrap/js/dist/alert",
            Button: "exports?Button!bootstrap/js/dist/button",
            Carousel: "exports?Carousel!bootstrap/js/dist/carousel",
            Collapse: "exports?Collapse!bootstrap/js/dist/collapse",
            Dropdown: "exports?Dropdown!bootstrap/js/dist/dropdown",
            Modal: "exports?Modal!bootstrap/js/dist/modal",
            Popover: "exports?Popover!bootstrap/js/dist/popover",
            Scrollspy: "exports?Scrollspy!bootstrap/js/dist/scrollspy",
            Tab: "exports?Tab!bootstrap/js/dist/tab",
            Util: "exports?Util!bootstrap/js/dist/util"
        }),

        new webpack.LoaderOptionsPlugin({
          options: {
            postcss: [autoprefixer]
          }
        })
    ],

    node: {
        fs: 'empty',
        global: true,
        crypto: 'empty',
        module: false,
        clearImmediate: false,
        setImmediate: false
    }
};
```

**Comment by borysn** [comment]
It looks like the file paths are being passed around fine. I've been setting up some console.log outputs in sass-loader/index.js:269-301 

It appears there may be an issue with source map. If you notice below, we get the line `sourceMap: 'undefined/sass.map'`, this is comming from the sassOptions parameter which is passed with the onRender function. 

Not sure exactly what that means for bootstrap-loader

```
{ sourceMap: 'undefined/sass.map',
  data: '@import "../bootstrap/scss/_mixins";\n@import "../bootstrap/scss/_variables";\n@import "../bootstrap/scss/_normalize";\n@import "../bootstrap/scss/_print";\n@import "../bootstrap/scss/_reboot";\n@import "../bootstrap/scss/_type";\n@import "../bootstrap/scss/_images";\n@import "../bootstrap/scss/_code";\n@import "../bootstrap/scss/_grid";\n@import "../bootstrap/scss/_tables";\n@import "../bootstrap/scss/_forms";\n@import "../bootstrap/scss/_buttons";\n@import "../bootstrap/scss/_animation";\n@import "../bootstrap/scss/_dropdown";\n@import "../bootstrap/scss/_button-group";\n@import "../bootstrap/scss/_input-group";\n@import "../bootstrap/scss/_custom-forms";\n@import "../bootstrap/scss/_nav";\n@import "../bootstrap/scss/_navbar";\n@import "../bootstrap/scss/_card";\n@import "../bootstrap/scss/_breadcrumb";\n@import "../bootstrap/scss/_pagination";\n@import "../bootstrap/scss/_jumbotron";\n@import "../bootstrap/scss/_alert";\n@import "../bootstrap/scss/_progress";\n@import "../bootstrap/scss/_media";\n@import "../bootstrap/scss/_list-group";\n@import "../bootstrap/scss/_responsive-embed";\n@import "../bootstrap/scss/_close";\n@import "../bootstrap/scss/_tags";\n@import "../bootstrap/scss/_modal";\n@import "../bootstrap/scss/_tooltip";\n@import "../bootstrap/scss/_popover";\n@import "../bootstrap/scss/_carousel";\n@import "../bootstrap/scss/_utilities";\n\n',
  omitSourceMapUrl: true,
  sourceMapContents: true,
  indentedSyntax: false,
  importer: [ [Function: asyncWebpackImporter] ],
  includePaths: [ '/home/p3pt/dev/java/projects/spring-boot-angular2/frontend/node_modules/bootstrap-loader' ] }
```

**Comment by Judahmeek** [comment]
This probably has nothing to do with bootstrap-loader, other than we were the first loader in this chain. (I honestly am not sure why we listed in the stack trace, because path is throwing the error, and the path function throwing the error is the path.relative below)

Based off the stack trace, the fact that `...sass-loader/index.js:282:42` is `path.relative(self.options.context, resourcePath);`, and jtangelder/sass-loader#290, I think that your problem is that the loadOptions plugin is wiping `this.options.context`.

The `sassOptions` you provided proves this because that sourceMap url is based off of `self.options.context` [0] and `var self = this` [1].

0: https://github.com/jtangelder/sass-loader/blob/master/index.js#L228
1: https://github.com/jtangelder/sass-loader/blob/master/index.js#L40

**Comment by Ks89** [comment]
I had the same issue. I fixed it adding this to my webpack.common.js:

plugins: [
(...)
new LoaderOptionsPlugin({
      debug: true,
      options: {
        context: __dirname,
        output: { path :  "./" },
        postcss: [autoprefixer],
        tslint: {
          emitErrors: false,
          failOnHint: false,
          resourcePath: 'src',
          formattersDirectory: "node_modules/tslint-loader/formatters/"
        }
      }
    })
(...)
]

I don't understand what it means "output" inside LoaderOptionsPlugin, but it works.
Obviously, in my webpack.dev.js I have always these lines (the real output):

output: {
    path    : './',
    filename: '[name].js',
    chunkFilename: '[name].js',
    publicPath: './'
  },

**Comment by itPiligrim** [comment]
Same problem. Set "output" not work for me.

**Comment by itPiligrim** [comment]
Answer this: [https://github.com/jtangelder/sass-loader/issues/285](https://github.com/jtangelder/sass-loader/issues/285)

`
plugins: [
    new LoaderOptionsPlugin({
...
       output: config.output,
....

    })
]

`

i.e. for me "output" must be set to root "LoaderOptionsPlugin".

**Comment by justin808** [comment]
@itPiligrim @Ks89 do we need a code PR or doc PR?

**Comment by nappynapster** [comment]
I have the same problem, I already tired nodejs 5.11.1 and the latest version 6.9.1 -> same problem. I also tried the several webpack configs.
`"webpack": "2.1.0-beta.25"`
`"bootstrap": "4.0.0-alpha.4"`
`"bootstrap-loader": "^2.0.0-beta.12"`

**Comment by Ks89** [comment]
I'm using bootstrap-loader": "^2.0.0-beta.11" and webpack 2.1 Beta 25.
Also, I'm using bootstrap 4 alpha 5. 

Really, I don't understand and I have no idea to try to help. 
If you want I can try to create a skeleton project to test this, but you should wait this weekend.  I'm very busy now :(

**Comment by nappynapster** [comment]
You can use this angular starter project as base here -> https://github.com/AngularClass/angular2-webpack-starter
Then I used this wiki tutorial here -> https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery) , but I doesn't include jquery and I used the newest version as I posted before.

**Comment by nappynapster** [comment]
Okay no problem. Thank you that you take a look at this :)

**Comment by borysn** [comment]
sorry I've been mia on this guys, I should be able to make some time to continue looking at this during the weekend. I recall trying the output fix, and not having that resolve the issue, but I still have to take another look at it.

**Comment by Ks89** [comment]
I created this small project as an example: https://github.com/Ks89/Angular2-webpack2-skeleton

Try it.

I'm using macOs Sierra and Nodejs 7.0.0

**Comment by regenrek** [comment]
Same Problem here. 

`[Function: root]
 10% building modules 4/4 modules 0 active http://localhost:3000/
webpack result is served from /
content is served from /Users/harambe/webwork/mjang2/src
404s will fallback to /index.html
 69% building modules 809/810 modules 1 active ...ode_modules/bootstrap-loader/no-op.jsTypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1226:5)
    at Object.onRender (/Users/harambe/webwork/mjang2/node_modules/sass-loader/index.js:282:42)
    at Object.<anonymous> (/Users/harambe/webwork/mjang2/node_modules/sass-loader/node_modules/async/dist/async.js:2414:31)
    at apply (/Users/harambe/webwork/mjang2/node_modules/sass-loader/node_modules/async/dist/async.js:40:25)
    at Object.<anonymous> (/Users/harambe/webwork/mjang2/node_modules/sass-loader/node_modules/async/dist/async.js:76:12)
    at Object.callback (/Users/harambe/webwork/mjang2/node_modules/sass-loader/node_modules/async/dist/async.js:988:16)
    at options.success (/Users/harambe/webwork/mjang2/node_modules/node-sass/lib/index.js:309:32)`

If i uncomment the following line in .bootstraprc file it loads up
but breaks after

`#appStyles: ./src/app/app.scss`

`ERROR in ./~/css-loader!./~/postcss-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: 
undefined
^
      File to import not found or unreadable: ../../src/app/app.scss
Parent style sheet: stdin
      in /Users/kevinkernegger/webwork/mjang2/node_modules/bootstrap-loader/no-op.js (line 12, column 1)
 @ ./~/style-loader!./~/css-loader!./~/postcss-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js 4:14-193 13:2-17:4 14:20-199
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js?configFilePath=/Users/kevinkernegger/webwork/mjang2/.bootstraprc!./~/bootstrap-loader/no-op.js
 @ multi bootstrap`

**Comment by adstep** [comment]
Encountering this issue on Win10 with:

"webpack": "2.1.0-beta.25"
"bootstrap": "^3.3.7"
"bootstrap-loader": "^1.3.0"

**Comment by Judahmeek** [comment]
@Ks89 When I updated the version of `bootstrap-loader` in your package.json and then ran `npm install`, npm installed `bootstrap-loader@2.0.0-exports.1`. When I installed the proper version and then ran `npm run start`, I had no errors.

@regenrek ```...ode_modules/bootstrap-loader/no-op.jsTypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)**
    at Object.relative (path.js:1226:5)
    at Object.onRender (/Users/harambe/webwork/mjang2/node_modules/sass-loader/index.js:282:42)```
suggests the issue is actually with sass-loader.

**Comment by Ks89** [comment]
@Judahmeek exactly. On Mac OS and Linux it's working very well. On Windows I found this issue #196 (but it's not a blocking issue)

**Comment by rloisel** [comment]
@Judahmeek It seems there is an issue with the npm package. I'm trying to install` "bootstrap-loader": "^2.0.0-beta.11"`, in my package.json and npm install the `bootstrap-loader@2.0.0-exports.1` version.

**Comment by Andrey-Pavlov** [comment]
Same issue with [https://github.com/AngularClass/angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter). Any workaround?

**Comment by Andrey-Pavlov** [comment]
Ok. I've fixed it for https://github.com/AngularClass/angular2-webpack-starter.

Frequently errors:

- resolve-url-loader, 'path' of undefined
- Path must be a string. Received undefined

You need to add next rows to LoaderOptionPlugin
**context: helpers.root(),
output: { path: helpers.root('dist') },**

  ```
  /**
       * Plugin LoaderOptionsPlugin (experimental)
       *
       * See: https://gist.github.com/sokra/27b24881210b56bbaff7
       */
      new LoaderOptionsPlugin({
        debug: true,
        options: {
           context: helpers.root(),
          output: {
              path: helpers.root('dist')
          },
          /**
           * Static analysis linter for TypeScript advanced options configuration
           * Description: An extensible linter for the TypeScript language.
           *
           * See: https://github.com/wbuchwalter/tslint-loader
           */
          tslint: {
            emitErrors: false,
            failOnHint: false,
            resourcePath: 'src'
          }
        }
      })
    ],
```

Spend 6 hours to resolve that 2 issues. :(

**Comment by Kamshak** [comment]
@Andrey-Pavlov Would you have a repo with the seed using bootstrap4 like this? I've been trying for a few hours now but very new to bootstrap and copy pasting your solution into webpack.common.js still causes the 

```
 69% building modules 770/771 modules 1 active ...ode_modules/bootstrap-loader/no-op.jsTypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1228:5)
    at Object.onRender (/home/valentin/angular2-webpack-starter/node_modules/sass-loader/index.js:282:42)
    at Object.<anonymous> (/home/valentin/angular2-webpack-starter/node_modules/async/dist/async.js:2414:31)
    at apply (/home/valentin/angular2-webpack-starter/node_modules/async/dist/async.js:40:25)
    at Object.<anonymous> (/home/valentin/angular2-webpack-starter/node_modules/async/dist/async.js:76:12)
    at Object.callback (/home/valentin/angular2-webpack-starter/node_modules/async/dist/async.js:988:16)
    at options.success (/home/valentin/angular2-webpack-starter/node_modules/node-sass/lib/index.js:300:32)
```
for me

**Comment by sasidhar** [comment]
@Kamshak I came across same issue with [Angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) and with the following I fixed it. I am using Bootstrap 3.

- Make sure we are using `bootstrap-loader@2.0.0-beta.15`. When I had `"bootstrap-loader": "^2.0.0-beta.15"` entry in my `package.json` it is still installing `2.0.0-exports.1`. So, I fixed it by remove `^` in the version as of now.
- As of now I added following two lines to my `.bootstraprc`. I will remove these once `sass-loader` issues are fixed.
   ```
   disableSassSourceMap: true
   disableResolveUrlLoader: true
   ```

I have a working repo with following enabled [here](https://github.com/sasidhar/angular2-webpack-starter)

- Angular2-webpack-starter
- font-awesome-loader
- bootstrap-loader (with bootstrap3)

Good Luck!

**Comment by Abhijith-Nagaraja** [comment]
@sasidhar : This is not an issue and you don't need disable SassSourceMap and ResolveUrl Loaders.... Since you are using the Angular2-webpack-starter, you need to add the following in webpack.dev.config, webpack.prod.config and other environment files. Remember, changing in webpack.common.config won't resolve the issue...

```
new LoaderOptionsPlugin({
        debug: true,
        options: {
          context: __dirname,  
          output: { path :  './' }, //This has to be './' and not your output folder.
          postcss: [autoprefixer],
          sassLoader: {
            includePaths: [path.resolve(__dirname, 'src', 'scss')]
          }
        }
      }),
```

**Comment by krasnyuk** [comment]
> @sasidhar : This is not an issue and you don't need disable SassSourceMap and ResolveUrl Loaders.... Since you are using the Angular2-webpack-starter, you need to add the following in webpack.dev.config, webpack.prod.config and other environment files. Remember, changing in webpack.common.config won't resolve the issue...
> 
> It's all about passing the right context to webpack.
Finally it's help. Thanks a lot!

**Comment by krasnyuk** [comment]
@Abhijith-Nagaraja
Thanks a lot!!!!! It's finally helped!

**Comment by Kamshak** [comment]
@sasidhar Thanks!

@Abhijith-Nagaraja finally, it works! Thanks a lot!

**Comment by justin808** [comment]
@Abhijith-Nagaraja @Judahmeek @Kamshak @krasnyuk @sasidhar,

Is there any chance that one of you can put together a doc PR to summarize this?

**Comment by Abhijith-Nagaraja** [comment]
@justin808 : I don't think doc PR is necessary here. Since it is not a bootstrap-loader issue. 
If the PR should be submitted, then it should be in webpack or saas-loader

**Comment by zjoin** [comment]
@Abhijith-Nagaraja
Thanks,  it works!

**Comment by kc3454** [comment]
@regenrek This problem was due to a regression in stylus-loader when upgrading to webpack 2. The fix has been merged in as follows: https://github.com/shama/stylus-loader/pull/104.
