### ISSUE TITLE
_bootstrap-variables.scss is not in the SourceMap.

### ISSUE THREAD

**Issue by JustDoItSascha** [shakacode/bootstrap-loader#192]
When I'm trying to run my webpack with angular2 in production config, I get this error:

```
Module build failed: Error: "../../src/assets/scss/_bootstrap-variables.scss" is not in the SourceMap.
```

when I have `devtool: 'source-map'` in my config. When I build the project without devtool, everything works fine. The `_bootstrap-variables.scss` is loaded via bootstrapCustomizations in `.bootstraprc`.

**Comment by justin808** [comment]
You'll have to do some debugging to sort this out.
