### ISSUE TITLE
Two configFiles in the same webpack build is not working

### ISSUE THREAD

**Issue by navarroaxel** [shakacode/bootstrap-loader#193]
### Issue description

When I have 2 entries in my `webpack.config.js`, with a `configFilePath` and a particular bootstrap-loader configuration file, both entries compiles with the first configuration.
### Where can I see the bug?

Repository to expose the bug: https://github.com/navarroaxel/webpack-bootstrap. The repository has 2 webpacks builds to show the differences.
### Versions:

`node` 6.9.1
`webpack` 1.13.2
`bootstrap-loader` 1.2.1

is it a bad config? or is it a bug?``

**Comment by justin808** [comment]
@navarroaxel This is a case that is not officially supported. It's likely that there's some global variables used. If you could send a PR, much appreciated.

**Comment by navarroaxel** [comment]
@justin808 Can you give me some guidelines?
Do you think this is hard for a ``first contribution``?
Is a huge refactor?

I'll try

**Comment by justin808** [comment]
My guess is that something is of global scope that shouldn't be.

**Comment by justin808** [comment]
Shipped in 1.3.0. The change to 2.x (master) is not completed. It can be found at #195. We'll keep this PR open until #195 is closed. @navarroaxel if you can help with that, much appreciated by the community! Great work on #194.
