### ISSUE TITLE
preBootstrapCustomizations not working for some variables

### ISSUE THREAD

**Issue by blowsie** [shakacode/bootstrap-loader#197]
Certain variables within my customisation file don't seem to work, for example:
`$brand-primary` fails, `$btn-primary-bg` works. Am I doing something wrong or is this a bug?

---

Version: 2.0.0-beta.11
OS: Windows 10

`.bootstraprc` extract
```
preBootstrapCustomizations: ./src/libs/bootstrap_variables.scss
bootstrapCustomizations: ./src/libs/bootstrap_variables.scss
```

`bootstrap_variables.scss`
```
// $btn-primary-bg: #f00f00; // <== Works
$brand-primary: #f00f00; // <== Fails

```

**Comment by justin808** [comment]
@blowsie Sounds like you're putting something like $brand-primary in the boostrapCustomizations. It's too late at that point. You need that in the preBootstrapCustomizations.

You also cannot use the same file for both. That makes no sense.

**Comment by blowsie** [comment]
@justin808 , I used the same file for both to prove a point that it does not work in `preBootstrapCustomizations` or `bootstrapCustomizations` . This is still an issue for me, can we please reopen?

**Comment by justin808** [comment]
1. Please put in debugging in those files: https://www.sitepoint.com/using-sass-error-warn-and-debug-directives/
2. Please use invalid file names to see if you get an obvious error message.
3. Please only use the appropriate one location for the file. $brand-primary absolutely must be defined in the pre file. Please see the sass files that are loaded with bootstrap from your bootstrap installation directory inside of your node_modules directory.

**Comment by blowsie** [comment]
Thanks I will do the above and report back in the next few days

**Comment by blowsie** [comment]
Split into two files.
```
# Customize Bootstrap variables that get imported before the original Bootstrap variables.
# Thus, derived Bootstrap variables can depend on values from here.
# See the Bootstrap _variables.scss file for examples of derived Bootstrap variables.
#
preBootstrapCustomizations: ./src/libs/bootstrap_variables_pre.scss


# This gets loaded after bootstrap/variables is loaded
# Thus, you may customize Bootstrap variables
# based on the values established in the Bootstrap _variables.scss file
#
bootstrapCustomizations: ./src/libs/bootstrap_variables_post.scss
```
---
bootstrap_variables_pre.scss
```
@debug 'pre-loaded';
$brand-primary: #f00f00;
```
bootstrap_variables_post.scss
```
@debug 'post-loaded';
```
---


### 1. 
Debug Info
```
/src/libs/bootstrap_variables_pre.scss:2 DEBUG: pre-loaded
/src/libs/bootstrap_variables_post.scss:2 DEBUG: post-loaded
```
### 2. 
Failed when i changed the file names

### 3.
libs.js
```
import 'bootstrap-loader';
import 'animate.css/animate.css';
```

---
```
// $btn-primary-bg: #f00f00; // <== Works
$brand-primary: #f00f00; // <== Fails
```

**Comment by Judahmeek** [comment]
By "Fails", do you mean that SASS can't see the `$brand-primary` variable or do you mean that it is overwritten? Are there any other variables that you have this issue with? Have you run a `findstr` search to identify any other files that might be overwriting those variables?

**Comment by blowsie** [comment]
Fails as in `$brand-primary: #f00f00;` should make my `btn-primary` buttons red, but they are still the default colors

**Comment by Judahmeek** [comment]
Can you reproduce your issue with our basic example?

I just successfully tested defining `$brand-primary: #f00f00;` [here](https://ide.c9.io/judahmeek/bootstrap-loader) (I uncommented and overwrote `.bootstraprc-4-default` pre-customization link).

**Comment by blowsie** [comment]
I am unable to run your sample, maybe because it is read only?

![bootstrap](https://cloud.githubusercontent.com/assets/308572/20827854/4a71bcde-b86c-11e6-8bd0-9679f139e9d2.gif)


Also your sample uses a webpack entry approach, and not require / import, perhaps this is the issue?

**Comment by Judahmeek** [comment]
Apologies for the Cloud 9 link. I didn't realize read-only didn't allow terminal access.

This should serve better: https://github.com/Judahmeek/bootstrap-loader/tree/brand-primary.

Using the require approach, I broke font-awesome somehow, but the `$brand-primary` preset still succeeds on Cloud 9.

**Comment by justin808** [comment]
@Judahmeek @blowsie is this still an issue?

**Comment by Judahmeek** [comment]
I was never able to reproduce @blowsie's issue.
