### ISSUE TITLE
Add extractStylesOptions param in the .bootstraprc

### ISSUE THREAD

**Issue by mikaelguillin** [shakacode/bootstrap-loader#200]
It would be great if we could set options of the extract plugin via an `extractStylesOptions` parameter in the .bootstraprc config file.

**Comment by justin808** [comment]
Please share an example of what you're thinking.

**Comment by mikaelguillin** [comment]
The idea is handling options like `options.publicPath` of the [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin) directly from the .bootstraprc.

This may be useful for overriding the public path of css backgrounds.

**Comment by xfides** [comment]
Please, help. I have the same problem. I need to set publicPath for extractStylesPlugin. And I don't understand how I can do it. I didn't find instructions via .bootstrarrc. What else do I have?  

I have extractTextPlugin in my webpack.config.js. But bootstrap-loader uses it's own loaders. May be I can do this trick another way?

**Comment by justin808** [comment]
@xfides @mikaelguillin any updates?

If any of you want personalized support, ShakaCode is here to help with our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).
