### ISSUE TITLE
Webpack v2.1.0-beta.26 - Breaking changes with loaders

### ISSUE THREAD

**Issue by silveryiris** [shakacode/bootstrap-loader#201]
The shorten express of loader names now conflicts with Webpack v2.1.0-beta.26 changes on many loaders.

I've dealt with this with a `bootstrap-loader` module hot fix.

`.bootstraprc`
```
styleLoaders:
  - style-loader
  - css-loader
  - sass-loader
```

And 2 files on `bootstrap-loader` module

`bootstrap-loader\lib\utils\buildExtractStylesLoader.js`
```javascript
//on line 7
exports.default = function (loaders) {
  var fallbackLoader = void 0;
  if (loaders[0].startsWith('style')) {
    fallbackLoader = 'style-loader';
  } else if (loaders[0].startsWith('isomorphic-style')) {
    fallbackLoader = 'isomorphic-style-loader';
  }
```

`bootstrap-loader\lib\utils\processStyleLoaders.js`
``` javascript
//on line 58
if (!resolveUrlLoader) {
  loaders.splice(sassLoaderIndex, 0, 'resolve-url-loader');
}

```

Just add the "-loader" word behind the loader name , and webpack should working now.

I know this is not gonna fix all the possibility config problems from this issues.

Hope there is a better solution then this hot fix.

**Comment by justin808** [comment]
Can you submit a PR? CC: @Judahmeek

**Comment by silveryiris** [comment]
@justin808 I would love to submit a PR , but there is a not solved issue with https://github.com/shakacode/bootstrap-loader/issues/201#issue-189030570

The `sass`  will encounter the same error if  not add the "-loader" word behind the loader name in `.bootstraprc`

The loader name of sass in `bootstrap-loader` is directly returned by
`sassLoaderRegExp.test(loader)`

So we have to enforced the `xxx-loader` format on `RegExp.test` result return.

or make a if..else logic section to add the extend "-loader" word ?

**Comment by kevinzwhuang** [comment]
I opened a PR, #201, which should handle the workaround that @silveryiris proposed as well as loaders coming from `.bootstraprc`, even in short form.

**Comment by justin808** [comment]
We're close to getting the PR from @kevinzwhuang merged!

**Comment by Judahmeek** [comment]
@silveryiris just add `resolveLoader: {moduleExtensions : ['-loader']},` to your webpack config.
