### ISSUE TITLE
Integration with react-create-app

### ISSUE THREAD

**Issue by timarney** [shakacode/bootstrap-loader#206]
@shakacode wondering if you would have any interest in working with me to see if we could roll an example Integration using https://github.com/timarney/react-app-rewired .

Looks to me like it would be very feasible... here's a simple example of using Sass with react-create-app (no eject, no fork) https://github.com/timarney/react-app-rewired/blob/master/examples/sass.md

**Comment by justin808** [comment]
@timarney **GREAT IDEA!** Please submit a PR and let's include this!

**Comment by timarney** [comment]
Okay - I'm going to close this and I'll file a PR when I have something.

**Comment by sattaman** [comment]
@timarney Can you post an update here when you do? i've just had to eject to get this working

**Comment by timarney** [comment]
@sattaman @justin808  I might have time to try this late next week.

Just so I fully understand given I haven't used this repo before...

Given a fresh CRA app with full access to the webpack config.

**What would be the steps to get it up and running?.**

```bash
npm install bootstrap-loader
npm install --save-dev bootstrap@v4.0.0-alpha.4
npm install --save-dev css-loader node-sass resolve-url-loader sass-loader style-loader url-loader
```

In **App.js** (until CRA uses Webpack 2)
```
require('bootstrap-loader');
```

Mod the **config** to allow usage of Sass see - https://github.com/timarney/react-app-rewired/blob/master/examples/sass.md
```
module.exports = function override(config, env) {
  config.module.loaders.push({
    test: /\.scss$/,
    loaders: ["style", "css", "sass"]
  });
}
```

Mod the **config** to add Tether ?

```
//this code to be added to the config
plugins: [
    new ExtractTextPlugin('app.css', { allChunks: true }),
    new webpack.ProvidePlugin({
      "window.Tether": "tether"
    }),
  ],
```


Then to show it working used some Bootstrap stuff i.e. 

```
<div class="container">
        <h2>Glyphicons (not available for Bootstrap 4!)</h2>
        <div class="row col-items">
          <div class="col-md-4 col-item">
            <span class="text">It.</span>
          </div>
          <div class="col-md-4 col-item">
            <span class="text">Just.</span>
          </div>
          <div class="col-md-4 col-item">
            <span class="text">Works.</span>
          </div>
        </div>
      </div>

```

**Comment by justin808** [comment]
That's possibly right. Be sure to check the README on the master or v1 branches, depending on if you are using webpack v2. I'm really excited to get out there!

I'm opening this ticket to let the community know that we're working on it and that we want to get this done within the next few weeks!
