### ISSUE TITLE
Bootstrap 4 not being loaded in html

### ISSUE THREAD

**Issue by alex88** [shakacode/bootstrap-loader#207]
I've installed `bootstrap-loader` along with `bootstrap` beta 4.

My project derives from https://github.com/preboot/angular2-webpack, I've included `bootstrap-loader` in the `vendor.ts` file, this is my bootstraprc

```
loglevel: debug
bootstrapVersion: 4
styleLoaders:
  - style-loader
  - css-loader
  - postcss-loader
  - sass-loader
extractStyles: true
```

and this is the log:

```
[bootstrap-loader]:  bootstrap-loader is in DEBUG mode because you have your config log level set to 'debug'.
[bootstrap-loader]:  Using config file /Users/alex/Sites/myapp-frontend/.bootstraprc
[bootstrap-loader]:  Query from webpack config: *none*
[bootstrap-loader]:  Using Bootstrap module: bootstrap
[bootstrap-loader]:  Bootstrap module location (abs): /Users/alex/Sites/myapp-frontend/node_modules/bootstrap
[bootstrap-loader]:  Bootstrap module location (rel): ../bootstrap
[bootstrap-loader]:  Context: /Users/alex/Sites/myapp-frontend/node_modules/bootstrap-loader
[bootstrap-loader]:  Using Bootstrap version: 4
[bootstrap-loader]:  Bootstrap NPM package version: 4.0.0-alpha.4
[bootstrap-loader]:  Normalized params:
 { bootstrapVersion: 4,
  loglevel: 'debug',
  preBootstrapCustomizations: undefined,
  bootstrapCustomizations: undefined,
  appStyles: undefined,
  disableSassSourceMap: undefined,
  disableResolveUrlLoader: undefined,
  useFlexbox: undefined,
  useCustomIconFontPath: undefined,
  extractStyles: true,
  styleLoaders: [ 'style-loader', 'css-loader', 'postcss-loader', 'sass-loader' ],
  styles: false,
  scripts: false,
  configFilePath: '/Users/alex/Sites/myapp-frontend/.bootstraprc',
  bootstrapPath: '/Users/alex/Sites/myapp-frontend/node_modules/bootstrap',
  bootstrapRelPath: '../bootstrap' }
[bootstrap-loader]:  Requiring:
```

however, no css is present in the html, any clue?

Update: I've tried also with the https://github.com/shakacode/bootstrap-loader/issues/201 branch

**Comment by justin808** [comment]
Why would you expect there to be CSS in the html?

Webpack CSS will either be inline with the JS, or it will be exported using the extract-text-plugin.

**Comment by alex88** [comment]
@justin808 sorry, I expect the css to be included in the page, either in js or css if extract styles is true, however no css is loaded

OT: can you have a look at https://github.com/shakacode/font-awesome-loader/pull/5 since you're a member of the same group?

**Comment by justin808** [comment]
@alex88 I just pushed 1.0.1 of the font-awesome-loader. Please let me know ASAP if it works OK as I did not test the change! Thanks!

**Comment by alex88** [comment]
@justin808 seems to solve the issue with webpack beta 26, I've an error but I think it's not because of the loader, but how I process sass files in `node_modules` folder, I'll confirm you as soon as I fix the issue with sass

**Comment by alex88** [comment]
@justin808 yeah the issue was with my config, the PR fixed the issue with webpack beta 26

**Comment by alex88** [comment]
@justin808 about the bootstrap issue, I've included `import 'bootrstrap-loader' into my js, shouldn't it include the css on the page?

**Comment by alex88** [comment]
Can this be reopened? I've still the same issue
