### ISSUE TITLE
createUserImport should pass an absolute path to webpack.addDependency

### ISSUE THREAD

**Issue by stephanwilliams** [shakacode/bootstrap-loader#211]
I'm using bootstrap-loader 1.3.0 and webpack 1.13.3.

In src/utils/createUserImport.js, `addDependency` is called with a path relative to the current module context, instead of an absolute file path like webpack expects.

This was causing `webpack --watch` to rebuild bootstrap-loader on every file change - after a bit of mucking around with webpack, it seems that to determine whether a rebuild is necessary webpack [checks file dependencies for updates against a map of absolute path -> timestamp](https://github.com/webpack/webpack/blob/v1.13.3/lib/NormalModule.js#L190), and if the file isn't in the map (e.g. if the path is relative instead of absolute) the module is always rebuilt.

The solution seems to be to pass `module` instead of `userModule` to `webpack.addDependency(...)`; looks like `createUserImport(...)` is only called on values that have already been pre-processed with `path.resolve(...)` in src/bootstrap.config.js, so `module` should always be an absolute path.

**Comment by justin808** [comment]
@stephanwilliams This sounds like a win.
