### ISSUE TITLE
Webpack 2 beta.27 - It's no longer allowed to omit the '-loader' prefix when using loaders.

### ISSUE THREAD

**Issue by alvipeo** [shakacode/bootstrap-loader#213]
Using bootstrap-loader in this repo https://github.com/qdouble/angular-webpack2-starter/tree/minimal, which uses Webpack 2 beta 27. And when I build I get this error:

>> ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module not found: Error: Can't resolve 'sass' in 'C:\Users\Alex\Documents\Visual Studio 2015\Projects\UziNg2\node_modules\bootstrap-loader'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
                 You need to specify 'sass-loader' instead of 'sass'.
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js 1:21-244
 @ ./~/bootstrap-loader/loader.js
 @ ./src/main.browser.ts
 @ dll app_assets

How can this be fixed?

**Comment by sasidhar** [comment]
@alvipeo Are you using `.bootstraprc`?
If yes, make sure we have `-loader` suffix for entires under `styleLoaders` as shown below
```
styleLoaders:
  - style-loader
  - css-loader
  - sass-loader
```

**Comment by justin808** [comment]
@alvipeo @sasidhar can we close this one?

**Comment by alvipeo** [comment]
@sasidhar No, I don't. Can I fix this somehow without .bootstraprc ?

**Comment by sasidhar** [comment]
Which version of `bootstrap-loader` are you using? Can you share your `package.json`'s `bootstrap-loader` entry? There was some issue with the `bootstrap-loader` versions as mentioned here : https://github.com/shakacode/bootstrap-loader/issues/214

**Comment by alvipeo** [comment]
I 'npm uninstall bootstrap-loader', then 'npm install bootstrap-loader@latest', which fixed the error. Thanks!

(though, I got another one, probably not related):
>>Error: Module 'C:\Users\Alex\Documents\Visual Studio 2015\Projects\UziNg2\node_modules\url\url.js' is not a loader (must have normal or pitch function)

if you have any idea on that, please share. Otherwise, close this. Thanks!!

**Comment by jeffswitzer** [comment]
I am having a similar issue. I get the error 

> BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
>                  You need to specify 'file-loader' instead of 'file'.

I'm using the latest right now:
`"bootstrap-loader": "^2.0.0-beta.19",`

I get this error without a .bootstraprc file, and I tried adding a .bootstraprc file with
```
styleLoaders:
- style-loader
- css-loader
- sass-loader
```
I also tried it with
```
styleLoaders:
- style-loader
- css-loader
- sass-loader
- file-loader
```
which maybe doesn't even make sense, but same error anyhow.

**Comment by jeffswitzer** [comment]
Nevermind on the above comment. My .bootstraprc file had a yaml extension and was being ignored. I ended up getting it to work by removing the extension and I'm now using json instead of yaml to specify my config which currently looks like:

```
{
  "bootstrapVersion": 3,
  "useFlexbox": true,

  "styleLoaders": ["style-loader", "css-loader", "sass-loader"],

  "styles": {
    "normalize": true,
    "print": true
  },

  "scripts": {
    "alert": true,
    "button": true
  },
  "appStyles": "./styles.css"
}
```

No more errors here.

**Comment by sjatkins** [comment]
I have the above and I still get this error.  And why oh why this this need to change in the first place?  *whimper*.    Are changes needed anywhere else?  In webpack perhaps?  Color me confused and not amused.
