### ISSUE TITLE
2.0.0-exports.1 is installed when requested for ^2.0.0-beta.15

### ISSUE THREAD

**Issue by sasidhar** [shakacode/bootstrap-loader#214]
I have following entry in my package.json
```
'bootstrap-loader': '^2.0.0-beta.15'
```
Expecting `2.0.0-beta.15`, as it is latest. But npm is installing old version : `2.0.0-exports.1`

May be it is a good idea to deprecate this version with a message to upgrade to latest one?

**Comment by justin808** [comment]
Thanks. I ran this command.

`npm deprecate bootstrap-loader@"2.0.0-exports.1" "See beta versions"`

**Comment by bbousba** [comment]
Hi,

I still have the same issue.
I have the following entry in my package.json

`"bootstrap-loader": "^2.0.0-beta.22",`

And every time I npm update my project, bootstrap-loader@"2.0.0-exports.1 is installed instead.
But if I uninstalled it (npm uninstall -D bootstrap-loader) and reinstall it right after (npm i -D bootstrap-loader) the correct version is installed.
