### ISSUE TITLE
Install with Angular-CLI

### ISSUE THREAD

**Issue by kjartanvalur** [shakacode/bootstrap-loader#217]
What is the recommended way of installing bootsrap-loader with angular-cli?

**Comment by kjartanvalur** [comment]
I´m using Angular CLI v1.0.0-beta.21

**Comment by Judahmeek** [comment]
@borysn @ks89 @andrey-pavlov Any words of advice for this gentleman?

**Comment by Ks89** [comment]
Sorry for the delay.
I really don't know. I never used angular-cli, but I'll try it soon or later.

**Comment by kjartanvalur** [comment]
Any news on this? I´m now using @angular/cli  - v1.3

**Comment by justin808** [comment]
@kjartanvalur if you can help with this, I'd really appreciate it.

**Comment by Ks89** [comment]
Oh damn I forgot this issue, I'm sorry :)

@kjartanvalur I created this example 
https://github.com/Ks89/angular-cli-bootstraploader very very quickly right now. I hope you like it :)
Remember to execute `ng eject` to create `webpack.config.js`.

I also installed some dependencies (I used the official readme of bootstrap-loader).
