### ISSUE TITLE
Breaking changes in webpack: 'style-loader' instead of 'style'

### ISSUE THREAD

**Issue by San4oPanso** [shakacode/bootstrap-loader#218]
Hi @shakacode,

There is breaking changes with webpack  2.1.0-beta.27 or earlier. At 2.1.0-beta.0 everything fine. Seems like it is small issue

``` 
    ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
    Module not found: Error: Can't resolve 'style' in 'D:\EPAM_Projects\WebEx\frontend\WebEx.Frontend\node_modules\bootstrap-loader'
    BREAKING CHANGE: It's no longer allowed to omit the '-loader' prefix when using loaders.
                     You need to specify 'style-loader' instead of 'style'.
     @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js 1:21-114
```
Same error by require('bootstrap-loader') and by using on entrypoint

webpack 2.1.0-beta.27
node v7.2.0
Thanks

**Comment by 4k** [comment]
https://github.com/shakacode/bootstrap-loader/blob/master/README.md#styleloaders

**Comment by folmert** [comment]
Had same issue. Fixed by installing latest beta:
`npm install --save-dev bootstrap-loader@2.0.0-beta.16`
instead latest stable:
`npm install --save-dev bootstrap-loader`

**Comment by justin808** [comment]
Thanks @folmert, @San4oPanso, @4k! Closing this one.

**Solution is to upgrade!**

**Comment by holyxiaoxin** [comment]
Remember to specify the exact version in `package.json`:
```
"bootstrap-loader": "2.0.0-beta.18"
```

A fresh install of node_modules will break if you just run `npm install --save-dev bootstrap-loader@2.0.0-beta.18`

**Comment by nextofsearch** [comment]
Hi,

I am getting the same error:
"bootstrap-loader": "^2.0.0-beta.22",
node v7.7.1

```
21:16:46 client.1 | ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
21:16:46 client.1 | Module not found: Error: Can't resolve 'style' in '/Users/danolee/git/commerce-dashboard/client/node_modules/bootstrap-loader'
21:16:46 client.1 | BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
21:16:46 client.1 |                  You need to specify 'style-loader' instead of 'style'.
21:16:46 client.1 |  @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js 1:21-113
21:16:46 client.1 |  @ ./~/bootstrap-loader/loader.js
21:16:46 client.1 |  @ multi es5-shim/es5-shim es5-shim/es5-sham babel-polyfill bootstrap-loader ./app/bundles/Dashboard/startup/root
```

**Comment by nextofsearch** [comment]
Never mind. it was solved after installing 'style' package.
