### ISSUE TITLE
A whole bunch of error after npm install

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [shakacode/bootstrap-loader#225]
Could somebody help with these? I am running this behind a proxy but it should be resolved already. Thanks.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master>npm install
npm WARN deprecated babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package

> bootstrap-loader@2.0.0-beta.17 prepublish C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master
> npm run prerelease

> bootstrap-loader@2.0.0-beta.17 prerelease C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master
> npm run lint && npm run clean && npm run build

> bootstrap-loader@2.0.0-beta.17 lint C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master
> eslint --ext .js .

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\extractStyles.js
  1:1  error  Unexpected '!' in './lib/bootstrap.loader?extractStyles!./no-op.js'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\loader.js
  1:18  error  Unexpected '!' in './lib/bootstrap.loader!./no-op.js'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\node_package\tests\bootstrap.config.test.js
  94:19  error  Missing trailing comma  comma-dangle

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\node_package\tests\utils\buildExtractStylesLoader.test.js
  18:80  error  Missing trailing comma  comma-dangle
  19:6   error  Missing trailing comma  comma-dangle
  25:91  error  Missing trailing comma  comma-dangle
  26:6   error  Missing trailing comma  comma-dangle

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\node_package\tests\utils\createBootstrapImport.test.js
  12:55  error  Missing trailing comma  comma-dangle

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\node_package\tests\utils\createBootstrapRequire.test.js
  12:56  error  Missing trailing comma  comma-dangle

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\node_package\tests\utils\processModules.test.js
  12:37  error  Missing trailing comma  comma-dangle

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\node_package\tests\utils\processStyleLoaders.test.js
  19:52  error  Missing trailing comma  comma-dangle
  26:61  error  Missing trailing comma  comma-dangle
  33:51  error  Missing trailing comma  comma-dangle
  40:39  error  Missing trailing comma  comma-dangle
  48:29  error  Missing trailing comma  comma-dangle
  55:67  error  Missing trailing comma  comma-dangle
  62:57  error  Missing trailing comma  comma-dangle
  69:45  error  Missing trailing comma  comma-dangle
  77:35  error  Missing trailing comma  comma-dangle
  84:52  error  Missing trailing comma  comma-dangle

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\src\bootstrap.loader.js
   32:1   error  Import in body of module; reorder to top  import/first
   33:1   error  Import in body of module; reorder to top  import/first
   35:1   error  Import in body of module; reorder to top  import/first
   36:1   error  Import in body of module; reorder to top  import/first
   37:1   error  Import in body of module; reorder to top  import/first
   38:1   error  Import in body of module; reorder to top  import/first
   39:1   error  Import in body of module; reorder to top  import/first
   40:1   error  Import in body of module; reorder to top  import/first
   41:1   error  Import in body of module; reorder to top  import/first
   42:1   error  Import in body of module; reorder to top  import/first
   43:1   error  Import in body of module; reorder to top  import/first
  181:67  error  Missing trailing comma                    comma-dangle
  182:12  error  Missing trailing comma                    comma-dangle
  183:10  error  Missing trailing comma                    comma-dangle
  198:68  error  Missing trailing comma                    comma-dangle
  199:12  error  Missing trailing comma                    comma-dangle
  200:10  error  Missing trailing comma                    comma-dangle

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\src\bootstrap.styles.loader.js
  39:74  error  Missing trailing comma  comma-dangle
  45:57  error  Missing trailing comma  comma-dangle
  50:75  error  Missing trailing comma  comma-dangle
  55:68  error  Missing trailing comma  comma-dangle
  61:54  error  Missing trailing comma  comma-dangle

✖ 42 problems (42 errors, 0 warnings)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! bootstrap-loader@2.0.0-beta.17 lint: `eslint --ext .js .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-loader@2.0.0-beta.17 lint script 'eslint --ext .js .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bootstrap-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --ext .js .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bootstrap-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bootstrap-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prerelease"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! bootstrap-loader@2.0.0-beta.17 prerelease: `npm run lint && npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-loader@2.0.0-beta.17 prerelease script 'npm run lint && npm run clean && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bootstrap-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run clean && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bootstrap-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bootstrap-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN bootstrap-loader@2.0.0-beta.17 requires a peer of css-loader@* but none was installed.
npm WARN bootstrap-loader@2.0.0-beta.17 requires a peer of node-sass@* but none was installed.
npm WARN bootstrap-loader@2.0.0-beta.17 requires a peer of resolve-url-loader@* but none was installed.
npm WARN bootstrap-loader@2.0.0-beta.17 requires a peer of sass-loader@* but none was installed.
npm WARN bootstrap-loader@2.0.0-beta.17 requires a peer of url-loader@* but none was installed.
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-react@^6.6.0 but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! bootstrap-loader@2.0.0-beta.17 prepublish: `npm run prerelease`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-loader@2.0.0-beta.17 prepublish script 'npm run prerelease'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bootstrap-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prerelease
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bootstrap-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bootstrap-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master\npm-debug.log

C:\ReactJS\bootstrap-loader-master\bootstrap-loader-master>

**Comment by justin808** [comment]
Try to create a small test repo to duplicate your issue. You can ping me here @justin808, and I'll re-open if there's a real issue. You can also get in touch with me at justin@shakacode.com for help.
