### ISSUE TITLE
Using entry point does not load bootstrap into angular2 webapp

### ISSUE THREAD

**Issue by Syntaf** [shakacode/bootstrap-loader#226]
Can't figure out where i'm going wrong with the bootstrap-loader. inside my webpack config I have an entry point for vendor.ts so that bootstrap loads with vendor:

```
    config.entry = isTest ? {} : {
      'polyfills': './src/polyfills.ts',
      'vendor': './src/vendor.ts',
      'app': './src/main.ts', // our angular app
      'bootstrap-loader': './src/vendor.ts'
    };
```

and the jquery loading module later on down in the webpack. The problem is that when weback compiles and I go to my localhost, the bootstrap isn't loaded and the styles are all missing. Am I doing the entry point wrong? I also tried using './src/main' for my `main.ts` but also didn't have any luck. Thanks

**Comment by justin808** [comment]
You might want jquery to load first.

Try to create a small test repo to duplicate your issue. You can ping me here @justin808, and I'll re-open if there's a real issue. You can also get in touch with me at justin@shakacode.com for help.
