### ISSUE TITLE
Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by MagnumDopus** [shakacode/bootstrap-loader#230]
ERROR in ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
Module parse failed: /Users/kevinhunt/Sites/DE2/node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)

Running 1.3.3 

Here is my loader

```
var path = require('path');
var webpack = require('webpack');

var config = {
    devtool: 'cheap-module-eval-source-map',
    entry: [
        'bootstrap-loader',
        './App.js',
    ],
    output: {
        path: path.join(__dirname, 'public'),
        filename: 'bundle.js',
        publicPath: '/public/'
    },
    plugins: [
        new webpack.NoErrorsPlugin()
    ],
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: [
                    path.resolve(__dirname, 'node_modules')
                ],
                query: {
                    presets: ["react", "es2015", "stage-0"]
                }
            },
            {
                test: /\.scss$/,
                loaders: ['style-loader', 'css-loader', 'sass-loader']
            }
        ]
    }
};

module.exports = config;

```

**Comment by justin808** [comment]
@MagnumDopus You'll have to do some more digging on your own. I have no idea on this one.

**Comment by lordptolmy** [comment]
I used this solution to resolve the issue:
https://github.com/webpack/css-loader/issues/38

**Comment by Prologh** [comment]
Changing the file encoding from Unicode (UTF-16 Little Endian) to UTF-8 solved the problem for me.
