### ISSUE TITLE
Setup with AngularClass angular2-webpack-starter

### ISSUE THREAD

**Issue by kjartanvalur** [shakacode/bootstrap-loader#233]
Hi
I´m trying to setup bootstrap-loader with [this](https://github.com/AngularClass/angular2-webpack-starter) boilerplate angular 2 template. I cannot use require('bootstrap-loader') since it breaks AOT. So I´m trying to set this up in webpack entry...  The default entry looks like this

```
 entry: {
      'polyfills': './src/polyfills.browser.ts',
      'main': AOT ? './src/main.browser.aot.ts' : './src/main.browser.ts'
    },
```

I tried putting import 'bootstrap-loader' in polyfills.browser.ts but then I got this following error:

```
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module not found: Error: Can't resolve 'style' in 'C:\data\demoproj\node_modules\bootstrap-loader'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'style-loader' instead of 'style'.
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js 1:21-122
 @ ./~/bootstrap-loader/loader.js
 @ multi bootstrap
```

"bootstrap": "4.0.0-alpha.5",
"bootstrap-loader": "2.0.0-beta.18",

**Comment by vheathen** [comment]
@kjartanvalur has you changed styleLoaders as prescribed in [fresh docs](https://github.com/shakacode/bootstrap-loader#usage) to:

styleLoaders:
  - style-loader
  - css-loader
  - postcss-loader
  - sass-loader

**Comment by vheathen** [comment]
@kjartanvalur that's pretty weird: _labels.scss is a part of bootstrap-sass (bootstrap 3) but not bootstrap 4. Have you set `bootstrapVersion: 4` in .bootstraprc?

**Comment by kjartanvalur** [comment]
@vheathen 
Thanks for response but yes I have set bootstrapVersion: 4 in .bootstraprc

**Comment by kjartanvalur** [comment]
Anyone care to guide me through this? This is a very popular boilerplate

**Comment by vheathen** [comment]
@kjartanvalur 

Seems that bootstrap-loader@2.0.0-beta.18 or one of the loaders can't work with bootstrap 4.0.0-alpha.6 which is downloading as a dependency if you set bootstrap version as `^4.0.0-alpha.5`. If you change it to `4.0.0-alpha.5` it will probably solve the problem.

[Here](https://cloud.mail.ru/public/K8C8/hM3hsJvJQ) is a working copy of my experiments with ng2-webpack-starter and bootstrap 4 alpha 5, I've made it a week ago or so. I did some (not too many) changes to the original webpack configs for bootstrap and font-awesome support. ng2-bootstrap's datepicker and alert work as an example on the Home component. Sorry for a direct link to the archive but I haven't uploaded this code to any public repository. Not sure how long I will keep this file.

Hope it will help you.

But I should mention that I switched to angilar-cli and don't follow it anymore.

**Comment by kjartanvalur** [comment]
Thanks @vheathen 

I will check this out.  But do you have a recommendation on installing bootstrap-loader with angular-cli. I have another question about that here #217

**Comment by vheathen** [comment]
@kjartanvalur do you need namely bootstrap-loader? As I can see in the angular-cli [docs](https://github.com/angular/angular-cli#global-library-installation) you can use bootstrap 4 without bootstrap-loader, as well you can [use ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap/blob/development/docs/getting-started/ng-cli.md) with angilar-cli. But haven't checked by myself though as I decided to move to material design with my current project.

**Comment by Ks89** [comment]
I have a similar boilerplate, partially based on AngularClass.
I don't know If it is useful for you, but if you wanna copy my config check [HERE](https://github.com/Ks89/angular-webpack-skeleton)

I don't know if you can apply everything to AngularClass.
