### ISSUE TITLE
bootstrap-loader fails when extractStyles is enabled (set to true)

### ISSUE THREAD

**Issue by andrefox333** [shakacode/bootstrap-loader#238]
All is well until I turn on extractStyles... Any ideas?

```
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js
Module not found: Error: Can't resolve '[object Object]./lib/bootstrap.styles.loader.js?{"bootstrapVersion":4,"preBootstrapCustomizations":"/Users/andrerecinto/projects/mount-everest/scss/pre-customizations.scss","bootstrapCustomizations":"/Users/andrerecinto/projects/mount-everest/scss/customizations.scss","appStyles":"/Users/andrerecinto/projects/mount-everest/scss/styles.scss","useFlexbox":true,"extractStyles":true,"styleLoaders":["style-loader","css-loader","postcss-loader","sass-loader"],
"styles":["mixins","normalize","print","reboot","type","images","code","grid","tables","forms","buttons","transitions","dropdown","button-group","input-group","custom-forms","nav","navbar", "card","breadcrumb","pagination","jumbotron","alert","progress","media","list-group","responsive-embed","close","badge","modal","tooltip","popover","carousel","utilities"],
"scripts":["alert","button","carousel","collapse","dropdown","modal","popover","scrollspy","tab","tooltip","util"], 
"configFilePath":"/Users/andrerecinto/projects/mount-everest/.bootstraprc","bootstrapPath":"/Users/andrerecinto/projects/mount-everest/node_modules/bootstrap","bootstrapRelPath":"../bootstrap"}' in '/Users/andrerecinto/projects/mount-everest/node_modules/bootstrap-loader'
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js 1:21-1417
```

**Comment by KevinMartin** [comment]
This seems to have been cause by a change between `extract-text-webpack-plugin` versions [Beta 5](https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/v2.0.0-beta.5/index.js#L201) and [RC 0](https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/v2.0.0-rc.0/index.js#L200)

The commit: https://github.com/webpack-contrib/extract-text-webpack-plugin/commit/74b86e0221096c682538472b455118179b7991a3

I switched back to Beta 5 and it works fine now.

**Comment by justin808** [comment]
Please let me know what your findings are. I'm happy to consider a PR.

**Comment by Quayle57** [comment]
I have the same problem with 

> extract-text-webpack-plugin@1.0.1

`ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module not found: Error: Cannot resolve module '[object Object]./lib/bootstrap.styles.loader.js' in /home/user/work/project/node_modules/bootstrap-loader
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js 1:21-1087`

I'm using Bootstrap@4.0.0-alpha.6 and webpack@1.14.0

**Comment by Jorran** [comment]
Related issue in the extract-text-webpack-plugin: [link](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/364).

Bootstrap@4 only seems to work fine with extract-text-webpack-plugin@2.0.0-beta.<x>, just like KevinMartin said.

**Comment by Quayle57** [comment]
Yes but I need to use this with webpack1 :/
Furthermore, the link is now closed saying that the loader should be the one to fix the problem : 

> bebraw commented a day ago
We discussed about this. It's actually a font-awesome-loader issue to fix now as ExtractTextPlugin won't emit a string by design (problematic with function based configuration). So instead of hacking around with a custom toString we'll document how to fix the loader instead.

**Comment by alecf** [comment]
The problem *seems* to be that ExtractTextPlugin is now always returning an array of objects, rather than an array of strings. 

I think it used to return:
```
[ 'style-loader', 'css-loader', '...']
```
and now it returns
```
[{ loader: 'style-loader', options: {...} }, { loader: 'css-loader', options: {...} } ]
```

It seems like https://github.com/shakacode/bootstrap-loader/blob/master/src/utils/buildExtractStylesLoader.js could perhaps be adjusted to handle both arrays of strings *and* objects?

**Comment by TCotton** [comment]
@alecf this code will solve that problem

`ExtractTextPlugin.extract = (before, loader, options) => {
  if (typeof loader === 'string') {
    return [
      ExtractTextPlugin.loader(Object.assign({ omit: before.split('!').length, extract: true, remove: true }, options)),
      before,
      loader
    ].join('!');
  } else {
    options = loader;
    loader = before;
    return [
      ExtractTextPlugin.loader(Object.assign({ remove: true }, options)),
      loader
    ].join('!');
  }
};`

However, this seems to be a separate issue with Webpack 2, ExtractTextPlugin and production builds; and it is not an issue exclusively reserved for bootstrap-loader

I state this because I'm working on the same bug. There is a long thread here about the same error: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/250

**Comment by justin808** [comment]
@TCotton I'd like to get bootstrap-loader v2.0.0 out which relies on Webpack V2 and put V1 into only CRIT fixes from now on.

Any chance that you want to update the dependencies on master and put together a final PR for V2.0.0?

Any other volunteers?

**Comment by ridem** [comment]
I gave it a try by submitting a PR that fixes things for me. Let me know!

**Comment by t47io** [comment]
Hope this can be fixed soon,

**Comment by ridem** [comment]
@t47io 
In case it temporarily helps someone, this what you can do to get it to work:
- Add a `"postinstall": "./fix-bootstrap-loader.sh"` entry to your `package.json`.
- In the same folder, make a file called `fix-bootstrap-loader.sh` with the following content:
```sh
# Ensure we have npm
if ! hash npm 2>/dev/null; then
  echo 'No NPM installed!'
  exit 1
fi

FILEPATH="node_modules/bootstrap-loader/lib/utils/buildExtractStylesLoader.js"

BEFORE="return ExtractTextPlugin.extract({ fallbackLoader: fallbackLoader, loader: restLoaders });"
AFTER="return [ ExtractTextPlugin.loader().loader + '?omit\&remove',    fallbackLoader,    restLoaders  ].join('!');"

if ! cat ${FILEPATH} 2>/dev/null | grep -q "${AFTER}"; then
  echo 'Fixing bootstrap-loader.'
  sed -i.bak "s|${BEFORE}|${AFTER}|g" "${FILEPATH}"
fi
```
- `npm install`

This fix is just the PR I just made.

This works with the latest `ExtractTextPlugin` (2.0.0-rc.2 and 2.0.0-rc.3) and the latest `bootstrap-loader` (beta 20). AFAIK the webpack version has no influence over that bug.

**Comment by arckosfr** [comment]
Hello,

Don't know if it came from the same bug (the error output seems to be same), but my build output is not working (already test with extract-text-webpack-plugin@beta5, it was worse than this) : 
```
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js
Module not found: Error: Can't resolve '[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]./lib/bootstrap.styles.loader.js' in '/home/arckosfr/Saedbox-web/node_modules/bootstrap-loader'
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js 1:21-1047
 @ ./~/bootstrap-loader/extractStyles.js
 @ multi font-awesome-loader bootstrap-loader/extractStyles tether ./src/main.js
```

webpack.base.conf.js
```js
var path = require('path')
var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')
var bootstrapEntryPoints = require('./webpack.bootstrap.config.js')
var ExtractTextPlugin = require('extract-text-webpack-plugin')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

module.exports = {
  entry: [
    'font-awesome-loader',
    bootstrapEntryPoints.prod,
    'tether',
    './src/main.js'
  ],
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    modules: [
      resolve('src'),
      resolve('node_modules')
    ],
    alias: {
      'src': resolve('src'),
      'assets': resolve('src/assets'),
      'components': resolve('src/components')
    }
  },
  module: {
    rules: [
      {
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: "pre",
        include: [resolve('src'), resolve('test')],
        options: {
          formatter: require('eslint-friendly-formatter')
        }
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      },
      {
        test: /bootstrap\/dist\/js\/umd\//,
        loader: 'imports-loader?jQuery=jquery'
      },
      {
      test: /\.css$/,
        loader: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]__[hash:base64:5]' +
          '!postcss-loader',
        }),
      },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'css-loader?modules&importLoaders=2&localIdentName=[name]__[local]__[hash:base64:5]' +
            '!postcss-loader' +
          '!sass-loader',
        }),
      }
    ]
  }
}
```

webpack.prod.conf.js
```js
var path = require('path')
var utils = require('./utils')
var webpack = require('webpack')
var config = require('../config')
var merge = require('webpack-merge')
var baseWebpackConfig = require('./webpack.base.conf')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var ExtractTextPlugin = require('extract-text-webpack-plugin')
var env = config.build.env

var webpackConfig = merge(baseWebpackConfig, {
  module: {
    rules: utils.styleLoaders({
      sourceMap: config.build.productionSourceMap,
      extract: true
    })
  },
  devtool: config.build.productionSourceMap ? '#source-map' : false,
  output: {
    path: config.build.assetsRoot,
    filename: utils.assetsPath('js/[name].[chunkhash].js'),
    chunkFilename: utils.assetsPath('js/[id].[chunkhash].js')
  },
  plugins: [
    // http://vuejs.github.io/vue-loader/en/workflow/production.html
    new webpack.DefinePlugin({
      'process.env': env
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),
    // extract css into its own file
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css')
    }),
    // generate dist index.html with correct asset hash for caching.
    // you can customize output by editing /index.html
    // see https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: config.build.index,
      template: 'index.html',
      inject: true,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true
        // more options:
        // https://github.com/kangax/html-minifier#options-quick-reference
      },
      // necessary to consistently work with multiple chunks via CommonsChunkPlugin
      chunksSortMode: 'dependency'
    }),
    // split vendor js into its own file
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: function (module, count) {
        // any required modules inside node_modules are extracted to vendor
        return (
          module.resource &&
          /\.js$/.test(module.resource) &&
          module.resource.indexOf(
            path.join(__dirname, '../node_modules')
          ) === 0
        )
      }
    }),
    // extract webpack runtime and module manifest to its own file in order to
    // prevent vendor hash from being updated whenever app bundle is updated
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      chunks: ['vendor']
    }),
    new webpack.ProvidePlugin({
        jQuery: 'jquery',
        $: 'jquery',
        jquery: 'jquery',
        "window.moment": "moment",
        'Tether': 'tether',
        'window.Tether': 'tether',
        Tooltip: "exports-loader?Tooltip!bootstrap/js/dist/tooltip",
        Alert: "exports-loader?Alert!bootstrap/js/dist/alert",
        Button: "exports-loader?Button!bootstrap/js/dist/button",
        Carousel: "exports-loader?Carousel!bootstrap/js/dist/carousel",
        Collapse: "exports-loader?Collapse!bootstrap/js/dist/collapse",
        Dropdown: "exports-loader?Dropdown!bootstrap/js/dist/dropdown",
        Modal: "exports-loader?Modal!bootstrap/js/dist/modal",
        Popover: "exports-loader?Popover!bootstrap/js/dist/popover",
        Scrollspy: "exports-loader?Scrollspy!bootstrap/js/dist/scrollspy",
        Tab: "exports-loader?Tab!bootstrap/js/dist/tab",
        Util: "exports-loader?Util!bootstrap/js/dist/util"
    })
  ]
})

if (config.build.productionGzip) {
  var CompressionWebpackPlugin = require('compression-webpack-plugin')

  webpackConfig.plugins.push(
    new CompressionWebpackPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: new RegExp(
        '\\.(' +
        config.build.productionGzipExtensions.join('|') +
        ')$'
      ),
      threshold: 10240,
      minRatio: 0.8
    })
  )
}

if (config.build.bundleAnalyzerReport) {
  var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
  webpackConfig.plugins.push(new BundleAnalyzerPlugin())
}

module.exports = webpackConfig
```
i am miss something ?

thanks :)

**Comment by kuongknight** [comment]
I have same issue, i switch to extract-text-webpack-plugin@2.0.0-beta-5 but it not work

**Comment by ayleesedai** [comment]
I tried @ridem solution and it works fine for me.
I just made a little change, since my team develop on Windows and our continous integration builder is on Linux, so we had little path and execution permission problems.
I made a javascript script and run it with node, instead of using a sh file.

**Comment by JulioC** [comment]
@ayleesedai would you mind sharing it?

**Comment by ayleesedai** [comment]
@JulioC here it is, I didn't attach it before, because it's not a masterpiece of coding, but it works fine. @ridem's sh script  is more sofisticated: it creates a backup copy of the original file and check for npm existance. Anyway:

The **package.json** section:
```
  "scripts": {
    "postinstall": "node fix-bootstrap-loader.js"
  }
```
And the **fix-bootstrap-loader.js**:
```
var fs = require('fs');

var theFile = './node_modules/bootstrap-loader/lib/utils/buildExtractStylesLoader.js';

fs.readFile(theFile, 'utf-8', function(err, data){
	if (err) throw err; // do something her: console.log for example

	var result = data.replace("return ExtractTextPlugin.extract({ fallbackLoader: fallbackLoader, loader: restLoaders });", "return [ ExtractTextPlugin.loader().loader + '?omit\&remove',    fallbackLoader,    restLoaders  ].join('!');");

	fs.writeFile(theFile, result, 'utf8', function (err) {
		if (err) throw err; // do something her: console.log for example
	});
});
```

**Comment by ridem** [comment]
Nice! I feel so old school now with my `sed` command that I had to tweak to get it to work on both Linux and macOS

**Comment by justin808** [comment]
@ridem @ayleesedai @JulioC Should this get a PR?

**Comment by ayleesedai** [comment]
@justin808 Working fine for me, so it's a yes.

**Comment by ridem** [comment]
There's been a merge of the solution into master by https://github.com/shakacode/bootstrap-loader/pull/259

**Comment by Resin01** [comment]
Is is possible to get this new version into NPM?
I have tried this in my package.json but it loads the wrong data.
"bootstrap-loader": "shakacode/bootstrap-loader",

**Comment by justin808** [comment]
2.0.0-beta.21 pushed to npm!

**Comment by justin808** [comment]
Over the next few weeks, @alexfedoseev, @Judahmeek, and I will get this all sorted and make the official 2.0 version of bootstrap-loader!

**Comment by diondirza** [comment]
@justin808 this error still exist in beta latest version.

**Comment by justin808** [comment]
@diondirza Try the config of the examples, paying attention to the versions:

https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic/package.json

**Comment by Resin01** [comment]
@diondirza If i run npm update it installs the 2.0.0-beta.20 instead of 2.0.0-beta.21. I simply deleted the folder and used npm install after which I got the right version (if I run npm update it downgrades again)

**Comment by diondirza** [comment]
@justin808 I think that was false alarm, after I wrote that comment I have switched back to beta.20 and rebuild my app again with no error, after you replied I try to re install beta.21 again and did rebuild and now the error is gone. weird, huh 
anyway I got error unmeet peer dependency for `eslint-plugin-jsx-a11y`, should it be using 4.0.0? I think your `eslint-config-shakacode` need to be updated, because latest `eslint-config-airbnb` need `eslint-plugin-jsx-a11y@^4.0.0`

@Resin01 I run update with command `yarn add bootstrap-loader@2.0.0-beta.21`

**Comment by alexfedoseev** [comment]
> I think your eslint-config-shakacode need to be updated

@diondirza Yep, will be updated later this week.

**Comment by justin808** [comment]
See release 2.1 for alpha 6 support.
