### ISSUE TITLE
ERROR in Cannot find module 'babel/polyfill'  @ ./~/bootstrap-loader/loader.js 1:0-44

### ISSUE THREAD

**Issue by Znow** [shakacode/bootstrap-loader#24]
Getting this error - tried updating, reinstalling, installing babel-polyfill explicitly, etc.

![image](https://cloud.githubusercontent.com/assets/265719/12478671/6a20d1f2-c036-11e5-8c02-d4a00a5ff226.png)

**Comment by AllenFang** [comment]
https://github.com/shakacode/bootstrap-loader/issues/16 is same and I've published a [PR](https://github.com/shakacode/bootstrap-loader/pull/21) for fixing this issues, wait them merge

**Comment by Znow** [comment]
Thanks!

**Comment by alexfedoseev** [comment]
I'll get on current issues/PRs this weekend. Closing this as dup.
