### ISSUE TITLE
Webpack, angular2, bootstrap-loader and jquery - Question

### ISSUE THREAD

**Issue by NelsonLamprecht** [shakacode/bootstrap-loader#246]
Honestly, not sure where the problem lies:
Using dotnet core and angular2 with webpack, based on [](http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/) and bootstrap seems to be loaded as I can see the various styles and the scripts are getting loaded into the vendors.js file but the bootstrap events like the nav datatoggle collapse are not wired up.  I am not sure if it related to a problem in angular2 base or angular2 components [my question](http://stackoverflow.com/questions/41986887/angular2-dotnetcore-duplicate-html-tag). Anyone find anything similar?

**Comment by justin808** [comment]
@NelsonLamprecht Your question is too vague to be considered an "issue" of bootstrap-loader.

Please feel free to [contact me directly](mailto:justin@shakacode.com) for individualized help from my team.
