### ISSUE TITLE
Requiring webpack 2.1.0-beta WHY?!

### ISSUE THREAD

**Issue by tubsandcans** [shakacode/bootstrap-loader#247]
warning "bootstrap-loader@2.0.0-beta.20" has incorrect peer dependency "extract-text-webpack-plugin@>=2.0.0-beta".
warning "bootstrap-loader@2.0.0-beta.20" has incorrect peer dependency "webpack@^2.1.0-beta || ^2.2.0-rc.0".

Why are you depending on a version of webpack that is not the default version served up by npm (1.14.0)? Why don't you at least include instructions for installing the correct dependencies for use under Webpack 1? The confusion between bootstrap-sass/bootstrap-sass-webpack and bootstrap-loader is insanity

**Comment by justin808** [comment]
@tubsandcans We need a PR to update the libraries to depend on only the official released versions of Webpack...

Now that Webpack v2.2 is done...It's time to do this. If you can help us, that would be greatly appreciated!
