### ISSUE TITLE
Partial configuration file default values

### ISSUE THREAD

**Issue by Toilal** [shakacode/bootstrap-loader#248]
When creating a minimalist configuration file, bootstrap styles are not loaded.

```md
bootstrapVersion: 3
scripts: false
```

After debugging, I saw that default value for ```styles``` is false.

Current workaround is to force the styles value to true.

```md
bootstrapVersion: 3
styles: true
scripts: false
```

**Comment by justin808** [comment]
@Toilal you either need to specify a full config file or no config file. That's the current behavior.
