### ISSUE TITLE
The example test pattern for loading jQuery in README fails on Windows.

### ISSUE THREAD

**Issue by whitetrefoil** [shakacode/bootstrap-loader#25]
Maybe we need something like this to make it work on both OSes.

```javascript
{
  test: RegExp(path.normalize('/bootstrap-sass/assets/javascripts').replace(/\\/g, '\\\\')),
  loader: 'imports?jQuery=jquery',
},
```

**Comment by alexfedoseev** [comment]
@whitetrefoil I don't have any windows machine to test this out, but I think for win you just need to change `/` to `\`. Can you test this out?

```js
{ test: /bootstrap-sass\\assets\\javascripts\\/, loader: 'imports?jQuery=jquery' },
```

**Comment by whitetrefoil** [comment]
I guess this will work though I'm not with my computer.  But it will be better if it can work on both format. (Actually my team has multiple different OSes.) ☺



—
通过 Mailbox 发送

**Comment by justin808** [comment]
Please open a new issue with a small sample repo if this still doesn't work on windows.

**Comment by benwill** [comment]
@alexfedoseev - FYI your correct that fix worked for me on Windows. 

{ test: /bootstrap-sass\/assets\/javascripts\//, loader: 'imports?jQuery=jquery' } << Failed on windows
{ test: /bootstrap-sass\\assets\\javascripts\\/, loader: 'imports?jQuery=jquery' } << Works on windows

**Comment by whitetrefoil** [comment]
It no doubt will work on Windows.  But won't you think it will be better if the rule will work on both Windows and Linux/OSX?

It is the official document, it works on only one major OS, it has even no tip for other OS's users and will cost them some hours to debug.

Besides, there are many cases a team will use multiple OSes, e.g. some devs use Win others use OSX and CI server use Linux.
