### ISSUE TITLE
`resolve-url-loader` related problem with `yarn`?

### ISSUE THREAD

**Issue by t47io** [shakacode/bootstrap-loader#250]
Hi, I went into a weird problem that I have not completely figured out. See if some one has better idea.

So everything works if I use `npm`. But after I switched to `yarn`, there is this error when building with `webpack`:

```
ERROR in ./~/css-loader!./~/resolve-url/resolve-url.js!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: ReferenceError: document is not defined
    at Object.resolveUrl (/Website_Server/t47io/main/node_modules/resolve-url/resolve-url.js:21:16)
 @ ./~/style-loader!./~/css-loader!./~/resolve-url/resolve-url.js!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js 4:14-163
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
 @ ./~/bootstrap-loader/loader.js
 @ multi bootstrap-loader ./app/index.jsx
```

First of all, I do have `resolve-url-loader` in my `package.json`, and installed. If I run `npm install`, then the problem goes away. Strange.

I was suspecting that the `.yarnclean` is possibly removing some files. After clearing it, still no luck. The file `postcss.config.js` in Bootstrap-loader was removed by `yarn` (but not matching any rules in the `.yarnclean`, strange!), along with some other `.md` files.

Last, since I'm using `webpack 2.2.1`, I guess it should be `resolve-url-loader` instead of the shorthand `resolve-url` in the call, right?

**Comment by t47io** [comment]
Ah! found it, it's a version problem!!!!!

Here is my `package.json`:
```
  "devDependencies": {
    "bootstrap-loader": "^2.0.0-beta.20",
  }
```

Somehow `yarn` will install version `2.0.0-exports.1`, which leads to the above problem. `npm` correctly installs `2.0.0-beta.20`. Any idea how to fix this though?

**Comment by msaglietto** [comment]
Yes I create a issue on yarn about it https://github.com/yarnpkg/yarn/issues/2648

**Comment by MikeJSX** [comment]
I had the same issue. Adding `resolve-url-loader` to `.bootstraprc` styleLoaders solved my problem.

**Comment by t47io** [comment]
No luck so far. I guess just remember to use `npm`, or do strict versioning in `package.json` for `yarn`
