### ISSUE TITLE
Log message should tell user with missing styleLoaders to add styleLoaders with `-loader` to be compatible with webpack 2

### ISSUE THREAD

**Issue by vjpr** [shakacode/bootstrap-loader#253]
https://github.com/shakacode/bootstrap-loader/blob/master/src/bootstrap.loader.js#L160

Log message should tell user with missing styleLoaders to add styleLoaders with `-loader` to be compatible with webpack 2.

**Comment by justin808** [comment]
@vjpr @Judahmeek @alexfedoseev This seems like a good PR.

@vjpr can you please submit one?
