### ISSUE TITLE
Support custom styleLoaders for extract-text-webpack-plugin

### ISSUE THREAD

**Issue by vjpr** [shakacode/bootstrap-loader#256]
> `make sure your 'styleLoaders' array starts with 'style' or 'isomorphic-style' at index  #0`

I had to patch `style-loaders` and publish as `@vjpr/style-loaders`. This hard-coded requirement for `style-loaders` breaks my config.

I think this should be configurable in case someone wants to use a custom `style-loader`.

Would be good to have a option to disable this error.

**Comment by justin808** [comment]
I'd be supportive of a PR with additional documentation for this.
