### ISSUE TITLE
How to use ExtractTextPlugin when using bootstraprc - bootstrapCustomizations

### ISSUE THREAD

**Issue by Mioleris** [shakacode/bootstrap-loader#258]
I have problem. To override bootstrap variables I use **bootstraprc** - **bootstrapCustomizations** and adding my main style **appStyles**

When running **npm run build** styles are not extracted  becouse they ar not included trough import. I want to override variables and on build action extract two my custom files variables.scss and app.scss

**Comment by justin808** [comment]
@Mioleris Please follow the examples in the /examples/basic directory and post any questions you may have. You need to specify some of the options and provide a full customization file.
