### ISSUE TITLE
EACCESS: permission denied

### ISSUE THREAD

**Issue by Resin01** [shakacode/bootstrap-loader#260]
Hi

I am trying to get this to work with bootstrap 3.3.7 but I am running into this issue.
resolve-url-loader cannot operate: source-map error
  EACCES: permission denied, scandir '/var/www/website/docker-mysql'
I am not quite sure why it is trying to do a scandir on this folder?

I am using the following
"bootstrap-loader": "^2.0.0-beta.20",
"bootstrap-sass": "^3.3.7",
"resolve-url-loader": "^1.6.1",

Thanks!

**Comment by Judahmeek** [comment]
@resin01, you've encountered an incompatibility between sass-loader@5-6 and resolve-url-loader: https://github.com/bholloway/resolve-url-loader/pull/45

Just dealt with this myself. My solution was to pull https://github.com/bholloway/resolve-url-loader/tree/feature/support-sass-loader-6 as a vendor library (yarn demands versions and the latest commit is after the latest release), but if you're using NPM, then just putting `bholloway/resolve-url-loader#feature/support-sass-loader-6` as a github url might be good enough: https://docs.npmjs.com/files/package.json#github-urls

**Comment by Resin01** [comment]
Great seems to be working! One thing is strange though. Seems that the css isnt included in my output css file?
I simply require it in my css setup file (js).
    require('bootstrap-sass');
    require('../sass/admin/layout.scss');

And i then export it to css using
    new ExtractTextPlugin({filename: '../css/[name]/layout.min.css'}),

**Comment by justin808** [comment]
@Judahmeek can we close this issue?

**Comment by Resin01** [comment]
Yes please do :)
