### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by MikeJSX** [shakacode/bootstrap-loader#264]
Hi. I try to update to webpack 2 and everything work except bootstrap-loader.
Next error appear: 
`./~/css-loader!./~/resolve-url/resolve-url.js!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: ReferenceError: document is not defined
    at Object.resolveUrl (/Users/Username/Projects/flymble-webapp/node_modules/resolve-url/resolve-url.js:21:16)
 @ ./~/style-loader!./~/css-loader!./~/resolve-url/resolve-url.js!./~/sass-loader/lib/loader.js?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js 4:14-168 13:2-17:4 14:20-174
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
 @ ./~/bootstrap-loader/loader.js
 @ multi bootstrap-loader react-hot-loader/patch webpack-hot-middleware/client?reload=true&path=http://192.168.0.115:3001/__webpack_hmr ./src/client/index`

**Comment by justin808** [comment]
@MikeJSX did you try out the examples in /examples/basic?

**Comment by MikeJSX** [comment]
Ok, I solved this by adding `resolve-url-loader` to `.bootstraprc` styleLoaders
