### ISSUE TITLE
Specify glyphicon path after build

### ISSUE THREAD

**Issue by sinnbeck** [shakacode/bootstrap-loader#265]
Is it somehow possible to specify the path to where the icons should be placed after building?
I expect it to be something like use: 'url-loader?name=./docs/fonts/[name].[ext] but that does not work.

Edit: Got it working with outputPath=[path]/../../../docs/fonts/, but I hope there is a more simple way of doing it :)

**Comment by justin808** [comment]
@Resin01 I'm not sure what you're asking for. It seems like you found a solution to use a relative path.

**Comment by Resin01** [comment]
Well i was just hoping to be able to do something a bit more simple like outputPath=[path/fonts
It seems that [path] is pointing to node_modules/boostrap-loader/lib. Was hoping to somehow set [path] to use the context set in my webpack config (which is context: path.resolve(__dirname, './docs/'))
