### ISSUE TITLE
@import statements in scss loaded via appStyles not fully extracted

### ISSUE THREAD

**Issue by actraiser** [shakacode/bootstrap-loader#266]
bootstrap-loader works great, thanks for the efforts! There is one thing that annoys me which
I am not sure wether this is by design of bootstrap-loader or me being new to Webpack 2.

I mix bootstrap classes and custom styles to create my templates. For each individual page I create, I add an import statement to a main.scss and which is loaded via 'appStyles' in .bootstraprc:

    appStyles: ./app/styles/main.scss

main.scss looks like this:

    @import "/src/core/Navigation/custom.css";
    @import "/src/core/Footer/custom.css";
    @import "/src/core/Footer/ionicons.css";

This works fine, I can now use all Bootstrap classes as well as my custom styles.

However, when building for production and using the ExtractTextPlugin, the @import-statements are not resolved as I would expect. The resulting style.css-File still includes the @import-statements which result in additional http-requests to the server.

The style.css generated starts like this:

    import url(/src/core/Navigation/custom.css);@import url(/src/core/Footer/custom.css);@import url(/src/core/Footer/ionicons.min.css)....other extracted css.

My expectation would be that the @import statements are parsed and that the CSS in each referenced file is extracted into that single styles.css, that is, removing the @import statements all together.

Is this a limitation when using 'appstyles' in .bootstraprc or is this something I need to take care of in the webpack config? Should I avoid the @import statements? Sorry if this is an obvious question.

Thanks for any advice

Best
-act

**Comment by justin808** [comment]
@actraiser You might want to look into https://github.com/shakacode/sass-resources-loader/. 

I'm quite sure that we support your use case, and that there's an error in some configuration. Feel free to comment more here or to [get in touch](mailto:justin@shakacode.com) if you want individual help.
