### ISSUE TITLE
Should eslint-xxx be peerDependencies?

### ISSUE THREAD

**Issue by vjpr** [shakacode/bootstrap-loader#267]
```
npm install
...
WARN registry.npmjs.org/bootstrap-loader/2.0.0-beta.21 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.
WARN registry.npmjs.org/bootstrap-loader/2.0.0-beta.21 requires a peer of eslint-plugin-react@^6.6.0 but none was installed.
```

Wouldn't they just be for development - so devDependencies?

**Comment by justin808** [comment]
@vjpr you're 100% right!

@Judahmeek Any idea how this snuck in?

@vjpr These should be `devDependencies`. 

Anybody want to do a PR?

**Comment by Judahmeek** [comment]
Those two packages are peer dependencies of [bootstrap-loader](https://github.com/shakacode/bootstrap-loader/blob/master/package.json#L40-L41) so you're going to get that warning anyway.

**Comment by justin808** [comment]
@Judahmeek They probably shouldn't be. There's no for linting to be a peer dependency.
