### ISSUE TITLE
Checklist for version 2.0!

### ISSUE THREAD

**Issue by justin808** [shakacode/bootstrap-loader#273]
What is needed for the 2.0.0 release which will have official support for Webpack 2.2.x and greater?

- [x] Update examples directory to use Webpack 2.2.x
- [x] Update peer dependencies in package.json

What else?

CC: @Judahmeek, @alexfedoseev

**Comment by actraiser** [comment]
Will the peer dependency update include updating "eslint-plugin-jsx-a11y" from 2.2.3 to ^3.0.2  || ^4.0.0? That would be awesome as this would make a local eslint setup with eslint-config-airbnb work. 

-act

**Comment by justin808** [comment]
@actraiser The examples should be updated. Let me know if something is missing.
