### ISSUE TITLE
How do use with isomorphic-style-loader

### ISSUE THREAD

**Issue by kuongknight** [shakacode/bootstrap-loader#276]
I want to load bootstrap in server-side with isomorphic-style-loader
How can i do it?

**Comment by justin808** [comment]
I've looked into this a little bit. Nothing struck me as obvious. @kuongknight have you tried to do some debugging?

**Comment by idangozlan** [comment]
+1, any example? can't figure out how to use it

**Comment by atalebagha** [comment]
+1.  I'm trying to figure this out also.

**Comment by justin808** [comment]
@idangozlan @kuongknight @atalebagha can you try to create an example based on:

https://github.com/shakacode/bootstrap-loader/tree/master/examples/basic

I've looked into this in the past, and it's not clear how we'd even want this to work.

**Comment by Quocnamit** [comment]
does anyone resolve this ? Now I want to load the bootstrap-loader in server side rendering but I can't any solution for that
