### ISSUE TITLE
Is there anyway to load the bootstrap css inline on server side rendering development mode?

### ISSUE THREAD

**Issue by idangozlan** [shakacode/bootstrap-loader#277]

**Comment by justin808** [comment]
@idangozlan can you provide some more details of why you want to do this?

**Comment by idangozlan** [comment]
Cause i don't like the first seconds when the CSS hasn't loaded yet,i would
like to have it inline in the HTML body as part of the response

**Comment by danyim** [comment]
I'm also curious

**Comment by ERPedersen** [comment]
Setting `extractStyles` to `false ` in _.bootstraprc_ did it for me.

**Comment by justin808** [comment]
@ERPedersen, @idangozlan Any chance that this should in the docs? If so, please help me with a doc PR.

**Comment by bherila** [comment]
@ERPedersen is this related to https://github.com/shakacode/bootstrap-loader/issues/276 ? I was not able to get it to work in my testing.

**Comment by ratherblue** [comment]
@bherila I just ran into this after a recent Webpack upgrade. Even if you have `extractStyles: false`, if you also have `css-loader?sourceMap` in your config the styles will load in `<link rel="stylesheet" href="blob:http...">` causing a delay in style loading and showing unstyled elements until the "external"  stylesheet loads.

Still looking into a way to get source maps back to being inline.

**Comment by bherila** [comment]
@ratherblue I think it's related to the source maps being unable to work without an absolute URI prefix being added at runtime.

**Comment by bherila** [comment]
In the end I decided to just hard code bootstrap css path from the CDN and then load only my specific styles through the loader (so no more bootstrap-loader for me). This also helps reduce the size of my bundle which I've been trying to do anyway (I'm approaching 4 MB here and bootstrap ain't helping! lol)
