### ISSUE TITLE
Bootstrap's extractStyles somehow escape from webpack uglify and stored as unminified css on webpack's css bundle 

### ISSUE THREAD

**Issue by idangozlan** [shakacode/bootstrap-loader#280]

**Comment by justin808** [comment]
@idangozlan What exactly is your question or issue?

**Comment by idangozlan** [comment]
How to minify the bootstrap CSS? When using the regular flow for production
of extract + webpack uglify it's not applied on the bootstrap CSS

**Comment by raybooysen** [comment]
I have the same issue.  I have my own CSS, and using Bootstrap CSS.  I have my own ExtractTextPlugin instance which extracts CSS to a file.  

This loader, once enabled, extracts to a different CSS file (which is probably fine) but how do I minify?

**Comment by raybooysen** [comment]
I've got this working through: https://github.com/NMFR/optimize-css-assets-webpack-plugin
Which does a post-build optimise.  

However, it would be good if the loader allows you to specify some options in how the bootstrap CSS is handled so we can pass in minification options, or extract text options.

**Comment by justin808** [comment]
@raybooysen Any PR, code or doc, or just changes to examples, would be awesome!

CC: @idangozlan

**Comment by ufhy** [comment]
this is my .bootstraprc
```
"styleLoaders": [
    "style-loader",
    "css-loader?sourceMap=true&importLoaders=1&minimize=true",
    "sass-loader?sourceMap"
  ],
````
