### ISSUE TITLE
Css is not minimized

### ISSUE THREAD

**Issue by Mioleris** [shakacode/bootstrap-loader#283]
Why bootstrap css is not minimized when using **extractStyles** and **bootstrapCustomizations** and **appStyles**

and when using **appStyles** and **bootstrapCustomizations** adds 3-4s to hot module replacement to reload

```
            {
                test: /\.scss$/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: ['css-loader?minimize&importLoaders=2', 'postcss-loader', 'sass-loader']
                })
            },
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: ['css-loader?minimize&importLoaders=1', 'postcss-loader']
                })
            }
```

Using latest dependencies

**Comment by Mioleris** [comment]
1. Problem is solved adding in .bootstraprc
```
# Webpack loaders, order matters
styleLoaders:
  - style-loader
  - css-loader?minimize&importLoaders=2
  - postcss-loader
  - sass-loader
```

2. Problem with hot module replacement exists. 
When using **appStyles** and **bootstrapCustomizations** to import custom scss files it slows down HMR about 3-4s. If I'm not using them it reloads in about 800ms

**Comment by justin808** [comment]
@Mioleris Maybe if you don't minimize for development? 

@alexfedoseev @Judahmeek This might be a good reason to get this merged: https://github.com/shakacode/bootstrap-loader/pull/126 and then the minimize can be configured the Node.env?

@robwise with the move to Webpacker for React on Rails, we'll need to minimize the CSS using Webpack.

**Comment by justin808** [comment]
@Mioleris Any chance that you can create a doc PR for this one?

**Comment by justin808** [comment]
@Mioleris I'll reopen this one if you recommend we do so.

**Comment by chadsaun** [comment]
Is there a way to make `minimize` dynamic based on environment?

**Comment by alexfedoseev** [comment]
@chadsaun Yes: https://github.com/shakacode/bootstrap-loader#styleloaders
