### ISSUE TITLE
Load order

### ISSUE THREAD

**Issue by markusdanek** [shakacode/bootstrap-loader#284]
https://github.com/markusdanek/t2w-vue/blob/master/src/main.js

Bootstrap CSS gets loaded at last and is overwriting my css. I also get the problem, when I add the Bootstrap CSS via stylesheet link in the index.html :confused:
Some quick ideas how to fix this? :smile_cat:

**Comment by justin808** [comment]
https://github.com/shakacode/bootstrap-loader#appstyles
