### ISSUE TITLE
appStyles: allow object.

### ISSUE THREAD

**Issue by jpmelnik** [shakacode/bootstrap-loader#286]
#The main.scss has multiple @imports.

So, if I set appStyles: src/App/Assets/main.scss, the source maps for each @imports doesn't exists and I can't work on that files.

How can I add multiple scss files into appStyles like "styles" property?

- Bootstrap styles
styles:

  - Mixins
  mixins: true

  - Reset and dependencies
  normalize: true
  print: true
  glyphicons: true

...

**Comment by justin808** [comment]
@jpmelnik Do you still have this question? Please ask me to re-open if you do.

If you found the answer, please consider submitting a doc PR.
