### ISSUE TITLE
CSS-module bs4:prod example currently fails due to extract-text plugin error.

### ISSUE THREAD

**Issue by Judahmeek** [shakacode/bootstrap-loader#287]
Apparently related to https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/417

**Comment by mvillis** [comment]
heads up. tried building against webpack master branch (post the PR being merged https://github.com/webpack/webpack/pull/4189) and still getting extract-text-plugin-error. could be just me? my config is based on the css-modules example.

**Comment by Judahmeek** [comment]
@mvillis We've got a working project with CSS modules, BS 4, & bootstrap-loader all fully updated. I'll spend some time and see if I can't figure out why bootstrap-loader's example errors out but our project doesn't.

**Comment by mvillis** [comment]
got mine working too. was a webpack config error on my behalf (nothing to do with the example in the end). thanks for your help!
