### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by frizar** [shakacode/bootstrap-loader#291]
Hello, i use bootstrap v4.0.0-beta.6
When i try use `webpack` i get error:

ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
Module build failed: Error: Could not resolve module 'bootstrap-sass' which must be installed when bootstrap version is configured to v3.
You must install 'bootstrap' for bootstrap v4 or 'bootstrap-sass' for bootstrap v3.
You can also specify the location manually by specifying 'bootstrapPath' in bootstrap-loader's query string.
See https://github.com/shakacode/bootstrap-loader/blob/master/README.md#usage.
    at Object.module.exports.pitch (E:\reps\support\node_modules\bootstrap-loader\lib\bootstrap.loader.js:147:11)
 @ ./~/bootstrap-loader/loader.js 2:17-61
 @ multi bootstrap-loader ./src/js/app.js

**Comment by Igor-Vuk** [comment]
Yes, I have got the same problem with Bootstrap 4

**Comment by justin808** [comment]
> Module build failed: Error: Could not resolve module 'bootstrap-sass' which must be installed when bootstrap version is configured to v3.

@frizar, @Igor-Vuk You need to set the bootstrap version in your config file.

https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic/.bootstraprc-4-example

**Comment by Igor-Vuk** [comment]
Hello justin808, 
afkors I did that. I copied the default config for bootstrap 4 and added -loader to loaders. It's version 4 by default there. It's still not working. Asking me for bootstrap-sass event though bootstrap 4 is designated in config file. It should b epicking up instaled packed bootstrap(version alpha 6). I even tried to designate the whole path to bootstrap folder. No luck.
