### ISSUE TITLE
Update default bootstraprc-4 properties to reflect changes in bootstrap v4 alpha 6

### ISSUE THREAD

**Issue by mircowidmer** [shakacode/bootstrap-loader#292]
In the release of alpha 6 (https://github.com/twbs/bootstrap/releases/tag/v4.0.0-alpha.6) the following renames occured: 
- tag -> badge
- animation -> transitions

This is not reflected in the default properties provided with https://github.com/shakacode/bootstrap-loader/blob/master/.bootstraprc-4-default

The following lines
`animation: true`
`tags: true`

should be changed to

`transitions: true`
`badge: true`

**Comment by justin808** [comment]
I commented in #293.
