### ISSUE TITLE
ExtractTextPlugin error using mixins

### ISSUE THREAD

**Issue by salacis** [shakacode/bootstrap-loader#295]
The provided example on how to make mixins available within seems to be outdated.

Using ExtracTextPlugin ^2.1.0 leads to the following error message:

`Error: Breaking change: extract now only takes a single argument. Either an options object *or* the 
  loader(s). Example: if your old code looked like this:`

`ExtractTextPlugin.extract('style-loader', 'css-loader') You would change it to: `
`ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' })`

Even though the suggested alternativ syntax leads to another error:
`TypeError: element.loader.split is not a function`

Can I fallback to an older version of extract text plugin and which one would it be?

**Comment by justin808** [comment]
@salacis Any chance that you can submit a PR to update the examples?

**Comment by salacis** [comment]
Can be closed. Loaded wepack v2 by mistake.
https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/README.md
