### ISSUE TITLE
Bootstrap-loader exposes deployment location in Chrome dev tools

### ISSUE THREAD

**Issue by jwhitmarsh** [shakacode/bootstrap-loader#296]
Is this a configuration issue? What is occurring here? 

![screen shot 2017-04-28 at 12 19 27](https://cloud.githubusercontent.com/assets/8026009/25526810/40de65fe-2c0d-11e7-909c-2e0caa545a26.png)

**Comment by justin808** [comment]
@jwhitmarsh Feel free to request re-opening this issue.
