### ISSUE TITLE
Brand-variables not changing the background and border colors of buttons.

### ISSUE THREAD

**Issue by ERPedersen** [shakacode/bootstrap-loader#301]
Brand-variables are not changing the background and border colors of buttons. I assume this is unintended, since it has been standard functionality in _bootstrap-sass_ since release.

**.bootstraprc**
```yml
bootstrapCustomizations: ./src/bootstrap/customizations.scss
```

**src/bootstrap/customizations.scss:**
```scss
$brand-primary: red;
$body-bg: yellow;
```

**index.html**
```html
<a href="#" class="btn btn-primary">I should be red :(</a>
<p class="text-primary">I should be red</p>
```

**Result:**
![screenshot](http://i.imgur.com/V3hpnyB.png)

**Comment by justin808** [comment]
@ERPedersen can you help us debug this? and figure out:

* What version this broke?
* Using what version of bootstrap?

And:

* Line of code causing issue.

**Comment by justin808** [comment]
@ERPedersen At the min, please submit a PR that changes something in the https://github.com/shakacode/bootstrap-loader/tree/master/examples/basic directory and then we'll fix this.

**Comment by justin808** [comment]
@ERPedersen Please ask me to re-open this issue once you've responded to my questions and suggestions.

**Comment by ERPedersen** [comment]
@justin808 this is no longer an issue in the latest version of Node JS `6.11.2` 👍
