### ISSUE TITLE
Multiple bootstrap themes

### ISSUE THREAD

**Issue by Mioleris** [shakacode/bootstrap-loader#305]
Is there ability to build multiple bootstrap themes ?
theme-1.css
theme-2.css

And in the end correct one would be included in <head> part depending on config file?

**Comment by Mioleris** [comment]
I want to extract multiple themes like this:
```
`bootstrap-loader/lib/bootstrap.loader?extractStyles&configFilePath=${__dirname}/.bootstraprc-green!bootstrap-loader/no-op.js`,
`bootstrap-loader/lib/bootstrap.loader?extractStyles&configFilePath=${__dirname}/.bootstraprc-orange!bootstrap-loader/no-op.js`,
```

but every time it's extracted and merged to single file.

**Comment by velveret** [comment]
I got this to work following the `multiple-entries` example (set up one entry per theme like https://github.com/shakacode/bootstrap-loader/blob/master/examples/multiple-entries/webpack.dev.config.js#L9). I also had to use `extractStyles` (https://github.com/shakacode/bootstrap-loader#extractstyles) and set the `extract-text-webpack-plugin` to output each CSS file as `[name].css`.

**Comment by justin808** [comment]
@velveret Should we put in a doc change for this?

**Comment by justin808** [comment]
@Mioleris Please tell me if we should re-open this issue. I just updated the docs thanks to @velveret.
