### ISSUE TITLE
angular 2 webpack bootstrap error bootstrap-loader

### ISSUE THREAD

**Issue by hesampour** [shakacode/bootstrap-loader#307]
hello. 
I working on angular 4 and webpack with ng2-admin.
after updating I have problem loading bootstrap 4 and get this error.
I am using bootstrap loader.

at Error (native)
 @ ./~/style-loader!./~/css-loader!./~/postcss-loader!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?sourceMap!./~/bootst
rap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":4,"useFlexbox":false,"extractStyles":false,"styleLoaders":["style
","css","postcss","sass"],"styles":["mixins","normalize","print","reboot","type","images","code","grid","tables","forms","butto
ns","dropdown","button-group","input-group","custom-forms","nav","navbar","card","breadcrumb","pagination","jumbotron","alert",
"progress","media","list-group","responsive-embed","close","transitions","modal","tooltip","popover","carousel","utilities"],"s
cripts":["alert","button","carousel","collapse","dropdown","modal","popover","scrollspy","tab","tooltip","util"],"configFilePat
h":"C://Users//client side//.bootstraprc","bootstrapPath":"C://Users//client side//~//bootstrap","bootstrapRelPath":"..//bootstrap"}!./~/bootstrap-loader/no-op.js 4:14-1151
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js
 @ ./~/bootstrap-loader/loader.js
 @ ./src/vendor.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/vendor.browser.ts

**Comment by justin808** [comment]
Hi @hesampour Please more carefully state your issue and possibly create an open source reproduction case. Any research you can do into this is appreciated. Please feel free to request re-opening the issue.

If you want personalized help on this, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).
