### ISSUE TITLE
Warning "Previous source map found, but options.sourceMap isn't set"

### ISSUE THREAD

**Issue by Janaka-Steph** [shakacode/bootstrap-loader#309]
Hello,

Despite all my efforts, I can't get rid of the postcss warning "Previous source map found, but options.sourceMap isn't set"
If I remove bootstrap-loader and all related things I don't have the warnings anymore.

Some packages I have:

babel-plugin-react-css-modules: 3.0.0
bootstrap: 4.0.0-alpha.6
bootstrap-loader: 2.1.0
node-sass: 4.5.3
postcss-loader: 2.0.6
postcss-scss: 1.0.1
precss: 1.4.0
sass-loader: 6.0.6
webpack: 2.6.1
webpack-dev-server: 2.5.0
My webpack.config.js : https://pastebin.com/QgLGNUbH
My webpack.bootsrap.config.js : https://pastebin.com/X9H0CTv6
My postcss.config.js : https://pastebin.com/a5grb2qx
My .bootstraprc : https://pastebin.com/NVq8Ne4J

The github repo : https://github.com/asseth/dao1901

I mention disableSassSourceMap: true in the .bootstraprc but it has no effect on the warnings.

Thank you for your help

**Comment by justin808** [comment]
@Janaka-Steph Please debug this a bit further. Thre could be something specific to the versions of the libraries you are using.

Sometimes it's best to just ignore some messages.

Please ask me to re-open this issue when you have more information.

**Comment by Janaka-Steph** [comment]
I don't see what more can I do.

**Comment by b-zee** [comment]
I had the same and solved it by appending `?sourceMap` to `css`, `postcss` and `sass` in the default Bootstrap 4 `.bootstraprc`:

```
styleLoaders:
  - style
  - css?sourceMap
  - postcss?sourceMap
  - sass?sourceMap
```

**Comment by justin808** [comment]
@b-zee, @Janaka-Steph can either of you submit a doc PR for this?

**Comment by SupinePandora43** [comment]
in https://github.com/postcss/postcss/issues/1276 solved same issue but with stylus-loader
