### ISSUE TITLE
`npm i` hangs in examples/css-modules 

### ISSUE THREAD

**Issue by janusch** [shakacode/bootstrap-loader#31]
Hey,
I am extremly excited about this project, great work so far!

There is just a tiny problem that keeps me from checking out the example. Was just wanting to have a quick look at the css-modules example and when I run `npm i` it hangs at:
`loadDep:bootstrap → after ▌ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
`

What am I doing wrong?

I am using npm version 3.5.2

Best Regards

**Comment by justin808** [comment]
what version of node?

**Comment by alexfedoseev** [comment]
It might be `bootstrap@4` from git repo, sometimes it takes ages to install it. Not sure how to debug it.

**Comment by janusch** [comment]
Hey, 
thanks for the quick replies!

I think I was on an old node version 0.10.38 or something like that. Now it installs fine with node v4.2.2.

Cheers!
