### ISSUE TITLE
bootstrap-loader not importing activated Styles

### ISSUE THREAD

**Issue by visualcookie** [shakacode/bootstrap-loader#312]
Having a problem when executing my application `yarn dev`. It just loads in buttons, forms etc. except for the navbar. The navbar has not the styling it should have like documented on the Bootstrap page.

My configs: https://gist.github.com/visualcookie/1e790786bd9e73a9341770f87e648566

**Comment by justin808** [comment]
@visualcookie Please create a test repo based on something within:

https://github.com/shakacode/bootstrap-loader/tree/master/examples

and then please ask me to re-open this issue.
