### ISSUE TITLE
[question] Optimize bs4.css with this loader?

### ISSUE THREAD

**Issue by janusch** [shakacode/bootstrap-loader#318]
Hey,
I really like this project and have been using the bs4 version since it was offered.
Now with the first bs4-beta release I came to ask myself, why is it again that this loader is needed?

In the official bs documentation is a section on webpack now: 
https://getbootstrap.com/docs/4.0/getting-started/webpack/ 

What was intriguing earlier was to use it in conjunction with css modules. Now I just use bootstrap 4 scss and css modules side by side. 

It would be really nice if some of the optimizations that css in js offer, e.g. remove unused bs4 styles etc. could be done. Or a way of how to use bs4 in a composable manner through custom react components without having to include bs4.css globally?

Would this be a different project or is it possible to do some optimizations through this loader in the future?
Maybe I am also just taking bootstrap-loader for granted because it works so smooth and my questions are nonsense to you?

I think it would be great to add a short statement of purpose of this loader to the readme. 

Thanks in advance for a reply :smile_cat:

**Comment by justin808** [comment]
@janusch Let me know if you want to collaborate. These ideas sound promising!

**Comment by janusch** [comment]
@justin808 Thank you for getting back to me!
I'll spend some time this weekend to straighten out my thoughts on this. I will also do some testing on what webpack and cssmodules can help with if we want to eliminate global styles and unused styles.
More input would be highly appreciated. I am not entirely sure on how to approach this yet.
I'll keep you posted!

**Comment by justin808** [comment]
Please email me: [justin@shakacode.com](mailto:justin@shakacode.com) for a slack invite for collaboration with my team.
