### ISSUE TITLE
Multiple webpack entry points

### ISSUE THREAD

**Issue by Darkside73** [shakacode/bootstrap-loader#32]
Is it possible to map appStyles (along with customizations) files to correspondent entry points?

**Comment by alexfedoseev** [comment]
Currently not, but we will need this probably here and 100% in [shakacode/sass-resources-loader](https://github.com/shakacode/sass-resources-loader)

**Comment by Judahmeek** [comment]
What exactly are the functional requirements here? Just accepting lists of paths instead of a single one?

This would be easily solved along with/by #125
