### ISSUE TITLE
Error: Cannot find module './lib/bootstrap.loader!./no-op.js'

### ISSUE THREAD

**Issue by thebedivere** [shakacode/bootstrap-loader#325]
I'm trying to get this set up in webpack, and I am stuck with errors.

If I try `require('bootstrap-loader');` at the top of my webpack.config, I get `Error: Cannot find module './lib/bootstrap.loader!./no-op.js'`

If I try `module.exports = { entry: [ 'bootstrap-loader, etc...` I get `Module build failed: Error: Failed to find '../bootstrap/scss/_mixins'`

Ok, I try setting the path to bootsrap. `module.exports = { entry: [ 'bootstrap-loader?bootstrapPath=node_modules/bootstrap/', etc...` which gives me the error `Module build failed: Error: Failed to find '../bootstrap/scss/_mixins'`

I try setting the boostrap path using require `require('bootstrap-loader?bootstrapPath=/node_modules/bootstrap/');
` which gives the error `Error: Cannot find module 'bootstrap-loader?bootstrapPath=/node_modules/bootstrap/'`

I've been going around this in circles for a few hours. Any ideas of what I need to do, or is this a bug?

**Comment by JESii** [comment]
Same here, and lots of other posts with this issue -- any suggestions as to a resolution?

**Comment by justin808** [comment]
@thebedivere @JESii can you sync the repo and get the examples to work: 

https://github.com/shakacode/bootstrap-loader/tree/master/examples

Most likely, there's some change in the versions of the libraries, webpack, etc. 

My team would love to help, but we need to prioritize our "pro customers". For more information on that program, see [http://www.shakacode.com/work/shakacode-coaching-plan.pdf](http://www.shakacode.com/work/shakacode-pro-support.pdf).

**Comment by raunofreiberg** [comment]
+1 to this. Can't get the examples to work either in any way. 

Traceback:
```
➜  css-modules git:(master) ✗ npm run bs3:default:dev

> bootstrap-loader-css-modules-example@0.0.1 bs3:default:dev /Users/rauno/Desktop/repos/bootstrap-loader/examples/css-modules
> npm run bs3:default:setup && npm start


> bootstrap-loader-css-modules-example@0.0.1 bs3:default:setup /Users/rauno/Desktop/repos/bootstrap-loader/examples/css-modules
> cp -f .bootstraprc-3-example .bootstraprc


> bootstrap-loader-css-modules-example@0.0.1 start /Users/rauno/Desktop/repos/bootstrap-loader/examples/css-modules
> nodemon --watch server.dev.js server.dev.js

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: server.dev.js
[nodemon] starting `node server.dev.js`
=> bootstrap-loader configuration: bootstrap-loader
=> 🔥  Webpack dev server is running on port 4000
webpack built 2db19f19a8fe4a1bb751 in 2523ms
Time: 2523ms
                                 Asset     Size  Chunks  Chunk Names
  674f50d287a8c48dc19ba404d20fe713.eot   166 kB
  912ec66d7572ff821749319396470bde.svg   444 kB
  b06871f281fee6b241d60582ae9369b9.ttf   166 kB
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB
 fee66e712a8a08eef5805a46892932ad.woff    98 kB
                                app.js  2.98 MB       0  main

ERROR in /Users/rauno/Desktop/repos/bootstrap-loader/loader.js
Module not found: Error: Can't resolve './lib/bootstrap.loader' in '/Users/rauno/Desktop/repos/bootstrap-loader'
 @ /Users/rauno/Desktop/repos/bootstrap-loader/loader.js 4:17-61
 @ multi webpack-hot-middleware/client tether font-awesome-loader bootstrap-loader ./app/startup/App
```

**Comment by justin808** [comment]
@raunofreiberg focus on this error:

```
ERROR in /Users/imac/Desktop/code/bootstrap-loader/lib/bootstrap.loader.js!/Users/imac/Desktop/code/bootstrap-loader/no-op.js
Module build failed: Error: Could not resolve module 'bootstrap-sass' which must be installed when bootstrap version is configured to v3.
You must install 'bootstrap' for bootstrap v4 or 'bootstrap-sass' for bootstrap v3.
```
