### ISSUE TITLE
appStyles appear before bootstrap

### ISSUE THREAD

**Issue by ssuhat** [shakacode/bootstrap-loader#33]
Hi,

I've tried to add my custom .scss file and at .bootstraprc i setup like this:

    bootstrapVersion: 3
    styleLoaders:
     - style
     - css
     - sass
     
    appStyles: ./src/sass/main.scss

    styles:

    # Mixins
    mixins: true

    # Reset and dependencies
    normalize: true
    print: true
    glyphicons: true

    # Core CSS
    scaffolding: true
    type: true
    code: true
    grid: true
    tables: true
    forms: true
    buttons: true

    # Components
    component-animations: true
    dropdowns: true
    button-groups: true
    input-groups: true
    navs: true
    navbar: true
    breadcrumbs: true
    pagination: true
    pager: true
    labels: true
    badges: true
    jumbotron: true
    thumbnails: true
    alerts: true
    progress-bars: true
    media: true
    list-group: true
    panels: true
    wells: true
    responsive-embed: true
    close: true

    # Components w/ JavaScript
    modals: true
    tooltip: true
    popovers: true
    carousel: true

    # Utility classes
    utilities: true
    responsive-utilities: true

    ### Bootstrap scripts
     scripts:
      transition: true
      alert: true
      button: true
      carousel: true
      collapse: true
      dropdown: true
      modal: true
      tooltip: true
      popover: true
      scrollspy: true
      tab: true
      affix: true

The problem is when I build the file, my custom css is load before bootstrap file.  

My main.scss:

    @import '~animate.css/animate.min.css';

    $color: blue;

    body{
       color:$color;
    }

As i recheck `body{}` is appear after bootstrap. but import file before bootstrap.

Is this suppose to be like this or I make a mistake?

**Comment by justin808** [comment]
@ssuhat Create a simple example and if you can reproduce this, please open a new issue and reference the simple example. See the examples directory.

I'm not sure you can import .css files. I think they have to be scss files.

**Comment by alexfedoseev** [comment]
@ssuhat I guess you messed up with indentions in your `.bootstraprc`, it matters in `yaml`.
