### ISSUE TITLE
Customization files are ignored

### ISSUE THREAD

**Issue by brallanAguilar** [shakacode/bootstrap-loader#330]
Hello. I am using Bootstrap 4.0.0-beta.2 and the files specified on `preBootstrapCustomizations` and `bootstrapCustomizations` are ignored. For example, in `bootstrapCustomizations` I have:

```sass
$body-bg: $gray-300
```
and that setting is never read. Before the beta 2 release, all was working nicely.

**Comment by justin808** [comment]
@apcomptec can you try to reproduce this in the https://github.com/shakacode/bootstrap-loader/tree/master/examples ?

**Comment by apcomptec** [comment]
@justin808 I clone the repo, and did the following (using the *basic* example):

```
npm i
npm run bs4
```
but I got:

```
ERROR in multi webpack-hot-middleware/client tether font-awesome-loader bootstrap-loader/lib/bootstrap.loader?configFilePath=/tmp/bootstrap-loader/examples/basic/.bootstraprc-4-example!bootstrap-loader/no-op.js ./app/scripts/app
Module not found: Error: Can't resolve 'bootstrap-loader/lib/bootstrap.loader' in '/tmp/bootstrap-loader/examples/basic'
 @ multi webpack-hot-middleware/client tether font-awesome-loader bootstrap-loader/lib/bootstrap.loader?configFilePath=/tmp/bootstrap-loader/examples/basic/.bootstraprc-4-example!bootstrap-loader/no-op.js ./app/scripts/app
```
so, at the moment I can't verify your question

**Comment by Andrey-Pavlov** [comment]
Hello. How to override $bg-{color}? Customization files don't work for me.

**Comment by WillooWisp** [comment]
Any progress here?

**Comment by justin808** [comment]
I'd need some help to get to bottom of this issue.

**Comment by nootrope** [comment]
@apcomptec : I've been able to use and customize BS4 by [following their Webpack notes](https://getbootstrap.com/docs/4.0/getting-started/webpack/), bypassing bootstrap-loader altogether. Custom overrides for default variables, via a `_custom.scss` `@import` [are addressed](https://getbootstrap.com/docs/4.0/getting-started/webpack/#importing-precompiled-sass). As frequently as BS4 is changing, I don't blame @justin808 for waiting until it settles down to (perhaps?) update bootstrap-loader.

**Comment by justin808** [comment]
@nootrope @WillooWisp @apcomptec I'm happy to merge any PR shown to be valuable.
