### ISSUE TITLE
grid-breakpoints now working

### ISSUE THREAD

**Issue by grounded-warrior** [shakacode/bootstrap-loader#335]
I can't seem to use grid breakpoints in my scss with the following error

    @return if($n < length($breakpoint-names), nth($breakpoint-names, $n + 1), null);
            ^
      Undefined operation: "null lt 5".

i have 
    
    # Mixins
    mixins: true

in my `.bootstrap.rc` and in my webpack.js i have

        test: /\.s?css$/,
        use: [
          'style-loader',
          'css-loader',
          'postcss-loader',
          'sass-loader',
          {
            loader: 'sass-resources-loader',
            options: {
              resources: [
                './node_modules/bootstrap/scss/_variables.scss',
                './node_modules/bootstrap/scss/_functions.scss',
                './node_modules/bootstrap/scss/mixins/_breakpoints.scss',
              ]
            },
          },
        ],

What am I missing?

**Comment by DavidHalkin** [comment]
Hey. I have the same problem. you could fix it? )

**Comment by Rundik** [comment]
same

**Comment by DavidHalkin** [comment]
@import
	'_custom_bootstrap_vatiables.scss',
	'../../bower_components/bootstrap/scss/_functions.scss',
	'../../bower_components/bootstrap/scss/_variables.scss',
	'../../bower_components/bootstrap/scss/_mixins.scss',
	'_header',
	'_footer';

**Comment by Rundik** [comment]
I fixed this error. I misspelled breakpoint's name
