### ISSUE TITLE
Webpack 4 deprecating extract-text-webpack-plugin

### ISSUE THREAD

**Issue by yazdog8** [shakacode/bootstrap-loader#338]
It looks like Webpack is deprecating extract-text-webpack-plugin in favor of [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin). Discussion can be found here: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/731.

Are there plans to upgrade the loader for Webpack 4?

**Comment by VyvIT** [comment]
Tired to fiddle with **bootstrap-loader\lib\utils\buildExtractStylesLoader.js** by switching to  mini-css-extract-plugin: 
```javascript
 var ExtractTextPlugin = void 0;
 try
 {
   // eslint-disable-next-line global-require
   ExtractTextPlugin = require('mini-css-extract-plugin'); // <- HERE
 }
 catch (error)
 {
   throw new Error('\nCould not find \'mini-css-extract-plugin\' module.\nMake sure it\'s installed in your \'node_modules/\' directory.\nError: ' + error + '\n');
 }
 var restLoaders = loaders.slice(1).map(function (loader)
   {
     return loader + '!';
   }
   ).join('');
// was this: ExtractTextPlugin.loader().loader and removed fallback param
 return [ExtractTextPlugin.loader + '?{"omit":1,"remove":true}', restLoaders].join('!'); // <- HERE
```
Seems to do the job for my project, let me know if I can create a PR of some sort.
Also, not sure about the {"omit":1,"remove":true}, probably those are no longer needed as well? Right?

My 2 cents: would it make sense to make some sort of configuration to specify the loader to be used for text extraction with it's options?

**Comment by justin808** [comment]
@yazdog8 If you can help us with this, that would be great.

**Comment by VyvIT** [comment]
@justin808 
Not very familiar with webpack loaders, etc., but here's my attempt.
https://github.com/shakacode/bootstrap-loader/pull/340

**Comment by seuros** [comment]
@justin808 i think this issue can be closed

**Comment by justin808** [comment]
Yep, shipped!

**Comment by t47io** [comment]
Question about this. So `mini-css-extract-plugin` is only compatible with `webpack` v4, which makes `bootstrap-loader` v3 not backward compatible with `webpack` v3. Should this breaking change be announced in `CHANGELOG` and release notes?
