### ISSUE TITLE
How do I add bootstrap-loader to the webpack object entry point

### ISSUE THREAD

**Issue by abepark01** [shakacode/bootstrap-loader#345]
Hello!

The documentation uses an array when adding `bootstrap-loader` to the entry point, but how would I do the same when using an object for the entry point?

```
entry: [ 'bootstrap-loader', './app' ]
```

```
entry: { 
  /* how do I add bootstrap-loader here? */
}
```

**Comment by justin808** [comment]
@abepark01 I think the array is like 

```js
entry: {
  someName: [ 'a', 'b']
}
```

so the plain array is just the default name.

**Comment by abepark01** [comment]
@justin808 Thank you! 🤙
