### ISSUE TITLE
Support webpack4 ?

### ISSUE THREAD

**Issue by sylogex** [shakacode/bootstrap-loader#346]
Hi! This lib doesn't support webpack4 ?

npm install --save-dev extract-text-webpack-plugin@4.0.0-beta.0

npm WARN bootstrap-loader@2.2.0 requires a peer of extract-text-webpack-plugin@>=2.1.0 but none is installed. You must install peer dependencies yourself.

**Comment by justin808** [comment]
@sylogex I want this to! Can you give me a hand? 

I think this is related: https://github.com/shakacode/bootstrap-loader/pull/340

Let's do this!

I've got a slack for contributors or anybody interested. Email me: justin@shakacode.com

**Comment by seuros** [comment]
@justin808 i think this issue can be closed.

**Comment by justin808** [comment]
Yep, shipped!
