### ISSUE TITLE
Use cosmiconfig to get the bootstraprc file

### ISSUE THREAD

**Issue by muuvmuuv** [shakacode/bootstrap-loader#353]
It happened today that I had to realize that bootstrap-loader cannot find my `.bootstraprc.json`. There is a package called [Cosmiconfig](https://github.com/davidtheclark/cosmiconfig) that would better handle those configs.

**Comment by justin808** [comment]
Excellent suggestion!

@muuvmuuv I'd be open to considering a PR.

**Comment by justin808** [comment]
@alexfedoseev Agree it's a good idea?

**Comment by x-yuri** [comment]
@justin808 Unfortunately, not in the near future. I don't have a problem with naming the file `.bootstraprc`.

What's really annoying is that you [can't][1] just `import 'bootstrap-loader'` on production. I hope I'll be able to work around that, but being able to just `import 'bootstrap-loader'` would be great. Switching to `require` might introduce issues with CSS order (`imports` are hoisted), tree shaking.

[1]: https://github.com/x-yuri/example-webpack-css-order/tree/bootstrap-loader-node-modules-symlink
