### ISSUE TITLE
css-importer

### ISSUE THREAD

**Issue by janusch** [shakacode/bootstrap-loader#36]
Hey,

this is a feature request.
It would be really useful if it was possible to import css files as part of the app styles and get them compiled into the output file.

There is a package on npm that could do this: `https://www.npmjs.com/package/node-sass-css-importer`
Would you be interested to add a plugin option to the config file .bootstraprc where this could be specified?

The use case is fairly common I think. E.g. external library, widget stylesheets, or old css files. While the latter can be renamed the external ones can not with ease, especially if they are an npm module themselves.

 Looking forward to hear you point of view on this!

**Comment by justin808** [comment]
Do you simply want to include CSS files rather than SASS files? An very, very simple example github repo would be great.

Typically, you should be able to specify other imports per the existing extension hooks. At least that works with Sass files. I guess maybe something special needs to be done with CSS files and you can't just change the extension to .scss?

**Comment by alexfedoseev** [comment]
@janusch @justin808 If it's a plain valid CSS — then it's a valid SCSS. So changing extension shouldn't be a problem. If you want to mark such files, you can name them `my-legacy-styles.css.scss`.

Anyway `appStyles` is not an array of paths, so you must specify one entry point, which must be scss file. After it you can combine your imports inside this entry point file. I took a very quick look at `node-sass-css-importer` and there is a question: why it can't be applied in the array of loaders?

If there is an issue with it, I see one more way to handle it: webpack treats all `@imports` as common `requires`, so you can apply loaders in these imports. It means you can have this structure:

```scss
// app-styles.scss
@import "./my-common-styles";
...
@import "node-sass-css-importer!./my-legacy-styles";

// my-legacy-styles.scss
@import "CSS:some_folder/some_css_file";
```

I guess it's gonna work until [this](https://github.com/sass/sass/issues/193) will be implemented in sass core.

@janusch Let us know if it works for you.

**Comment by janusch** [comment]
Hey @justin808 @alexfedoseev ,
thank you very much for your suggestions!

 I chose the route of least resistance and renamed the files as you @alexfedoseev suggested. That works just fine. The only drawback is that I cannot import the .css files from node_modules directory directly if they have css imports within them. 
e.g. jquery-ui has its styles arranged like this:
 `all.css`
`
@import "base.css";
@import "theme.css";
`

and in `base.css`:

`
@import url("core.css");
@import url("accordion.css");
@import url("autocomplete.css");
@import url("button.css");
@import url("checkboxradio.css");
@import url("controlgroup.css");
@import url("datepicker.css");
@import url("dialog.css");
@import url("draggable.css");
@import url("menu.css");
@import url("progressbar.css");
@import url("resizable.css");
@import url("selectable.css");
@import url("selectmenu.css");
@import url("sortable.css");
@import url("slider.css");
@import url("spinner.css");
@import url("tabs.css");
@import url("tooltip.css");
`

However, the .css files can be imported one by one which is just fine.

Thanks again for your help, it was actually not really related to the awesome `bootstrap-loader`

Keep up the great work!

**Comment by alexfedoseev** [comment]
Glad it helped :+1: Closing this.
