### ISSUE TITLE
Using vulnerable `js-yaml` version

### ISSUE THREAD

**Issue by arturopie** [shakacode/bootstrap-loader#364]
bootstrap-loader is using a vulnerable dependency. See:

![image](https://user-images.githubusercontent.com/762752/54832932-83ffe580-4c93-11e9-90bf-72dbbf81896b.png)

and: https://github.com/shakacode/bootstrap-loader/blob/master/package.json#L51

**Comment by justin808** [comment]
@arturopie Any chance that you can throw in a PR?

**Comment by alecf** [comment]
@arturopie I just pushed one up!

**Comment by arturopie** [comment]
Thanks for the PR @alecf. 
I'm sorry I didn't reply earlier @justin808, I have been very busy recently.

**Comment by justin808** [comment]
@alecf @arturopie I just pushed 3.0.3 without local testing. Please confirm that you don't have any issues.

**Comment by arturopie** [comment]
@justin808 no issues so far. Thanks!

**Comment by amen57** [comment]
v3.0.3 uses js-yaml@3.13.0, but according to https://npmjs.com/advisories/813, it is patched in >=3.13.1. Can you please update this? Thank you.

**Comment by justin808** [comment]
Released!
