### ISSUE TITLE
Using url() in scss throws parse failed error

### ISSUE THREAD

**Issue by markogresak** [shakacode/bootstrap-loader#37]
I'm using bootstrap-loader for the first time and it is working amazingly. Or it was, until I've tried to add a background using `url(...)` syntax, now I can't get it to work.

Every time I try to compile it, I get this error:

```
ERROR in ./src/assets/image.png
    Module parse failed: [project-root-path]/src/assets/image.png Line 1: Unexpected token ILLEGAL
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./~/css-loader!./~/postcss-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js 6:156925-156967
```

I've tried with [adding `resolve-url`](https://github.com/shakacode/bootstrap-loader#paths-to-custom-assets), but it didn't work. I have installed all the dependencies listed in [installation section](https://github.com/shakacode/bootstrap-loader#installation).

I don't even need the resolving url part, for now it would be fine if just the `url()` worked like it's expected to work in regular CSS code.

List of `styleLoaders`:

``` yml
styleLoaders:
  - style
  - css
  - resolve-url
  - postcss
  - sass
```

**Comment by markogresak** [comment]
Fixed by changing above `styleLoaders` to: 

``` yml
styleLoaders:
  - style
  - raw
  - postcss
  - sass
```

Requires [`raw-loader`](https://github.com/webpack/raw-loader) to be installed.

**Comment by lilyxl8** [comment]
Without minification, just `css?-url` and `sass` do the trick. Thanks mate!
