### ISSUE TITLE
Allow custom $icon-font-path

### ISSUE THREAD

**Issue by HorizonXP** [shakacode/bootstrap-loader#38]
So I purchased an official theme from Bootstrap, which comes in LESS format. I converted it to Sass, and it uses a custom icon font, replacing glyphicons. It looks as though `bootstrap-loader` automatically adds the $icon-font-path to point to the location of Bootstrap's Sass files, if the Bootstrap version is 3.

It would be great to disable this default behaviour. Ideally, we should parse the incoming Sass files to see if $icon-font-path has already been declared, but I don't see anything in `bootstrap-loader` that currently does this.

Thus, perhaps it's best to add a configuration option. There are two possible ways we could do this:

1. A boolean option that simply disables the default behaviour. It's then up to the user to properly declare $icon-font-path within their Sass files. I like this option because it allows the user to redeclare the variable within their Sass files if they need to.

2. An option that explicitly points to the fonts folder. This is more explicit, but means the user is forced to point to a single location, and it's not indicated within their Sass files, which doesn't maintain separation of concerns.

**Comment by alexfedoseev** [comment]
Merged.
