### ISSUE TITLE
Plans for bootstrap 5 support?

### ISSUE THREAD

**Issue by dwvisser** [shakacode/bootstrap-loader#397]
I plan on updating my site to bootstrap v5 as soon as there is a stable release. Are there plans to make bootstrap-loader explicitly compatible with bootstrap v5?

**Comment by justin808** [comment]
@dwvisser I'd definitely be happy to get a PR for that! I'd review ASAP!

**Comment by RazielleS** [comment]
I tried `4.0.0-rc.0` with Bootstrap 5, but it doesn't work yet. And I could not find a commit about it.
Does this mean, there won't be any Bootstrap 5 support, since this issue was closed?

**Comment by justin808** [comment]
I'd be open to a PR!
