### ISSUE TITLE
Update wrong version number(s)

### ISSUE THREAD

**Issue by DerZyklop** [shakacode/bootstrap-loader#409]
Right now the newest version of bootstrap-loader is

- [4.0.0 on npm](https://www.npmjs.com/package/bootstrap-loader)
- [3.0.0 in the changelog](https://github.com/shakacode/bootstrap-loader/blob/master/CHANGELOG.md)
- [1.0.9 in the release tags](https://github.com/shakacode/bootstrap-loader/releases)

This is confusing. I assume 4.0.0 is correct, but I can not figure out that are the changes compared to 3.0.4, thus I am afraid to update the package in my project. 

At least a 4.0.0 entry in the changelog would be nice.

**Comment by ahangarha** [comment]
Hi @DerZyklop 
Version 4.0.2 just released.

Please check and let us know if you face any issues.
