### ISSUE TITLE
Error in running basic example

### ISSUE THREAD

**Issue by nicolasxu** [shakacode/bootstrap-loader#43]
ERROR in ./~/bootstrap-loader/loader.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/bootstrap.loader in /Users/nick/Documents/Projects/bootstrap-loader/examples/basic/node_modules/bootstrap-loader
 @ ./~/bootstrap-loader/loader.js 1:0-44

**Comment by justin808** [comment]
@nicolasxu We're happy to help if you create a small demo project on github that demonstrates the issue. Otherwise, you've simply got something misconfigured.

**Comment by nicolasxu** [comment]
It is fixed. 
"bootstrap-loader": "file:../../.", in the package.json in basic example folder caused the problem. I guess it refers to bootstrap-loader in parent folder. Thank you so much!

**Comment by nicolasxu** [comment]
It is fixed. 
"bootstrap-loader": "file:../../.", in the package.json in basic example folder caused the problem. I guess it refers to bootstrap-loader in parent folder. Thank you so much!
