### ISSUE TITLE
WINDOWS: Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by matiishyn** [shakacode/bootstrap-loader#47]
I have an error: `Uncaught ReferenceError: jQuery is not defined`
I have [`imports-loader`](https://github.com/webpack/imports-loader) installed but I still have this error.

Could you please help me to resolve it?
this is my `webpack.config.js`

```js
var path = require('path');
var webpack = require('webpack');

module.exports = {
    devtool: 'source-map',
    entry: [
        'webpack-hot-middleware/client',
        'bootstrap-loader',
        './app/index'
    ],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/static/'
    },
    plugins: [
        new webpack.optimize.OccurenceOrderPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
    ],
    module: {
        loaders: [
            // es6, JSX
            {
                test: /\.js$/,
                loader: 'babel',
                exclude: /node_modules/,
                include: __dirname,
                query: {
                    cacheDirectory: true,
                    presets: ['es2015', 'react', 'stage-0']
                }
            },
            // SASS as CSS modules
            {
                test: /\.scss$/,
                loaders: [
                    "style",
                    "css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]",
                    "sass"
                ]
            },
            // fonts
            {
                test: /\.(woff2?|ttf|eot|svg)$/,
                loader: 'url?limit=10000'
            },

            // Bootstrap 3
            {test: /bootstrap-sass\/assets\/javascripts\//, loader: 'imports?jQuery=jquery'}
        ]
    }
}
```

looks like yours in your examples...

**Comment by matiishyn** [comment]
I see you have the same issue in your examples

**Comment by matiishyn** [comment]
I was experimenting a little bit. `imports-loader` plugin works well. And I'm guessing that you may reproduce this bug on Windows only, since there's another path separator.
So, maybe inside webpack's loader's test expression we should use `path.sep` instead of hardcoded unix's `\`.

Here how test works on my Windows machine:
![image](https://cloud.githubusercontent.com/assets/3661065/13153563/1a03c274-d675-11e5-8147-b5f08c4fbac8.png)

Obviously string like `C:\PROJECTS\TEST\bootstrap-loader\examples\basic\node_modules\bootstrap-sass\assets\javascripts\bootstrap\tab.js` cannot be caught with such regexp `bootstrap-sass\/assets\/javascripts\/`

Am I right? Am I on the right way?

**Comment by justin808** [comment]
@matiishyn, @alexfedoseev and I need a maintainer for windows, as we don't currently use windows, and we didn't necessarily build this loader for windows.

If anybody is interested in the role of being the windows lead, please let us know.

**Comment by justin808** [comment]
@matiishyn I think you're on the right track. We'd be happy to work with you on a PR to fix this issue.

These problems with windows vs. linux are pretty easy to spot and fix when adding copious print debug statements to the source code.

**Comment by vivanac** [comment]
You could just add both cases:
```
webpackConfig.module.loaders.push({
    test: /bootstrap-sass(\\|\/)assets(\\|\/)javascripts(\\|\/)/,
    loader: 'imports?jQuery=jquery'
})
```

**Comment by matiishyn** [comment]
I asked the same question in webpack repo
https://github.com/webpack/webpack/issues/2073

Couldn't make it work like they recommended 
```
{ test: path.resolve(__dirname, "node_modules/boostrap-sass/assets/javascript"),
```
so I used something like @vivanac wrote:
```
{ test: /bootstrap-sass[\\\/]assets[\\\/]javascripts/, ...
```

This closed my issue

**Comment by jbruni** [comment]
I just stumbled upon similar issue: same codebase was working on Linux but not on Windows.

I did just like @matiishyn following @vivanac hint, and got it working.

I will create a PR for the readme...

**Comment by matiishyn** [comment]
@jbruni There's already one here https://github.com/shakacode/bootstrap-loader/pull/44

**Comment by mcianc** [comment]
I use win .. and my problem was that i didn'y installed imports-loader 
installed from
https://github.com/webpack/imports-loader

and used 
        loaders: [
            ...
            { test: /bootstrap-sass[\/\\]assets[\/\\]javascripts[\/\\]/, loader: 'imports?jQuery=jquery' }
        ]


is webpack.config.js

I Solved the problem, JQUERY was included correctly

**Comment by Lazarencjusz** [comment]
I have another solution because nothing from here was not work.

Simply add a plugin :)
```
plugins: [
         new webpack.ProvidePlugin({
             $: "jquery",
             jQuery: "jQuery"
         })
]
```
