### ISSUE TITLE
Bootstrap 4, "Uncaught Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)" with Tooltip

### ISSUE THREAD

**Issue by Kuzmin** [shakacode/bootstrap-loader#48]
Getting the above error while trying to use this with the bootstrap tooltip. I figured it out by exposing Tether on window. I guess it would be a good idea to add this to the documentation since a lot of users will probably be encountering this?

**Comment by re6exp** [comment]
+1

**Comment by chvanikoff** [comment]
Just happened to me so I will +1 as well

**Comment by justin808** [comment]
Is this a doc issue for bootstrap 4? I.e., you just need to be sure your web page loads this?
https://github.com/HubSpot/tether

Any chance that one of you can submit a PR?

**Comment by re6exp** [comment]
Some js components in Bootstrap 4 depends on Tether.js. It can be discovered by bootstrap using window.Tether variable.
If you are using webpack:

1. Set up bootstrap-loader as described in docs;
1. Install tether.js via npm;
1. Add tether.js to the webpack ProvidePlugin plugin:
```javascript
    plugins: [
        <... your plugins here>,
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery",
            "window.Tether": 'tether'
        })
    ]
```

**Comment by justin808** [comment]
I'm fixing the example right now and updating the docs.

I'm updating the examples to alpha-2.

**Comment by justin808** [comment]
Chrome debugger is so useful! "Pause on Caught Exceptions" is :gift:!


![2016-02-27_16-14-31](https://cloud.githubusercontent.com/assets/1118459/13376286/327e7fd4-dd6d-11e5-98fe-8d1b75e89cf1.png)

```js
  /**
   * --------------------------------------------------------------------------
   * Bootstrap (v4.0.0-alpha.2): tooltip.js
   * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
   * --------------------------------------------------------------------------
   */

  var Tooltip = (function ($) {

    /**
     * Check for Tether dependency
     * Tether - http://github.hubspot.com/tether/
     */
    if (window.Tether === undefined) {
      throw new Error('Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)');
    }
```

Fixed in #56.

**Comment by lequy1010** [comment]
You should done my guideline:
1. Add bellow source into Gemfile
```
source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.1.0'
end
```
2. Run command:
`bundle install`
3. Add this line after jQuery in application.js.
```
//= require jquery
//= require tether
```
4. Restart rails server.

**Comment by ThePadawan** [comment]
Note that using Bootstrap 4.0.0-alpha.6, Bootstrap is no longer checking for "window.Tether" but the global variable "Tether", so the webpack configuration becomes
`
    plugins: [
        <... your plugins here>,
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery",
            "Tether": 'tether'
        })
    ]
`

**Comment by sfrjrs** [comment]
@ThePadawan solution worked for me.

My issue was with ASP.NET Core project http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/. I had to add tether to vendor array as well in webpack.config.vendor.js.

entry: {
	vendor: [
		'bootstrap',
		'bootstrap/tether'
	]
},

**Comment by Basel78** [comment]
Hello,
I am building project with Angular2 with Typescript and need to use bootstrap 4.alpha for my navbar, that is complaining about Tether to be added, I have updated the SystemJs.config.js with Tether but still bootstrap complaining with same error mentioned above,
any idea how to update Tether properly using SystemJs.config.js to get bootstrap running properly,
Thanks
