### ISSUE TITLE
Surprising configuration behavior

### ISSUE THREAD

**Issue by febeling** [shakacode/bootstrap-loader#49]
The default values of the configuration are only applied if no configuration is present at all. That is uncommon and confusing.

The README hints at it by saying something like: if a `.bootstraprc` isn't present at all, the default one for Bootstrap 3 is used. It would be less surprising, if the individual configuration attributes were falling back to the (documented) default values. Else, a special note about this behavior in the README might be appropriate.

**Comment by alexfedoseev** [comment]
> The default values of the configuration are only applied if no configuration is present at all. That is uncommon and confusing.

@febeling The opposite will be more confusing IMO: https://github.com/shakacode/bootstrap-loader/issues/5#issuecomment-172315427

**Comment by febeling** [comment]
I feel most configurations work that way. But I don't want to belabor the point. What about a note in the README?

**Comment by alexfedoseev** [comment]
> What about a note in the README?

:+1:

**Comment by justin808** [comment]
Fixed by #56.
