### ISSUE TITLE
Impossible to disable resolve-url-loader

### ISSUE THREAD

**Issue by vjpr** [shakacode/bootstrap-loader#52]
If should be possible to disable it.

Also, its a bit confusing when the `styleLoaders` in the `.bootstraprc` is not the actual loaders used when requiring `bootstrap.style.loader`. A bit too magical IMHO.

`processStyleLoaders.js#46`

```
  if (!resolveUrlLoader) {
    loaders.splice(sassLoaderIndex, 0, 'resolve-url');
  }
```

My reasons for disabling relate to this bug https://github.com/Marak/colors.js/issues/151

**Comment by justin808** [comment]
@vjpr Are you suggesting an option in the config file? Any chance that you can submit a PR?

**Comment by justin808** [comment]
@vjpr Any update on this one?

@alexfedoseev should we include this?

**Comment by alexfedoseev** [comment]
@justin808 Checked a code, it should be safe to configure this via config w/ inclusion by default. @vjpr PR is welcome.

**Comment by Judahmeek** [comment]
So basically, make a boolean in config that stops `bootstrap-loader` from injecting `resolve-url-loader` if true?

**Comment by Judahmeek** [comment]
@justin808 this issue can be closed.
