### ISSUE TITLE
Impossible to disable sass sourceMaps

### ISSUE THREAD

**Issue by vjpr** [shakacode/bootstrap-loader#53]
Source maps are slow. It should not add them unless specified in the `.bootstraprc`.

```
  // We need to check if user's loader already contains sourceMap param
  // And if it's not there - inject it
  var sassLoaderWithSourceMap = undefined;
  if (sassLoaderQuery) {
    sassLoaderWithSourceMap = sassLoaderQuery.includes('sourceMap') ? sassLoader : sassLoader + '&sourceMap';
  } else {
    sassLoaderWithSourceMap = sassLoader + '?sourceMap';
  }
```

**Comment by justin808** [comment]
@vjpr I buy this. Any chance that you can make a PR that includes:

1. README.md changes
2. example in the examples directory
3. core change to the loader?

Thanks!

**Comment by justin808** [comment]
@alexfedoseev This would explain why I can't use the extract-text-plugin with font-awesome and the file-loader.

**Comment by justin808** [comment]
@vjpr Would you like an invite to our private slack room?

Please see #56.

**Comment by justin808** [comment]
Possibly this affects #88.

**Comment by Judahmeek** [comment]
So is bootstrap-loader actually creating a source map or is bootstrap-loader just telling sass-loader to do it?

**Comment by Judahmeek** [comment]
@justin808 this issue can be closed.
