### ISSUE TITLE
webpack works, not seeing styles

### ISSUE THREAD

**Issue by josh--newman** [shakacode/bootstrap-loader#58]
This is my `webpack.config.js`
```js
module.exports = {
  context: __dirname + '/app',
  entry: [
    'bootstrap-loader',
    './app.js',
    './index.html',
  ],

  output: {
    filename: 'app.js',
    path: __dirname + '/dist',
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules)/,
        loader: 'babel',
        query: {
          presets: ['react', 'es2015']
        }
      },
      { test: /\.html$/, loader: 'file?name=[name].[ext]' },
      { test: /\.css$/, loaders: [ 'style', 'css', 'postcss' ] },
      { test: /\.scss$/, loaders: ['style','css','sass'] },
      // Bootstrap 4
      { test: /bootstrap\/dist\/js\/umd\//, loader: 'imports?jQuery=jquery' },
    ],
  },
}
```

I can get a successful `webpack` command, but I'm not seeing any styles in my app. Am I missing something really obvious?

**Comment by chvanikoff** [comment]
@josh--newman did u require bootstrap-loader in your app.js?
`require('bootstrap-loader');`

**Comment by justin808** [comment]
@josh--newman Take a look at the https://github.com/shakacode/bootstrap-loader/tree/master/examples directory and create a small test app.

@chvanikoff Per https://github.com/shakacode/bootstrap-loader/blob/master/examples%2Fbasic%2Fwebpack.dev.config.js#L14, you don't need to do a "require". An entry point does that.

**Comment by chvanikoff** [comment]
@justin808 thank you, will take into a count

**Comment by simonh1000** [comment]
Webpack is so mysterious, it is great when you find something that does the work, but I have the same issue as OP

```
module.exports = {
  entry: './src/index.js',

  output: {
    path: './dist',
    filename: 'index.js'
  },

  resolve: {
    modulesDirectories: ['node_modules'],
    extensions: ['', '.js', '.elm', '.scss']
  },

  module: {
    loaders: [
      {
        test: /\.html$/,
        exclude: [/ignore/, /node_modules/],
        loader: 'file?name=[name].[ext]'
      },
      {
        test: /\.elm$/,
        exclude: [/ignore/, /elm-stuff/, /node_modules/],
        loader: 'elm-hot!elm-webpack'
      },
      {
        test: /\.scss$/,
        exclude: [/ignore/, /elm-stuff/],
        loaders: ["style", "css", "sass"]
      },
      {
        test: /\.css$/,
        exclude: [/ignore/, /elm-stuff/],
        loaders: ["style", "css"]
      },
    //    { test: /bootstrap-sass\/assets\/javascripts\//, loader: 'imports?jQuery=jquery' },
      { test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
          exclude: [/ignore/, /elm-stuff/]
          , loader: 'url?limit=10000&mimetype=application/font-woff'},
      {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
          exclude: [/ignore/, /elm-stuff/],
          loader: 'url?limit=10000&mimetype=application/octet-stream'},
      {test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
          exclude: [/ignore/, /elm-stuff/],
          loader: 'file'},
      {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
          exclude: [/ignore/, /elm-stuff/],
            loader: 'url?limit=10000&mimetype=image/svg+xml'}
    ],

    noParse: /\.elm$/
  },

  devServer: {
    stats: 'errors-only'
  }
};
```

index.js
```
'use strict';

require('./index.html');
// Bootstrap
require('bootstrap-loader');
// require('./assets/css/bootstrap.css');
// MDB bootstrap
// require('./assets/css/mdb.css');
require("./styles.scss");

var Elm = require('./Main');

var elm = Elm.fullscreen(Elm.Main, { swap: false });
```

config
```
---
# You can use comments here

bootstrapVersion: 3

styleLoaders:
  - style
  - css
  - sass

scripts: false
```

**Comment by simonh1000** [comment]
OK, just found that adding `styles: true` seems to help, but not entirely.  Could a default setting be wrong?

**Comment by justin808** [comment]
@simonh1000 It's best to create a simple test app to verify your webpack config with regards to styles.

**Comment by josh--newman** [comment]
I copied the `.bootstraprc-3-default` file into my project root and everything worked.

I haven't had the chance to play around with the default values yet.

**Comment by reywright** [comment]
I'm glad I found this thread.

So I was also having issues last week and today.

First off, make sure your webpack matches the sample webpack config... literally comb through the lines.

The 2nd part: in the example folders there are bootstrap configs... for whatever reason, you want to ignore these and use the config at the root of the project. So if you're using Bootstrap V4, grab the .bootstraprc-4-default... I'm not sure if it's the file name or the config therein but this is what I need to do and now I'm seeing bootstrap styles finally.

**Comment by josh--newman** [comment]
I'm glad this thread helped you. :smile:
