### ISSUE TITLE
How to add overriding rules

### ISSUE THREAD

**Issue by egeriis** [shakacode/bootstrap-loader#60]
I recognize that there is a _pre-customization_ and a _customization_ file, but both seem to be included prior to all rules being defined. What is best practice for overriding rules, that cannot be adjusted using variables?

For example, I want to achieve another `disabled` style for my buttons, and tried adding this to my `customizations.scss` file:

```scss
.btn {
  &.disabled,
  &[disabled],
  fieldset[disabled] & {
    @include opacity(.2);
  }
}
```

But this rule is overridden by the default Bootstrap rule, which tells me that my custom rule is included prior to the default.

How would I go about this?

**Comment by justin808** [comment]
Very simple. Just put this file in your appStyles or some import of your appStyles.

https://github.com/shakacode/bootstrap-loader/blob/master/.bootstraprc-3-default#L47
