### ISSUE TITLE
missing example of derived variables of bootstrap

### ISSUE THREAD

**Issue by davidb583** [shakacode/bootstrap-loader#61]
preBootstrapCustomizations : docs should explain what derived variables are, because reading _variables.scss doesn't help much.

**Comment by justin808** [comment]
What's wrong with the descriptions here:

https://github.com/shakacode/bootstrap-loader/blob/master/README.md#prebootstrapcustomizations

Please submit a PR if you could clarify it more. 

Basically, it's all about whether you want to define variables that bootstrap will use if defined, or if you want to change values after bootstrap had defined variables.
