### ISSUE TITLE
Constantly bootstrap-loader folder in the node_module dir get renamed to .bootstrap-loader.DELETE

### ISSUE THREAD

**Issue by FakhruddinAbdi** [shakacode/bootstrap-loader#65]
I'm using react starter kit as a boilerplate for building react application 
For loading bootstrap i'm using BL (bootstrap-loader) and it was working fine.
After a while, when i installed react-bootstrap alongside BL, i saw an error 
`ERROR in multi main
    Module not found: Error: Cannot resolve module 'bootstrap-loader' in /Users/fakhruddinabdi/WebstormProjects/zeyton
     @ multi main
`
So i double check node_module for the folder and i saw it was renamed to .bootstrap-loader.DELETE

What's wrong with it ?

**Comment by justin808** [comment]
`rm -rf node_modules npm-shrinkwrap.json && npm i`

Try that.
