### ISSUE TITLE
Is it possible to use bootstrap-loader without jQuery?

### ISSUE THREAD

**Issue by LukasBombach** [shakacode/bootstrap-loader#66]
I am using a very simple webpack config to use `bootstrap-loader`:

```javascript
const path = require('path');
const autoprefixer = require('autoprefixer');

module.exports = {

  entry: [
    'bootstrap-loader',
    './client/javascript/index',
  ],

  output: {
    path: path.join(__dirname, 'client_releases', 'development'),
    filename: 'storytelling.js',
  },

  // devtool: '#cheap-module-eval-source-map',

  module: {
    loaders: [
      { test: /\.jsx?$/, exclude: /(node_modules|bower_components)/, loader: 'babel' },
      { test: /\.css$/, loaders: ['style', 'css', 'postcss'] },
      { test: /\.scss$/, loaders: ['style', 'css', 'postcss', 'sass'] },
      { test: /\.woff2?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url?limit=10000' },
      { test: /\.(ttf|eot|svg)(\?[\s\S]+)?$/, loader: 'file' },
    ],
  },

  postcss: [autoprefixer],

};
```

This leaves me with the error

> Uncaught ReferenceError: jQuery is not defined

We know how *en-vogue* it is not to use jQuery and in fact we really don't need it (or want it). Is it possible to use `bootstrap-loader` without jQuery?

**Comment by justin808** [comment]
@LukasBombach Don't load the bootstrap scripts.

set these to false:

```js
### Bootstrap scripts
scripts:
  transition: true
  alert: true
  button: true
  carousel: true
  collapse: true
  dropdown: true
  modal: true
  tooltip: true
  popover: true
  scrollspy: true
  tab: true
  affix: true
```

https://github.com/shakacode/bootstrap-loader/blob/master/.bootstraprc-3-default#L104

You might be able to just remove that section. I don't remember if we default to false or true in that case.

**Comment by LukasBombach** [comment]
Awesome, thank you!

**Comment by alexfedoseev** [comment]
@LukasBombach You can just set:

```yaml
scripts: false
```

**Comment by justin808** [comment]
@LukasBombach Can you please verify this is documented well and if not, please submit a PR to the README.

**Comment by LukasBombach** [comment]
I would not have guessed that disabling all scripts would effectively be the solution to get rid of jQuery. I feel that it is a use case shared by some and it's hard to find anything on it via Google, so I am creating a PR to point it out a bit more.
