### ISSUE TITLE
Allow writing config to package.json

### ISSUE THREAD

**Issue by LukasBombach** [shakacode/bootstrap-loader#68]
I personally do not like to pollute my project with numerous dot-files for configuration. Many libraries nowadays offer writing their configuration to the package.json file. This is particularly nice when all you need is only a few configurations like disabling scripts to disable jQuery. As an alternative (or addition), I'd find it nice to be able to add the path to an actual config file, so I may be able to put all my config files to a config folder instead of having a messy root folder.

**Comment by justin808** [comment]
There's too much configuration to add this to package.json and you can't easily put comments in there.

We do have another request to customize the location of that file. It would be **AWESOME** if you could submit a PR for one.

**Comment by justin808** [comment]
See #35.
