### ISSUE TITLE
Unable to load WOFF, WOFF2, TTF files from browser

### ISSUE THREAD

**Issue by derrekyoung** [shakacode/bootstrap-loader#73]
I've got bootstrap-loader mostly working with bootstrap-react. I'm using Bootstrap 3 with default dootstrap-loader config in my `.bootstraprc`. 

I'm using webpack to build the app, and webpack is spitting the bundled JS, CSS and artifacts into the `./build/ `directory. My JS loads fine and bootstrap-loader is applying Bootstrap to the page.

My problem is that when I try to add a glyphicon I get 404 errors in the browser console about woff, woff2 and ttf files. Well, that's because the bootstrap css is trying to get the files at l`ocalhost/file-name-here.woff` and so on. Those files are being put under the ./build/ directory so the compiled CSS should be looking at `localhost/build/file-name-here.woff`.

Any ideas how I can address this?

**Comment by justin808** [comment]
Glyphicons in bootstrap 3 (removed in bootstrap 4) should work fine as-is. @derrekyoung can you study the example here and compare to yours: https://github.com/shakacode/bootstrap-loader/blob/master/examples%2Fbasic%2F.bootstraprc-3-example

**Comment by lxcid** [comment]
I'm getting the same issue as well. the problem is that bootstrap-loader assume that these assets are located in the root of the url. It would be great if we can provide an path to the bin/dist/build directory accessible from the web.

**Comment by lxcid** [comment]
This is not an issue related to bootstrap-loader. The solution is to specific the publicPath of output in webpack.config.js.

See https://github.com/webpack/docs/wiki/configuration#outputpublicpath

**Comment by justin808** [comment]
@lxcid Thanks for the help!
