### ISSUE TITLE
outputStyle doesn't work

### ISSUE THREAD

**Issue by C3PablO** [shakacode/bootstrap-loader#76]
Hello! First of all, thanks for this awesome library.

I'm extracting scss files and setting `outputStyle=compressed` in .bootstraprc but the output file contains bootstrap expanded and also inline source map comment which makes the file very heavy.
.bootstraprc:
```
# Webpack loaders, order matters
styleLoaders:
  - style
  - css
  - sass?outputStyle=compressed
```

webpack.config.js:
```
const config = {
  entry: [
    'webpack-hot-middleware/client',
    'bootstrap-loader/extractStyles',
    './src/index',
  ],
  output: {
    //...
  },
  module: {
    loaders: [
      //...
      { test: /\.css$/, loaders: [ 'style', 'css'] },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract(
          'style',
          'css' +
          '!sass' +
          '!sass-resources'
        ),
      }
    ]
  },
  sassLoader: {
    outputStyle: 'compressed',
  },
  sassResources: path.resolve(__dirname, 'src/sass-resources/variables.scss'),
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new ExtractTextPlugin('app.css'),
  ],
};
```

Any idea if there is something wrong? I'm trying the same thing with the examples but I'm getting the same result

**Comment by C3PablO** [comment]
I can solve the problem about the inline source map comment adding `sourceMap=false` in .bootstraprc but I can't find a way to compress bootstrap styles

**Comment by justin808** [comment]
Maybe compression is something that should be done at the webserver level?

If you think there's a valid feature missing, please submit a PR.

For Rails apps, the gziping of assets is configured once for the server.

**Comment by C3PablO** [comment]
I think a bug more than a PR. The documentation paragraph about styleLoaders says it's possible to pass loader params, which is possible but outputStyle doesn't work. In fact, documentation shows an example passing `outputStyle`.

**Comment by justin808** [comment]
I'm open to any additional suggestions on whether or not bootstrap-loader should do compression.
