### ISSUE TITLE
Module build failing at 'Argument `$color` of `lightness($color)` must be a color'

### ISSUE THREAD

**Issue by storrdev** [shakacode/bootstrap-loader#78]
I'm new to webpack so sorry if this is an obvious answer.

I'm using the [react starter kit](https://github.com/kriasoft/react-starter-kit) to create an app which uses the [isomorphic style loader](https://github.com/kriasoft/isomorphic-style-loader).

I wish to add some custom rules to the .btn class and figured the best way to do so would be to @import the bootstrap sass file in my scss file and use @include button-varient() so I've imported bootstrap sass at the top of my scss file like so:

`@import '../../../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss';`

and change my webpack config for .scss files to this:

```
{
        test: /\.scss$/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${DEBUG ? 'sourceMap&' : 'minimize&'}modules&localIdentName=` +
          `${DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]'}`,
          'postcss-loader?parser=postcss-scss',
          'sass'
        ],
 }
```

but when I start the server and webpack runs I get get this error (among many others):

```
    ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]_[hash:base64:3]!./~/postcss-loader?parser=postcss-scss!./~/sass-loader!./src/components/ContentPage/ContentPage.scss
    Module build failed: 
    $gray-darker:           color(black lightness(+13.5%)); /* #222 */
                                       ^
          Argument `$color` of `lightness($color)` must be a color
    
    Backtrace:
    	src/components/variables.scss:6, in function `lightness`
    	src/components/variables.scss:6
          in /Users/storr/dev/ACME/src/components/variables.scss (line 6, column 37)
     @ ./src/components/ContentPage/ContentPage.scss 2:18-270 19:6-25:8 20:25-277
```

Any help would be appreciated, thanks.

**Comment by justin808** [comment]
The error is:

>   Argument `$color` of `lightness($color)` must be a color

You are passing 13.5%
