### ISSUE TITLE
Navbar styles don't seem to be working with Bootstrap 4

### ISSUE THREAD

**Issue by Gacnt** [shakacode/bootstrap-loader#8]
I have installed the package using the guide on the readme, everything seems to be working fine.

But it seems that the navbar styles don't seem to be working, e.g. this is my navbar:

http://v4-alpha.getbootstrap.com/components/navbar/#color-schemes
   ```
   <nav class="navbar navbar-dark bg-inverse">
        <a href="#" class="navbar-brand">PugIt</a>
        <ul class="nav navbar-nav">
            <li class="nav-item active">
                <a href="/home" class="nav-link"><i class="fa fa-home"> </i> Home</a>
            </li>
            <li class="nav-item">
                <a href="/about" class="nav-link"><i class="fa fa-ellipsis-v"> </i> About Us</a>
            </li>
            <li class="nav-item">
                <a href="/faq" class="nav-link"><i class="fa fa-question"> </i> FAQ</a>
            </li>
        </ul>
        <ul class="nav navbar-nav pull-right">
            <li class="nav-item">
                <a href="/auth/steam" class="navButtonLogin nav-link"></a>
            </li>
        </ul>
    </nav>
```

But my navbar has no background at all, but it doesn't structure properly so am I missing something? I'm using the config file from the default .bootstrap4rc or whatever thanks.

**Comment by justin808** [comment]
@Gacnt Can you create a super simple fork of the https://github.com/shakacode/bootstrap-loader/blob/master/examples%2Fbasic%2FREADME.md that demonstrates this issue. Thanks.

**Comment by justin808** [comment]
@Gacnt Any more details on this one? Once you have a reproducible case, we'll do a fix. Or feel free to submit a PR. Please reopen when you have more details.

**Comment by Agowan** [comment]
Hi @justin808, I've got the same problem and have managed to reproduce the problem.

https://github.com/Agowan/twbs-4-dark-navbar-problem

I'm using:
*node: 5.4.1
npm: 3.5.3*

**Comment by alexfedoseev** [comment]
@Agowan Thanks for repo! :+1:  I'll take a look today / tomorrow.

**Comment by hedefalk** [comment]
+1 Can't see the navbar.

**Comment by hedefalk** [comment]
I'm not allowed to re-open this, but I'm having the exact same issue. Styling for navbar is all weird - all white. How can this be? I have no custom css at this point.

**Comment by alexfedoseev** [comment]
I missed this one yesterday b/c it was closed. @hedefalk Your PR (https://github.com/shakacode/bootstrap-loader/pull/28) solves it?

/cc: @justin808

**Comment by hedefalk** [comment]
Yes, the pr fixes it.

**Comment by alexfedoseev** [comment]
`1.0.7` published. Thanks, @hedefalk!
