### ISSUE TITLE
Excessive amount of console log after executing 'webpack' in console

### ISSUE THREAD

**Issue by nicolasxu** [shakacode/bootstrap-loader#81]
The log shows about 30 of: 
==== JS stack trace =========================================
...
==== C stack trace ===============================
...
It is not relevant to setting in the .bootstraprc file, e.g:
\# Output debugging info
loglevel: disabled

How can I disable the stack trace info when executing 'webpack' command in console?

**Comment by alexfedoseev** [comment]
@nicolasxu Can you remove `bootstrap-loader` and check if output is gone / still there? I'm not logging anything like this.

**Comment by nicolasxu** [comment]
Thanks for the suggestion. After removing bootstrap-loader, the log is gone. The log is from a sub module 'bootstrap-sass', a dependency of bootstrap-loader. The content of log is warning for future deprecation. The version of my 'bootstrap-sass' is 3.3.6. 

Log example:
==== JS stack trace =========================================

Security context: 0x38ca36dc9fa9 <JS Object>#0#
    1: /* anonymous */ [/Users/nick/Documents/projects/canvas-demo/node_modules/node-sass/lib/index.js:356] [pc=0x3f191e22ade8] (this=0x38ca36de99f1 <JS Global Object>#1#,options=0x16a3589c4061 <an Object with map 0x11ca0a67ba51>#2#,cb=0x16a3589c91d1 <JS Function (SharedFunctionInfo 0x3bc1ae42a319)>#3#)
    2: /* anonymous */ [/Users/nick/Documents/projects/canvas-demo/node_modules/async/lib/async.js:987] [pc=0x3f191e22a8ae] (this=0x38ca36de99f1 <JS Global Object>#1#,items=0x16a3589c9041 <JS Array[1]>#4#,cb=0x16a3589c91d1 <JS Function (SharedFunctionInfo 0x3bc1ae42a319)>#3#)
    3: _onImmediate [/Users/nick/Documents/projects/canvas-demo/node_modules/async/lib/async.js:953] [pc=0x3f191e22a27d] (this=0x16a3589c53d9 <an Immediate with map 0x11ca0a67b161>#5#)
    4: tryOnImmediate(aka tryOnImmediate) [timers.js:543] [pc=0x3f191e0d94da] (this=0x38ca36d04189 <undefined>,immediate=0x16a3589c53d9 <a 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: CallbackBridge<Sass_Import**, void*>::get_wrapper_constructor()
 3: CallbackBridge<Sass_Import**, void*>::CallbackBridge(v8::Local<v8::Function>, bool)
 4: ExtractOptions(v8::Local<v8::Object>, void*, sass_context_wrapper*, bool, bool)
 5: render(Nan::FunctionCallbackInfo<v8::Value> const&)
 6: Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&)
 7: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 8: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>)
 9: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
10: 0x3f191db0961b
11: 0x3f191e22ade8
12: 0x3f191e22a8ae
13: 0x3f191e22a27d

Any suggestion?

**Comment by nicolasxu** [comment]
Btw, I try webpack on your basic example project in "bootstrap-loader/examples/basic/", it also logs lots of C stack trace.

**Comment by csmalin** [comment]
That only happens for me on Node 6.0, I've reverted back to v5.11.1 and it went away.

**Comment by dguo** [comment]
I had the same experience as @csmalin. Try updating your version of `node-sass` to [3.7.0](https://github.com/sass/node-sass/releases/tag/v3.7.0), which is Node v6 compatible. That fixed it for me.
