### ISSUE TITLE
Poor HMR performance when adding 'bootstrap-loader'

### ISSUE THREAD

**Issue by hoschi** [shakacode/bootstrap-loader#82]
Hi,

before adding bootstrap-loader to my webpack config, HMR changes were served in ~200-350ms. The timings are from webpack when it says "webpack built HASH in X ms". After adding bootstrap-loader this time degraded to around ~2500-3000ms. I checked also the 'css-modules' examples and the timing here is also always above 2000ms. Is this fixable? I don't know what bootstrap-loader performs when HMR is activated, but I would love exchange some loader features/update stuff for faster HMR updates instead.

**Comment by IAMtheIAM** [comment]
I have this problem too. My recompile is 1.4 seconds without bootstrap-loader, and 7 seconds with it. What is causing this?

**Comment by justin808** [comment]
@hoschi @IAMtheIAM Please open a PR if you have a fix or provide some more debugging info. I'll leave this discussion open for a bit longer.

**Comment by hoschi** [comment]
I switched to Material Design (Material-UI)

**Comment by nathanvale** [comment]
This is not a problem you have with bootstrap-loader. It's sounds like you have not set up up webpack to maximise performance with hot reloading. Creating DLL bundles for vendor modules and your common assets such as your bootstrap sass build and main app style is the way to go.

http://engineering.invisionapp.com/post/optimizing-webpack/

**Comment by justin808** [comment]
@nathanvale OK if we close this issue?

**Comment by nathanvale** [comment]
No problem.
