### ISSUE TITLE
webpack-dev-middleware does not reload when changing .bootstraprc

### ISSUE THREAD

**Issue by nknapp** [shakacode/bootstrap-loader#84]
I haven't much experience with webpack and the bootstrap-loader yet, so I'm not sure whether I got something wrong. I forked vigetlabs' (gulp-starger)[https://github.com/gachou/gulp-starter]-repository
and included the bootstrap-loader [in this commit](https://github.com/gachou/gulp-starter/commit/59e1ad1fb80c8d009440d0a888fb6123efc2f7c7).
Everything worked fine pretty quickly, except one thing: When I run the `webpack-dev-middleware` with `npm start`. I would like to have the SASS and the JavaScript  rebuilt when I change the configuration in `.bootstraprc`, since it changes the resulting CSS and JavaScript. That currently does not happen in my configuration.

Since I don't know how exactly the watcher determines which files to watch, I have the question. 
Is this something that can be solved appropriately through webpack configuration, or it this something that must be done in the `bootstrap-loader`?

I have tried to use `gulp watch` to run the SASS-task (which worked) and `webpack-dev-middleware.run()` (which didn't).

**Comment by alexfedoseev** [comment]
Same as if you'd change webpack config. It's build config, but not build target, so it's not a subject for hot reloading. Sorry, wontfix.
