### ISSUE TITLE
transition.js:59Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by pearljamik** [shakacode/bootstrap-loader#85]
When I use require('bootstrap-loader'); my app wont start:

The following error appears:
transition.js:59Uncaught ReferenceError: jQuery is not definedwebpackJsonp.513 @ transition.js:59__webpack_require__ @ bootstrap 95cfe20…:50webpackJsonp.402 @ no-op.js?cb73:1__webpack_require__ @ bootstrap 95cfe20…:50webpackJsonp.401 @ no-op.js:2__webpack_require__ @ bootstrap 95cfe20…:50webpackJsonp.501 @ loader.js:1__webpack_require__ @ bootstrap 95cfe20…:50webpackJsonp.386 @ index.ts:8__webpack_require__ @ bootstrap 95cfe20…:50webpackJsonp.393 @ main.browser.ts:17__webpack_require__ @ bootstrap 95cfe20…:50webpackJsonp.0 @ main.bundle.js:8__webpack_require__ @ bootstrap 95cfe20…:50webpackJsonpCallback @ bootstrap 95cfe20…:21(anonymous function) @ main.bundle.js:1

**Comment by nathaliesicard** [comment]
Same here! I also added the loader in webpack.config.js:

      { test:/bootstrap-sass[\/\\]assets[\/\\]javascripts[\/\\]/, loader: 'imports?jQuery=jquery' }

And I get the exact same error.

**Comment by nathaliesicard** [comment]
I actually just got it solved. I added this line in my app.js:

`global.jQuery = require('jquery');`

Right before:

`require('bootstrap-loader');`

**Comment by AllenFang** [comment]
```js
plugins: [
    new webpack.ProvidePlugin({
        jQuery: 'jquery'
    })
]
```
Maybe try to add this in your webpack ?!

**Comment by justin808** [comment]
Seems like this could just be a doc issue. Please comment if we should re-open this one.

**Comment by denizdogan** [comment]
I think the documentation should definitely be extended to explain that jQuery needs to be included "manually", i.e. `npm install jquery` and then use something like `ProvidePlugin`.

**Comment by justin808** [comment]
We have this documented here:

https://github.com/shakacode/bootstrap-loader#jquery

We have examples here:

* https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic/package.json#L47
* https://github.com/shakacode/bootstrap-loader/blob/master/examples/basic/webpack.dev.config.js#L59

**Comment by heroselohim** [comment]
I know this issue is closed. But to solve this problem I had to define the global '_jquery_' in **lowercase**.

    global.jquery = jQuery

**Comment by justin808** [comment]
@heroselohim any doc PR needed?

**Comment by phfoxer** [comment]
Add alias on webpack
![image](https://user-images.githubusercontent.com/5194383/35792913-2a354d0e-0a2e-11e8-96b1-40b48659a6b4.png)

see #2180

**Comment by ccmcbeck** [comment]
If you are using Docker, remember to copy `.boostraprc` into your container or you'll get the same problem.
