### ISSUE TITLE
Enable sourcemaps per environment

### ISSUE THREAD

**Issue by JulioC** [shakacode/bootstrap-loader#86]
Is it possible to enable the generation of sourcemaps only if env is set to development?

**Comment by programbo** [comment]
I've been looking to see if this is a feature of bootstrap-loader. Looks like it's not.

**Comment by justin808** [comment]
This would probably take a PR to do this. This seems like a reasonable request.

What is the downside to building source maps for the production env?

@JulioC or @programbo, are either of you interested in doing a PR?

**Comment by programbo** [comment]
Sounds reasonable. I had a look at the source a while ago and it seemed pretty straightforward. 

Sent from my iPhone




On Sun, Jun 26, 2016 at 7:22 AM +0800, "Justin Gordon" <notifications@github.com> wrote:












This would probably take a PR to do this. This seems like a reasonable request.



What is the downside to building source maps for the production env?



@JulioC or @programbo, are either of you interested in doing a PR?

**Comment by justin808** [comment]
@programbo A PR would be great.

**Comment by Judahmeek** [comment]
I'm not one to steal another's thunder, but I'd be happy to submit a PR in your place if you would like, @programbo . That said, I'm not even sure what a source map looks like, so any guidance would be appreciated.

**Comment by justin808** [comment]
@Judahmeek @programbo @JulioC Is this still necessary? or useful?

**Comment by JulioC** [comment]
For me it's not necessary, we ended up developing the application without source maps for Bootstrap.

For the loader itself, I believe it would be a good addition if it doesn't take long do.

**Comment by gilhanan** [comment]
I think ability to load configuration options as module would solved that
