### ISSUE TITLE
`bootstrap-loader` Reruns During `webpack --watch` When Isolated, Non-Style Files Change

### ISSUE THREAD

**Issue by carbonizer** [shakacode/bootstrap-loader#88]
I don't know if this is an issue, or if I am misunderstanding how `webpack` and/or `bootstrap-loader` works.

In the interest of faster builds, I separated my custom app code and vendor code into two bundles
I separated my config into an app. Running `webpack --watch`, when I change my `appStyles` file, `bootstrap-loader` is triggered and the vendor bundle rebuilds as I expect. However, if I change the logic in my app code, as part of building the app bundle, `bootstrap-loader` is unexpectedly triggered as well. 

To debug the issue, I added the `--display-modules` and `--display-reasons` flags to the `webpack` command.  My app logic changes update only the app bundle (as expected), but the reasons given include `[158] ./~/css-loader!./~/resolve-url-loader!./~/sass-loader??sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js 162 kB {1} [built]...` which is a reference to a part of the vendor bundle (which is not updated). It is as if `bootstrap-loader` is building something then throwing it away because it realizes nothing has changed after the fact. The result is accomplishing nothing other than increasing a ~500ms operation to ~3500ms. The increase in time taken is annoying when I am making little changes back-to-back.

Is this an issue, or am I misunderstanding something? Did I overlook a configuration option somewhere?

**Note:** I found that I didn't have the issue if I commented out `appStyles` in `.bootstraprc`.

Thank you for any insight anyone can provide.

**Comment by justin808** [comment]
@carbonizer If you're using app styles, then you can access bootstrap variables, which is correct. The downside is that you rebuild all CSS with every change to your CSS in your application styles. I don't know of any way around that.

Please close this issue if this answers your question.

**Comment by danwashusen** [comment]
> The downside is that you rebuild all CSS with every change to your CSS in your application styles.

Any chance you could clarify this a little? 

We're converting over a big backbone app from requirejs to webpack and its working but incremental builds are taking around 15 seconds to complete (for a single line change to a coffeescript file). From fairly basic understanding of webpack output suggests that some 12+ seconds of the 15 is spent in the bootstrap-loader plugin.

Commenting out appStyles (as mentioned above) seemed to make it a little faster (say 10 seconds from memory) but still unworkable.

**Comment by justin808** [comment]
@danwashusen I'm going to close this, as I don't see what the next step would be. I think you might have some issues related to:

> big backbone app

At a certain size, you'll probably need to look at optimizing this.
