### ISSUE TITLE
sourcemap getting created in bundle

### ISSUE THREAD

**Issue by pranaydutta89** [shakacode/bootstrap-loader#89]
big sourcemap are getting created for .css, .ttf and .eot, how to disable them with .bootstraprc, please help me with the issue

**Comment by justin808** [comment]
@pranaydutta89 I think your "issue" is really more of a doc request. Did you try asking on StackOverflow? Note, you can pass some options.

See this section of the docs:

https://github.com/shakacode/bootstrap-loader/blob/master/README.md#paths-to-custom-assets

@pranaydutta89 Please let me know if I can close this issue. If you like, you can submit a PR for some doc on this issue.
