### ISSUE TITLE
Question: How to use JSX?

### ISSUE THREAD

**Issue by thevangelist** [shakacode/bootstrap-loader#91]
AFAIK you're using vanilla HTML here: https://github.com/shakacode/bootstrap-loader/blob/master/examples/css-modules/app/components/GlyphIcons/GlyphIcons.jsx on low level 
`<span className="glyphicon glyphicon-headphones"/>` instead of say `<Glyphicon name='headphones' />` or so, can I do that?

This seems possible in the deprecated version of https://github.com/shakacode/bootstrap-sass-loader, but I wouldnt like to use it if it's deprecated.

Am I missing something or how do I simply get those custom bootstrap variables in my setup & use JSX directly imported to my JSX files?

Hit me a question if I am being unclear.

**Comment by evansb** [comment]
You can use `react-bootstrap` which provides React component wrapper for Bootstrap components.

**Comment by justin808** [comment]
@evansb is correct.
