### ISSUE TITLE
sass-loader 3.2.2 source-map error

### ISSUE THREAD

**Issue by chrisblossom** [shakacode/bootstrap-loader#94]
I updated to [jtangelder/sass-loader@3.2.2](https://github.com/jtangelder/sass-loader/blob/master/CHANGELOG.md) and am now getting this error:

```js
    WARNING in ./~/css-loader!./~/postcss-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js
      resolve-url-loader cannot operate: source-map error
      cannot establish a common base path for all sources in the incoming source-map
```

Any ideas? Maybe I should open this issue with [bholloway/resolve-url-loader](https://github.com/bholloway/resolve-url-loader)?

https://github.com/jtangelder/sass-loader/pull/250

**Comment by tquetano-r7** [comment]
I'm getting the same issue with v4.0.0 of the sass-loader (which is the same as v3.2.2, but bumped major versions due to breaking changes). Just figured I would call this out.

**Comment by rjbergerud** [comment]
Same issue here.  I get the @chrisblossom 's error when I run webpack, and @tquetano-r7 's error when I run webpack-dev-server.

**Comment by iltegin** [comment]
This issue source new 4.0.0 sass-loader version. Previous version 3.2.0 works.

**Comment by justin808** [comment]
@iltegin @rjbergerud @tquetano-r7 @chrisblossom At the minimum, we should document this. I'm totally open to a PR for this. @alexfedoseev and I are totally slammed shipping our new product. Basically, that means that we'll be enhancing this when we get PRs, or when we put in changes that we're using in our product or a client. 

Thanks in advance for help on this issue. I'd like to get this one solved!

**Comment by janusch** [comment]
I am using:

```
"bootstrap": "4.0.0-alpha.2",
"bootstrap-loader": "^1.1.0",
"sass-loader": "^4.0.0"
```

and this is not an issue anymore. I think you can close it @justin808 
Btw, thanks for your great work on maintaining this incredible loader again!

**Comment by justin808** [comment]
Thanks @janusch!
