### ISSUE TITLE
Simpler Bootswatch instructions

### ISSUE THREAD

**Issue by fdcastel** [shakacode/bootstrap-loader#96]
I believe the recipe for [Incorporating Bootswatch themes](https://github.com/shakacode/bootstrap-loader#incorporating-bootswatch-themes) could be simplified to:

1) Install Bootswatch

```
npm install --save bootswatch
```

2) Add to `.bootstraprc`:

```
  "preBootstrapCustomizations": "./node_modules/bootswatch/<THEME>/_variables.scss",
  "appStyles": "./node_modules/bootswatch/<THEME>/_bootswatch.scss"
```

replacing `<THEME>` with the name of chosen theme (e.g. `superhero`).

Doing this way there's no need to create any additional files nor directories. 

Could somebody please test this? Do you see any problems doing this way?

Pinging: @larsw 

Related: #20

**Comment by justin808** [comment]
@fdcastel If you're pretty sure of this, create a PR.

**Comment by wphampton** [comment]
This seems like it should work, however using both methods (yours proposed above and the current docs with separate _bs-theme.scss_) I'm seeing the behavior similar to #20 with the _superhero_ there: "No mixin named box-shadow".  Using the _spacelab_ theme I get different mixin errors.  Any ideas @larsw ?

**Comment by larsw** [comment]
Hi,

 Sorry, I haven't looked into this for a while.

 --larsw

**Comment by Judahmeek** [comment]
@wphampton Do you have a public example repository, by any chance?

**Comment by wphampton** [comment]
I do not, sorry.  I ended up taking a different approach when I could not figure it out.  It could have been user error so please don't hold the issue open solely on my one comment above.  Thanks!
